//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCOUNTINFO
    {
        public int AI_CUSTOMEROID { get; set; }
        public int AI_CUSTOMERTID { get; set; }
        public string AI_TYPE { get; set; }
        public string AI_CURRENCY { get; set; }
        public string AI_KIND { get; set; }
        public decimal AI_OVERPAY { get; set; }
        public decimal AI_REMAIN { get; set; }
        public decimal AI_BALANCE { get; set; }
        public Nullable<decimal> AI_PERSONAL_ACCOUNT { get; set; }
    
        public virtual CURRENCY CURRENCY { get; set; }
        public virtual CUSTOMER CUSTOMER { get; set; }
    }
}
