//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANALYTICTAX_DETAIL
    {
        public int OID { get; set; }
        public int TID { get; set; }
        public int ANTD_ANALYTICTAXOID { get; set; }
        public int ANTD_ANALYTICTAXTID { get; set; }
        public Nullable<int> ANTD_IINVOICEOID { get; set; }
        public Nullable<int> ANTD_IINVOICETID { get; set; }
        public Nullable<int> ANTD_OINVOICEOID { get; set; }
        public Nullable<int> ANTD_OINVOICETID { get; set; }
        public int ANTD_INVDETOID { get; set; }
        public int ANTD_INVDETTID { get; set; }
        public int ANTD_TAXDEFID { get; set; }
        public double ANTD_NETTO { get; set; }
        public double ANTD_BRUTTO { get; set; }
        public double ANTD_TAXVALUE { get; set; }
        public double ANTD_CURRENCY_RATE { get; set; }
        public string ANTD_TAXAREA { get; set; }
        public System.DateTime ANTD_TAXDATE { get; set; }
        public string ANTD_TORATE { get; set; }
        public string ANTD_DIVIDED { get; set; }
        public double ANTD_PERIODSETTLE { get; set; }
        public string ANTD_ISSETTLED { get; set; }
        public string ANTD_ISFULLCHARGED { get; set; }
        public string ANTD_ISVALID { get; set; }
        public string ANTD_ISREVISION { get; set; }
        public string ANTD_ISDEPOSIT { get; set; }
        public string ANTD_IDUETOSTORNO { get; set; }
        public string ANTD_ODUETOSTORNO { get; set; }
        public string ANTD_PROCESSED { get; set; }
        public string ANTD_REQUEST { get; set; }
        public string ANTD_RTYPE { get; set; }
        public string ANTD_ITYPE { get; set; }
        public Nullable<int> ANTD_OCCUREDOID { get; set; }
        public Nullable<int> ANTD_OCCUREDTID { get; set; }
    
        public virtual ANALYTICTAX ANALYTICTAX { get; set; }
        public virtual TAXDEF TAXDEF { get; set; }
        public virtual I_INVOICE I_INVOICE { get; set; }
        public virtual O_INVOICE O_INVOICE { get; set; }
    }
}
