//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANALYTICTAX_INVOICECONTRACT
    {
        public int OID { get; set; }
        public int TID { get; set; }
        public int ANTIC_ANALYTICTAXOID { get; set; }
        public int ANTIC_ANALYTICTAXTID { get; set; }
        public int ANTIC_INVOID { get; set; }
        public int ANTIC_INVTID { get; set; }
        public int ANTIC_CUSTOMEROID { get; set; }
        public int ANTIC_CUSTOMERTID { get; set; }
        public double ANTIC_NETTO { get; set; }
        public double ANTIC_TAXVALUE { get; set; }
        public double ANTIC_CURRENCY_RATE { get; set; }
        public System.DateTime ANTIC_TAXDATE { get; set; }
    
        public virtual ANALYTICTAX ANALYTICTAX { get; set; }
        public virtual CUSTOMER CUSTOMER { get; set; }
    }
}
