//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AVAILABLESTOCKLOG
    {
        public int ASL_PARTITIONTID { get; set; }
        public Nullable<int> ASL_WAREHOUSEID { get; set; }
        public Nullable<int> ASL_PRODUCTOID { get; set; }
        public Nullable<int> ASL_PRODUCTTID { get; set; }
        public System.DateTime ASL_BEGINTIME { get; set; }
        public int ASL_BEGINDATEI { get; set; }
        public int ASL_BEGINTIMEI { get; set; }
        public Nullable<System.DateTime> ASL_ENDTIME { get; set; }
        public Nullable<int> ASL_ENDDATEI { get; set; }
        public Nullable<int> ASL_ENDTIMEI { get; set; }
        public double ASL_QUANTITY { get; set; }
        public Nullable<int> ASL_QUID { get; set; }
        public int ASL_OID { get; set; }
        public int ASL_TID { get; set; }
        public string ASL_TABLE { get; set; }
        public string ASL_PRFX { get; set; }
        public int ASL_DOID { get; set; }
        public int ASL_DTID { get; set; }
        public string ASL_DTABLE { get; set; }
        public string ASL_DPRFX { get; set; }
        public int ASL_COID { get; set; }
        public int ASL_CTID { get; set; }
        public string ASL_CTABLE { get; set; }
        public string ASL_CPRFX { get; set; }
        public int ASL_CDOID { get; set; }
        public int ASL_CDTID { get; set; }
        public string ASL_CDTABLE { get; set; }
        public string ASL_CDPRFX { get; set; }
        public string ASL_ACTION { get; set; }
        public System.DateTime ASL_ACTIONDATE { get; set; }
        public System.DateTime ASL_DATE { get; set; }
        public string ASL_CONN { get; set; }
        public string ASL_STATE { get; set; }
    
        public virtual PFSTORAGE PFSTORAGE { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual QUANTITY_UNIT QUANTITY_UNIT { get; set; }
    }
}
