//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AVISO_DETAIL
    {
        public int OID { get; set; }
        public int TID { get; set; }
        public int AD_AVISOOID { get; set; }
        public int AD_AVISOTID { get; set; }
        public Nullable<int> AD_PRODUCTOID { get; set; }
        public Nullable<int> AD_PRODUCTTID { get; set; }
        public Nullable<int> AD_PRODUCTORIGINID { get; set; }
        public string AD_CUSTOMCODE { get; set; }
        public double AD_QUANTITY { get; set; }
        public int AD_QUID { get; set; }
        public double AD_UNITPRICE { get; set; }
        public string AD_CURRENCY { get; set; }
        public double AD_CURRENCY_RATE { get; set; }
        public Nullable<double> AD_UNITPRICEBC { get; set; }
        public double AD_PRICEMULTIPLIER { get; set; }
        public Nullable<double> AD_DISCOUNTPERCENT { get; set; }
        public Nullable<decimal> AD_DISCOUNT { get; set; }
        public Nullable<decimal> AD_NETTO { get; set; }
        public int AD_TAXDEFID { get; set; }
        public Nullable<decimal> AD_TAXVALUE { get; set; }
        public Nullable<decimal> AD_BRUTTO { get; set; }
        public Nullable<int> AD_DETAILGROUP { get; set; }
        public string AD_CUSTPRODUCTCODE { get; set; }
        public string AD_DESCRIPTION { get; set; }
        public Nullable<int> AD_CUSTOMCHARGE { get; set; }
        public Nullable<double> AD_CUSTOMPERCENT { get; set; }
        public Nullable<double> AD_GROSSWEIGHT { get; set; }
        public Nullable<double> AD_NETWEIGHT { get; set; }
        public Nullable<decimal> AD_OTHERCOSTBC { get; set; }
    
        public virtual AVISO AVISO { get; set; }
        public virtual CURRENCY CURRENCY { get; set; }
        public virtual PRODUCTORIGIN PRODUCTORIGIN { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual QUANTITY_UNIT QUANTITY_UNIT { get; set; }
        public virtual TAXDEF TAXDEF { get; set; }
    }
}
