//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BANK()
        {
            this.BANKSTAT = new HashSet<BANKSTAT>();
            this.BANKTRANSFER = new HashSet<BANKTRANSFER>();
            this.CONVRATE = new HashSet<CONVRATE>();
            this.CUSTBANK = new HashSet<CUSTBANK>();
            this.DWBANKGUARANTEE = new HashSet<DWBANKGUARANTEE>();
            this.I_SETTLE = new HashSet<I_SETTLE>();
            this.O_SETTLE = new HashSet<O_SETTLE>();
            this.SECTIONBANK = new HashSet<SECTIONBANK>();
            this.TRANSFERTIME = new HashSet<TRANSFERTIME>();
        }
    
        public int BANKID { get; set; }
        public string B_BANKNAME { get; set; }
        public string B_BIC { get; set; }
        public string B_CONTACTNAME { get; set; }
        public Nullable<int> B_TITLEID { get; set; }
        public string B_COUNTRY { get; set; }
        public string B_ZIP { get; set; }
        public string B_CITY { get; set; }
        public string B_STREET { get; set; }
        public string B_PHONE { get; set; }
        public string B_FAX { get; set; }
        public string B_ACCOUNTNUMBER { get; set; }
        public string B_TAXNUMBER { get; set; }
        public string B_COUNTRYCODE { get; set; }
    
        public virtual COUNTRY COUNTRY { get; set; }
        public virtual TITLE TITLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BANKSTAT> BANKSTAT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BANKTRANSFER> BANKTRANSFER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONVRATE> CONVRATE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUSTBANK> CUSTBANK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DWBANKGUARANTEE> DWBANKGUARANTEE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_SETTLE> I_SETTLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<O_SETTLE> O_SETTLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SECTIONBANK> SECTIONBANK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRANSFERTIME> TRANSFERTIME { get; set; }
    }
}
