//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class BINDING_DOCUMENTS
    {
        public int OID { get; set; }
        public int TID { get; set; }
        public int BDD_BINDINGOID { get; set; }
        public int BDD_BINDINGTID { get; set; }
        public string BDD_DOCTYPE { get; set; }
        public int BDD_DOCOID { get; set; }
        public int BDD_DOCTID { get; set; }
        public int BDD_DOCDETOID { get; set; }
        public int BDD_DOCDETTID { get; set; }
        public Nullable<decimal> BDD_WEIGHT { get; set; }
    }
}
