//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class BINDING
    {
        public int OID { get; set; }
        public int TID { get; set; }
        public System.DateTime BD_VALIDFROM { get; set; }
        public System.DateTime BD_VALIDTO { get; set; }
        public string BD_REFERENCENUMBER { get; set; }
        public int BD_CUSTOMEROID { get; set; }
        public int BD_CUSTOMERTID { get; set; }
        public int BD_PRODUCTOID { get; set; }
        public int BD_PRODUCTTID { get; set; }
        public decimal BD_QUANTITY { get; set; }
        public int BD_QUID { get; set; }
        public double BD_UNITPRICE { get; set; }
        public string BD_CURRENCY { get; set; }
        public double BD_CURRENCY_RATE { get; set; }
        public Nullable<decimal> BD_ARRIVED { get; set; }
        public Nullable<decimal> BD_ONWAY { get; set; }
        public string BD_ACTIVE { get; set; }
        public string BD_FINALIZED { get; set; }
        public string BD_NOTE { get; set; }
    }
}
