//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOOKSTOCKSH
    {
        public int BS_TID { get; set; }
        public string BS_CLASS { get; set; }
        public int BS_IDX { get; set; }
        public string BS_ACC { get; set; }
        public int BS_YEAR { get; set; }
        public double BS_Q { get; set; }
        public double BS_V { get; set; }
        public int BS_POID { get; set; }
        public int BS_PTID { get; set; }
        public int BS_CHKTID { get; set; }
        public int BS_CHKOID { get; set; }
        public Nullable<int> BS_QUID { get; set; }
    
        public virtual BOOKCHECKPOINTS BOOKCHECKPOINTS { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual QUANTITY_UNIT QUANTITY_UNIT { get; set; }
    }
}
