//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOOKOUTPUT_PARAMS
    {
        public int OID { get; set; }
        public int TID { get; set; }
        public int BOPD_BOOKOUTPUTOID { get; set; }
        public int BOPD_BOOKOUTPUTTID { get; set; }
        public string BOPD_IDX { get; set; }
        public string BOPD_NAME { get; set; }
        public int BOPD_TYPE { get; set; }
        public string BOPD_SKIP { get; set; }
        public Nullable<int> BOPD_BOUPOID { get; set; }
        public Nullable<int> BOPD_BOUPTID { get; set; }
        public Nullable<int> BOPD_BUDGETCALCOID { get; set; }
        public Nullable<int> BOPD_BUDGETCALCTID { get; set; }
    
        public virtual BOOKOUTPUT BOOKOUTPUT { get; set; }
        public virtual BOOKOUTPUT BOOKOUTPUT1 { get; set; }
        public virtual BUDGETCALC BUDGETCALC { get; set; }
        public virtual BOTYPE BOTYPE { get; set; }
    }
}
