//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOOKCHECKPOINTS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BOOKCHECKPOINTS()
        {
            this.BOOKSTOCKSH = new HashSet<BOOKSTOCKSH>();
            this.BOOKCLOSURE = new HashSet<BOOKCLOSURE>();
            this.BOOKOPENING = new HashSet<BOOKOPENING>();
        }
    
        public int OID { get; set; }
        public int TID { get; set; }
        public string BCP_CLASS { get; set; }
        public int BCP_YEAR { get; set; }
        public System.DateTime BCP_CREATED { get; set; }
        public string BCP_ACTIVE { get; set; }
        public string BCP_NOTE { get; set; }
    
        public virtual MFROOTS MFROOTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOOKSTOCKSH> BOOKSTOCKSH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOOKCLOSURE> BOOKCLOSURE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOOKOPENING> BOOKOPENING { get; set; }
    }
}
