//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOOKOUTPUT_TEMPLATE_CALC
    {
        public int BOUTC_ID { get; set; }
        public int BOUTC_ROW { get; set; }
        public int BOUTC_IDX { get; set; }
        public string BOUTC_METHOD { get; set; }
        public string BOUTC_PARAM { get; set; }
        public string BOUTC_CONDITION { get; set; }
        public string BOUTC_RATEFROM { get; set; }
        public string BOUTC_RATETO { get; set; }
    }
}
