//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class BUDGETCALC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BUDGETCALC()
        {
            this.BOOKOUTPUT_PARAMS = new HashSet<BOOKOUTPUT_PARAMS>();
            this.BUDGETCALC_ELEMENT = new HashSet<BUDGETCALC_ELEMENT>();
        }
    
        public int OID { get; set; }
        public int TID { get; set; }
        public int BCA_BUDGETLEVELID { get; set; }
        public int BCA_IDX { get; set; }
        public string BCA_NAME { get; set; }
        public System.DateTime BCA_STARTDATE { get; set; }
        public System.DateTime BCA_ENDDATE { get; set; }
        public Nullable<int> BCA_PREVOID { get; set; }
        public Nullable<int> BCA_PREVTID { get; set; }
        public Nullable<int> BCA_BOOKOUTPUTOID { get; set; }
        public Nullable<int> BCA_BOOKOUTPUTTID { get; set; }
        public string BCA_ISVALID { get; set; }
        public string BCA_ISEXPIRED { get; set; }
        public string BCA_COMMENT { get; set; }
    
        public virtual BOOKOUTPUT BOOKOUTPUT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOOKOUTPUT_PARAMS> BOOKOUTPUT_PARAMS { get; set; }
        public virtual BUDGETLEVEL BUDGETLEVEL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BUDGETCALC_ELEMENT> BUDGETCALC_ELEMENT { get; set; }
    }
}
