//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_SPOOLINF
    {
        public string TYP { get; set; }
        public string VOT { get; set; }
        public string VON { get; set; }
        public string VT { get; set; }
        public string VE { get; set; }
        public string VN { get; set; }
        public string V { get; set; }
    }
}
