//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CASHDESK_DENOMINATION
    {
        public int CDN_CASHDESKDENID { get; set; }
        public int CDN_CASHDESKID { get; set; }
        public System.DateTime CDN_DATE { get; set; }
        public int CDN_DENOMINATIONID { get; set; }
        public int CDN_QUANTITY { get; set; }
        public Nullable<int> CDN_CLOSEOID { get; set; }
        public Nullable<int> CDN_CLOSETID { get; set; }
    
        public virtual CASHDESK CASHDESK { get; set; }
        public virtual CASHDESK_CLOSE CASHDESK_CLOSE { get; set; }
        public virtual DENOMINATION DENOMINATION { get; set; }
    }
}
