//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CASHDESK_CLOSE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CASHDESK_CLOSE()
        {
            this.CASHDESK_CLOSE_DETAIL = new HashSet<CASHDESK_CLOSE_DETAIL>();
            this.CASHDESK_DENOMINATION = new HashSet<CASHDESK_DENOMINATION>();
        }
    
        public int OID { get; set; }
        public int TID { get; set; }
        public int CDC_CASHDESKID { get; set; }
        public int CDC_NUMBER { get; set; }
        public string CDC_GENNUMBER { get; set; }
        public Nullable<int> CDC_CASHIERID { get; set; }
        public System.DateTime CDC_OPENDATE { get; set; }
        public Nullable<decimal> CDC_OPENINCOME { get; set; }
        public Nullable<decimal> CDC_OPENOUTCOME { get; set; }
        public Nullable<decimal> CDC_OPENBALANCE { get; set; }
        public Nullable<decimal> CDC_INCOME { get; set; }
        public Nullable<decimal> CDC_OUTCOME { get; set; }
        public Nullable<decimal> CDC_BALANCE { get; set; }
        public Nullable<decimal> CDC_CLOSEINCOME { get; set; }
        public Nullable<decimal> CDC_CLOSEOUTCOME { get; set; }
        public Nullable<decimal> CDC_CLOSEBALANCE { get; set; }
        public string CDC_CURRENCYID { get; set; }
        public string CDC_STORNO { get; set; }
        public Nullable<System.DateTime> CDC_STORNODAT { get; set; }
        public string CDC_OK { get; set; }
        public Nullable<System.DateTime> CDC_OKDATE { get; set; }
        public string CDC_NOTE { get; set; }
        public Nullable<int> CDC_SECTIONOID { get; set; }
        public Nullable<int> CDC_SECTIONTID { get; set; }
        public Nullable<System.DateTime> CDC_CLOSEDATE { get; set; }
    
        public virtual CASHDESK CASHDESK { get; set; }
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        public virtual CURRENCY CURRENCY { get; set; }
        public virtual SECTION SECTION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CASHDESK_CLOSE_DETAIL> CASHDESK_CLOSE_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CASHDESK_DENOMINATION> CASHDESK_DENOMINATION { get; set; }
    }
}
