//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CC_EXPANSION
    {
        public int COSTCENTEROID1 { get; set; }
        public int COSTCENTERTID1 { get; set; }
        public int COSTCENTEROID2 { get; set; }
        public int COSTCENTERTID2 { get; set; }
        public double REL { get; set; }
    }
}
