//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CITY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CITY()
        {
            this.CITY_ATTACHMENT = new HashSet<CITY_ATTACHMENT>();
            this.PUBLICPLACE = new HashSet<PUBLICPLACE>();
        }
    
        public int CITYID { get; set; }
        public string CITYNAME { get; set; }
        public string CITYZIP { get; set; }
        public Nullable<int> REGIONID { get; set; }
        public Nullable<double> COORDINATEWIDTH { get; set; }
        public Nullable<double> COORDINATELENGTH { get; set; }
    
        public virtual REGION REGION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CITY_ATTACHMENT> CITY_ATTACHMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PUBLICPLACE> PUBLICPLACE { get; set; }
    }
}
