//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONSIGNMENTREPORT_DETAIL
    {
        public int OID { get; set; }
        public int TID { get; set; }
        public int CRD_CONSIGNMENTREPORTOID { get; set; }
        public int CRD_CONSIGNMENTREPORTTID { get; set; }
        public int CRD_PRODUCTOID { get; set; }
        public int CRD_PRODUCTTID { get; set; }
        public double CRD_QUANTITY { get; set; }
        public Nullable<double> CRD_CQUANTITY { get; set; }
        public int CRD_QUID { get; set; }
        public double CRD_UNITPRICE { get; set; }
        public string CRD_AUTODISCOUNT { get; set; }
        public string CRD_CUSTPRODUCTCODE { get; set; }
        public string CRD_CUSTOMCODE { get; set; }
        public string CRD_SERIALNUMBER { get; set; }
        public string CRD_TAG { get; set; }
        public Nullable<System.DateTime> CRD_LIMITDAY { get; set; }
        public string CRD_DESCRIPTION { get; set; }
        public string CRD_TACC { get; set; }
        public string CRD_KACC { get; set; }
        public Nullable<int> CRD_PROJECTOID { get; set; }
        public Nullable<int> CRD_PROJECTTID { get; set; }
        public double CRD_PRICEMULTIPLIER { get; set; }
        public Nullable<double> CRD_DISCOUNTPERCENT { get; set; }
        public int CRD_TAXDEFID { get; set; }
        public string CRD_CURRENCY { get; set; }
        public double CRD_CURRENCY_RATE { get; set; }
        public string CRD_CONTCODE { get; set; }
        public Nullable<double> CRD_UNITPRICEBC { get; set; }
        public Nullable<decimal> CRD_DISCOUNT { get; set; }
        public Nullable<decimal> CRD_NETTO { get; set; }
        public Nullable<decimal> CRD_TAXVALUE { get; set; }
        public Nullable<decimal> CRD_BRUTTO { get; set; }
        public Nullable<int> CRD_DETAILGROUP { get; set; }
        public string CRD_FORCE { get; set; }
        public Nullable<int> CRD_COSTCENTEROID { get; set; }
        public Nullable<int> CRD_COSTCENTERTID { get; set; }
    
        public virtual CONSIGNMENTREPORT CONSIGNMENTREPORT { get; set; }
        public virtual COSTCENTER COSTCENTER { get; set; }
        public virtual CURRENCY CURRENCY { get; set; }
        public virtual TAXDEF TAXDEF { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual PROJECT PROJECT { get; set; }
        public virtual QUANTITY_UNIT QUANTITY_UNIT { get; set; }
    }
}
