//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTTEMPLATE_DETAIL
    {
        public int OID { get; set; }
        public int TID { get; set; }
        public int CTD_CONTTEMPLATEOID { get; set; }
        public int CTD_CONTTEMPLATETID { get; set; }
        public string CTD_TACC { get; set; }
        public string CTD_KACC { get; set; }
        public string CTD_VALUEKIND { get; set; }
        public string CTD_NOTE { get; set; }
    
        public virtual CONTTEMPLATE CONTTEMPLATE { get; set; }
    }
}
