//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class COSTCENTERPERIODPROJ
    {
        public int OID { get; set; }
        public int TID { get; set; }
        public int CCPP_CCP_CCOID { get; set; }
        public int CCPP_CCP_CCTID { get; set; }
        public int CCPP_CCP_CCPOID { get; set; }
        public int CCPP_CCP_CCPTID { get; set; }
        public double CCPP_REL { get; set; }
        public System.DateTime CCPP_VALIDFROM { get; set; }
        public System.DateTime CCPP_VALIDTO { get; set; }
    
        public virtual COSTCENTER COSTCENTER { get; set; }
        public virtual COSTCENTER COSTCENTER1 { get; set; }
        public virtual COSTCENTERPROJ COSTCENTERPROJ { get; set; }
    }
}
