//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class COSTCENTERPROJ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COSTCENTERPROJ()
        {
            this.COSTCENTERPERIODPROJ = new HashSet<COSTCENTERPERIODPROJ>();
        }
    
        public int CCP_CCOID { get; set; }
        public int CCP_CCTID { get; set; }
        public int CCP_CCPOID { get; set; }
        public int CCP_CCPTID { get; set; }
        public double CCP_REL { get; set; }
        public string CCP_CHANGEABLEREL { get; set; }
    
        public virtual COSTCENTER COSTCENTER { get; set; }
        public virtual COSTCENTER COSTCENTER1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COSTCENTERPERIODPROJ> COSTCENTERPERIODPROJ { get; set; }
    }
}
