//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOPTIONED
    {
        public int CO_PARTITION { get; set; }
        public int CO_EOID { get; set; }
        public int CO_ETID { get; set; }
        public int CO_WAREHOUSEID { get; set; }
        public Nullable<int> CO_CUSTOMEROID { get; set; }
        public Nullable<int> CO_CUSTOMERTID { get; set; }
        public int CO_PRODUCTOID { get; set; }
        public int CO_PRODUCTTID { get; set; }
        public double CO_QUANTITY { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual WAREHOUSE WAREHOUSE { get; set; }
    }
}
