//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMREPORT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CUSTOMREPORT()
        {
            this.CUSTOMREPORT_DETAIL = new HashSet<CUSTOMREPORT_DETAIL>();
        }
    
        public int OID { get; set; }
        public int TID { get; set; }
        public Nullable<int> CR_DOCUOWNNUMBER { get; set; }
        public string CR_DOCUNUMBER { get; set; }
        public int CR_WAREHOUSEID { get; set; }
        public Nullable<int> CR_SECTIONOID { get; set; }
        public Nullable<int> CR_SECTIONTID { get; set; }
        public Nullable<int> CR_EMPLOYEEID { get; set; }
        public System.DateTime CR_DOCUDATE { get; set; }
        public string CR_CURRENCY { get; set; }
        public string CR_OK { get; set; }
        public Nullable<System.DateTime> CR_OKDATE { get; set; }
        public string CR_STORNO { get; set; }
        public Nullable<System.DateTime> CR_STORNODAT { get; set; }
        public Nullable<decimal> CR_CUSTOMPERCENT { get; set; }
        public Nullable<decimal> CR_O_STOCKVALUE { get; set; }
        public Nullable<decimal> CR_O_STSVCUSTOMCHARGE { get; set; }
        public Nullable<decimal> CR_O_STINCUSTOMCHARGE { get; set; }
        public Nullable<decimal> CR_O_STOUTCUSTOMCHARGE { get; set; }
        public Nullable<decimal> CR_O_CUSTOMCHARGE { get; set; }
        public Nullable<decimal> CR_O_PCUSTOMCHARGE { get; set; }
        public Nullable<decimal> CR_C_STOCKVALUE { get; set; }
        public Nullable<decimal> CR_C_STSVCUSTOMCHARGE { get; set; }
        public Nullable<decimal> CR_C_STINCUSTOMCHARGE { get; set; }
        public Nullable<decimal> CR_C_STOUTCUSTOMCHARGE { get; set; }
        public Nullable<decimal> CR_C_CUSTOMCHARGE { get; set; }
        public Nullable<decimal> CR_C_PCUSTOMCHARGE { get; set; }
        public string CR_COMMENT { get; set; }
    
        public virtual CURRENCY CURRENCY { get; set; }
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        public virtual SECTION SECTION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUSTOMREPORT_DETAIL> CUSTOMREPORT_DETAIL { get; set; }
        public virtual WAREHOUSE WAREHOUSE { get; set; }
    }
}
