//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMINFO
    {
        public string CI_CUSTOMCODE { get; set; }
        public int CI_CUSTOMEROID { get; set; }
        public int CI_CUSTOMERTID { get; set; }
        public int CI_ORIGINID { get; set; }
        public double CI_CUSTOMPERCENT { get; set; }
        public Nullable<int> CI_APPEARORDER { get; set; }
        public Nullable<double> CI_ENVIRONMENT_FEE { get; set; }
    
        public virtual CUSTOMCODETAB CUSTOMCODETAB { get; set; }
        public virtual CUSTOMER CUSTOMER { get; set; }
        public virtual PRODUCTORIGIN PRODUCTORIGIN { get; set; }
    }
}
