//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTPHONE
    {
        public int OID { get; set; }
        public int TID { get; set; }
        public int CP_CUSTOMEROID { get; set; }
        public int CP_CUSTOMERTID { get; set; }
        public int CP_PHONETYPEDEFID { get; set; }
        public string CP_COUNTRYPHONE { get; set; }
        public string CP_PHONEAREACODE { get; set; }
        public string CP_PHONE { get; set; }
        public string CP_ACTIVE { get; set; }
        public Nullable<System.DateTime> CP_VALIDTODATE { get; set; }
        public string CP_NOTE { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
        public virtual PHONETYPEDEF PHONETYPEDEF { get; set; }
    }
}
