//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTONTHEWAY
    {
        public int CW_PARTITION { get; set; }
        public int CW_EOID { get; set; }
        public int CW_ETID { get; set; }
        public int CW_WAREHOUSEID { get; set; }
        public int CW_CUSTOMEROID { get; set; }
        public int CW_CUSTOMERTID { get; set; }
        public int CW_PRODUCTOID { get; set; }
        public int CW_PRODUCTTID { get; set; }
        public double CW_QUANTITY { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual WAREHOUSE WAREHOUSE { get; set; }
    }
}
