//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DELIVERYORDERMOD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DELIVERYORDERMOD()
        {
            this.DELIVERYORDERMOD_EXPANDED = new HashSet<DELIVERYORDERMOD_EXPANDED>();
            this.DELIVERYORDERMOD_DETAIL = new HashSet<DELIVERYORDERMOD_DETAIL>();
        }
    
        public int OID { get; set; }
        public int TID { get; set; }
        public int DOM_DELIVERYORDEROID { get; set; }
        public int DOM_DELIVERYORDERTID { get; set; }
        public Nullable<int> DOM_DOCUGENNUMBER { get; set; }
        public Nullable<int> DOM_WAREHOUSEID { get; set; }
        public string DOM_DOCUNUMBER { get; set; }
        public Nullable<int> DOM_SECTIONOID { get; set; }
        public Nullable<int> DOM_SECTIONTID { get; set; }
        public Nullable<int> DOM_EMPLOYEEID { get; set; }
        public System.DateTime DOM_DOCUDATE { get; set; }
        public string DOM_OK { get; set; }
        public Nullable<System.DateTime> DOM_OKDATE { get; set; }
        public string DOM_STORNO { get; set; }
        public Nullable<System.DateTime> DOM_STORNODAT { get; set; }
        public string DOM_COMMENT { get; set; }
        public Nullable<int> DOM_UNOPTIONEDOID { get; set; }
        public Nullable<int> DOM_UNOPTIONEDTID { get; set; }
        public Nullable<int> DOM_WHMODUNOPTIONEDOID { get; set; }
        public Nullable<int> DOM_WHMODUNOPTIONEDTID { get; set; }
        public string DOM_WAREHOUSEMOD { get; set; }
        public Nullable<int> DOM_PROJECTOID { get; set; }
        public Nullable<int> DOM_PROJECTTID { get; set; }
        public Nullable<int> DOM_COSTCENTEROID { get; set; }
        public Nullable<int> DOM_COSTCENTERTID { get; set; }
    
        public virtual COSTCENTER COSTCENTER { get; set; }
        public virtual DELIVERYORDER DELIVERYORDER { get; set; }
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DELIVERYORDERMOD_EXPANDED> DELIVERYORDERMOD_EXPANDED { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DELIVERYORDERMOD_DETAIL> DELIVERYORDERMOD_DETAIL { get; set; }
        public virtual UNOPTIONED UNOPTIONED { get; set; }
        public virtual PROJECT PROJECT { get; set; }
        public virtual SECTION SECTION { get; set; }
        public virtual UNOPTIONED UNOPTIONED1 { get; set; }
        public virtual WAREHOUSE WAREHOUSE { get; set; }
    }
}
