//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DELIVERYOFFER_DETAIL
    {
        public int OID { get; set; }
        public int TID { get; set; }
        public int DFD_DELIVERYOFFEROID { get; set; }
        public int DFD_DELIVERYOFFERTID { get; set; }
        public Nullable<int> DFD_PRODUCTOID { get; set; }
        public Nullable<int> DFD_PRODUCTTID { get; set; }
        public string DFD_CUSTOMCODE { get; set; }
        public double DFD_QUANTITY { get; set; }
        public int DFD_QUID { get; set; }
        public double DFD_UNITPRICE { get; set; }
        public string DFD_CURRENCY { get; set; }
        public double DFD_CURRENCY_RATE { get; set; }
        public Nullable<double> DFD_UNITPRICEBC { get; set; }
        public double DFD_PRICEMULTIPLIER { get; set; }
        public string DFD_AUTODISCOUNT { get; set; }
        public Nullable<double> DFD_DISCOUNTPERCENT { get; set; }
        public Nullable<decimal> DFD_DISCOUNT { get; set; }
        public Nullable<decimal> DFD_NETTO { get; set; }
        public int DFD_TAXDEFID { get; set; }
        public Nullable<decimal> DFD_TAXVALUE { get; set; }
        public Nullable<decimal> DFD_BRUTTO { get; set; }
        public Nullable<System.DateTime> DFD_DELIVERYDATE { get; set; }
        public Nullable<int> DFD_DELIVERYWEEK { get; set; }
        public Nullable<int> DFD_DETAILGROUP { get; set; }
        public string DFD_CUSTPRODUCTCODE { get; set; }
        public string DFD_DESCRIPTION { get; set; }
        public Nullable<System.DateTime> DFD_BEGINTIME { get; set; }
        public Nullable<System.DateTime> DFD_ENDTIME { get; set; }
        public Nullable<int> DFD_PRTN_ID { get; set; }
        public Nullable<int> DFD_PROJECTOID { get; set; }
        public Nullable<int> DFD_PROJECTTID { get; set; }
        public Nullable<int> DFD_OFFERVARIATIONOID { get; set; }
        public Nullable<int> DFD_OFFERVARIATIONTID { get; set; }
        public string DFD_NOTE { get; set; }
        public Nullable<int> DFD_CUSTOMCHARGE { get; set; }
        public Nullable<double> DFD_CUSTOMPERCENT { get; set; }
        public Nullable<double> DFD_GROSSWEIGHT { get; set; }
        public Nullable<double> DFD_NETWEIGHT { get; set; }
        public Nullable<decimal> DFD_OTHERCOSTBC { get; set; }
        public Nullable<int> DFD_COSTCENTEROID { get; set; }
        public Nullable<int> DFD_COSTCENTERTID { get; set; }
    
        public virtual COSTCENTER COSTCENTER { get; set; }
        public virtual CURRENCY CURRENCY { get; set; }
        public virtual DELIVERYOFFER DELIVERYOFFER { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual PC_OFFERVARIATIONS PC_OFFERVARIATIONS { get; set; }
        public virtual PRODUCTRECORDTYPENAME PRODUCTRECORDTYPENAME { get; set; }
        public virtual PROJECT PROJECT { get; set; }
        public virtual QUANTITY_UNIT QUANTITY_UNIT { get; set; }
        public virtual TAXDEF TAXDEF { get; set; }
    }
}
