//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEXTER_INTEGER_PROPS
    {
        public int DXI_TID { get; set; }
        public int DXI_OID { get; set; }
        public int DXI_PRID { get; set; }
        public Nullable<int> DXI_DATA { get; set; }
    }
}
