//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEXTER_FLOAT_PROPS
    {
        public int DXF_TID { get; set; }
        public int DXF_OID { get; set; }
        public int DXF_PRID { get; set; }
        public Nullable<double> DXF_DATA { get; set; }
    }
}
