//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIRECTBUY_DETAIL
    {
        public int OID { get; set; }
        public int TID { get; set; }
        public int DBD_DIRECTBUYOID { get; set; }
        public int DBD_DIRECTBUYTID { get; set; }
        public Nullable<int> DBD_PRODUCTOID { get; set; }
        public Nullable<int> DBD_PRODUCTTID { get; set; }
        public string DBD_CUSTOMCODE { get; set; }
        public double DBD_QUANTITY { get; set; }
        public Nullable<double> DBD_CQUANTITY { get; set; }
        public int DBD_QUID { get; set; }
        public double DBD_UNITPRICE { get; set; }
        public string DBD_CURRENCY { get; set; }
        public double DBD_CURRENCY_RATE { get; set; }
        public Nullable<System.DateTime> DBD_LIMITDAY { get; set; }
        public Nullable<System.DateTime> DBD_GUARANTEEDDATE { get; set; }
        public Nullable<double> DBD_UNITPRICEBC { get; set; }
        public double DBD_PRICEMULTIPLIER { get; set; }
        public Nullable<double> DBD_DISCOUNTPERCENT { get; set; }
        public Nullable<decimal> DBD_DISCOUNT { get; set; }
        public Nullable<decimal> DBD_NETTO { get; set; }
        public int DBD_TAXDEFID { get; set; }
        public Nullable<decimal> DBD_TAXVALUE { get; set; }
        public Nullable<decimal> DBD_BRUTTO { get; set; }
        public Nullable<int> DBD_DETAILGROUP { get; set; }
        public string DBD_SERIALNUMBER { get; set; }
        public string DBD_DESCRIPTION { get; set; }
        public string DBD_CONTCODE { get; set; }
        public string DBD_TAG { get; set; }
        public string DBD_INVCONTCODE { get; set; }
        public string DBD_FORCE { get; set; }
        public string DBD_TACC { get; set; }
        public string DBD_KACC { get; set; }
        public Nullable<int> DBD_PROJECTOID { get; set; }
        public Nullable<int> DBD_PROJECTTID { get; set; }
        public string DBD_CUSTPRODUCTCODE { get; set; }
        public Nullable<int> DBD_COSTCENTEROID { get; set; }
        public Nullable<int> DBD_COSTCENTERTID { get; set; }
    
        public virtual COSTCENTER COSTCENTER { get; set; }
        public virtual CURRENCY CURRENCY { get; set; }
        public virtual DIRECTBUY DIRECTBUY { get; set; }
        public virtual QUANTITY_UNIT QUANTITY_UNIT { get; set; }
        public virtual TAXDEF TAXDEF { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual PROJECT PROJECT { get; set; }
    }
}
