//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIRECTSELL_SERIAL
    {
        public Nullable<double> DSS_C_QUANTITY { get; set; }
        public Nullable<int> DSS_C_QUID { get; set; }
        public string DSS_CONTROLLED { get; set; }
        public Nullable<int> DSS_DETAIL_OID { get; set; }
        public Nullable<int> DSS_DETAIL_TID { get; set; }
        public string DSS_FORCE { get; set; }
        public Nullable<System.DateTime> DSS_LIMITDAY { get; set; }
        public int DSS_MASTER_OID { get; set; }
        public int DSS_MASTER_TID { get; set; }
        public Nullable<double> DSS_MB_QUANTITY { get; set; }
        public Nullable<int> DSS_MB_QUID { get; set; }
        public Nullable<double> DSS_MN_QUANTITY { get; set; }
        public Nullable<int> DSS_MN_QUID { get; set; }
        public Nullable<int> DSS_NOTICEOID { get; set; }
        public string DSS_NUMTYPE { get; set; }
        public int OID { get; set; }
        public Nullable<int> DSS_PFDIVISIONOID { get; set; }
        public Nullable<int> DSS_PFDIVISIONTID { get; set; }
        public Nullable<int> DSS_PRODUCTOID { get; set; }
        public Nullable<int> DSS_PRODUCTTID { get; set; }
        public Nullable<double> DSS_QUANTITY { get; set; }
        public Nullable<int> DSS_QUID { get; set; }
        public string DSS_SERIALNUMBER { get; set; }
        public Nullable<double> DSS_STOCKQUANTITY { get; set; }
        public string DSS_TAG { get; set; }
        public int TID { get; set; }
        public Nullable<double> DSS_UNITPRICEBC { get; set; }
        public Nullable<double> DSS_V_QUANTITY { get; set; }
        public Nullable<int> DSS_V_QUID { get; set; }
    
        public virtual C_QUANTITY_UNIT C_QUANTITY_UNIT { get; set; }
        public virtual DIRECTSELL DIRECTSELL { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
