//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIRECTQUC
    {
        public int DQUC_FROMQUID { get; set; }
        public int DQUC_TOQUID { get; set; }
        public double DQUC_RATE { get; set; }
    }
}
