//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIRECTSELL_DETAIL
    {
        public int OID { get; set; }
        public int TID { get; set; }
        public int DSD_DIRECTSELLOID { get; set; }
        public int DSD_DIRECTSELLTID { get; set; }
        public Nullable<int> DSD_PRODUCTOID { get; set; }
        public Nullable<int> DSD_PRODUCTTID { get; set; }
        public string DSD_CUSTOMCODE { get; set; }
        public double DSD_QUANTITY { get; set; }
        public Nullable<double> DSD_CQUANTITY { get; set; }
        public int DSD_QUID { get; set; }
        public double DSD_UNITPRICE { get; set; }
        public string DSD_CURRENCY { get; set; }
        public double DSD_CURRENCY_RATE { get; set; }
        public Nullable<double> DSD_UNITPRICEBC { get; set; }
        public double DSD_PRICEMULTIPLIER { get; set; }
        public Nullable<double> DSD_DISCOUNTPERCENT { get; set; }
        public Nullable<decimal> DSD_DISCOUNT { get; set; }
        public Nullable<decimal> DSD_NETTO { get; set; }
        public Nullable<System.DateTime> DSD_LIMITDAY { get; set; }
        public Nullable<System.DateTime> DSD_GUARANTEEDDATE { get; set; }
        public int DSD_TAXDEFID { get; set; }
        public Nullable<decimal> DSD_TAXVALUE { get; set; }
        public Nullable<decimal> DSD_BRUTTO { get; set; }
        public Nullable<int> DSD_DETAILGROUP { get; set; }
        public string DSD_FORCE { get; set; }
        public string DSD_SERIALIZED { get; set; }
        public string DSD_AUTODISCOUNT { get; set; }
        public string DSD_SERIALNUMBER { get; set; }
        public string DSD_DESCRIPTION { get; set; }
        public string DSD_CONTCODE { get; set; }
        public string DSD_TAG { get; set; }
        public string DSD_INVCONTCODE { get; set; }
        public string DSD_CUSTPRODUCTCODE { get; set; }
        public string DSD_TACC { get; set; }
        public string DSD_KACC { get; set; }
        public Nullable<int> DSD_PROJECTOID { get; set; }
        public Nullable<int> DSD_PROJECTTID { get; set; }
        public Nullable<int> DSD_COSTCENTEROID { get; set; }
        public Nullable<int> DSD_COSTCENTERTID { get; set; }
    
        public virtual COSTCENTER COSTCENTER { get; set; }
        public virtual CURRENCY CURRENCY { get; set; }
        public virtual DIRECTSELL DIRECTSELL { get; set; }
        public virtual QUANTITY_UNIT QUANTITY_UNIT { get; set; }
        public virtual TAXDEF TAXDEF { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual PROJECT PROJECT { get; set; }
    }
}
