//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCATTACHMENTS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DOCATTACHMENTS()
        {
            this.DOCUMENTATTACH = new HashSet<DOCUMENTATTACH>();
        }
    
        public int OID { get; set; }
        public int TID { get; set; }
        public Nullable<System.DateTime> DOCA_INDATE { get; set; }
        public string DOCA_LOCALFILE { get; set; }
        public Nullable<int> DOCA_SIZE { get; set; }
        public string DOCA_NOTE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DOCUMENTATTACH> DOCUMENTATTACH { get; set; }
    }
}
