//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCDERIVELOG
    {
        public int SRCOID { get; set; }
        public int SRCTID { get; set; }
        public int DESTOID { get; set; }
        public int DESTTID { get; set; }
        public Nullable<int> DERIVEROID { get; set; }
        public Nullable<int> DERIVERTID { get; set; }
        public Nullable<System.DateTime> DERIVETIME { get; set; }
    }
}
