//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCITEMREFS
    {
        public int OID { get; set; }
        public int TID { get; set; }
        public int DIR_REFOID { get; set; }
        public int DIR_REFTID { get; set; }
        public string DIR_REFTYPE { get; set; }
        public Nullable<int> DIR_EVID { get; set; }
    }
}
