//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCPERIODSEXCEPTIONS
    {
        public int PERIODX_ID { get; set; }
        public int PERIODX_PERIOD_ID { get; set; }
        public string PERIODX_DOCUMENT { get; set; }
        public string PERIODX_CANCLOSE { get; set; }
        public string PERIODX_CANSTORNO { get; set; }
    
        public virtual DOCPERIODS DOCPERIODS { get; set; }
    }
}
