//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DPI_INVOICE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DPI_INVOICE()
        {
            this.DPI_INVOICEDETAIL = new HashSet<DPI_INVOICEDETAIL>();
            this.DPI_TAXDETAIL = new HashSet<DPI_TAXDETAIL>();
        }
    
        public int OID { get; set; }
        public int TID { get; set; }
        public Nullable<int> DPI_INVOICENUMBER { get; set; }
        public string DPI_INVOICEORIGNUMBER { get; set; }
        public string DPI_INVOICEGENNUMBER { get; set; }
        public int DPI_PAYMENTID { get; set; }
        public Nullable<int> DPI_SECTIONOID { get; set; }
        public Nullable<int> DPI_SECTIONTID { get; set; }
        public int DPI_CUSTOMEROID { get; set; }
        public int DPI_CUSTOMERTID { get; set; }
        public Nullable<int> DPI_IINVOICEOID { get; set; }
        public Nullable<int> DPI_IINVOICETID { get; set; }
        public Nullable<int> DPI_CPCOID { get; set; }
        public Nullable<int> DPI_CPCTID { get; set; }
        public Nullable<int> DPI_EMPLOYEEID { get; set; }
        public System.DateTime DPI_INVOICEDATE { get; set; }
        public System.DateTime DPI_FULFILMENT { get; set; }
        public Nullable<System.DateTime> DPI_DEADLINE { get; set; }
        public Nullable<System.DateTime> DPI_ORIGINDATE { get; set; }
        public string DPI_PAYINID { get; set; }
        public string DPI_FULFILM_PLACE { get; set; }
        public string DPI_STORNO { get; set; }
        public Nullable<System.DateTime> DPI_STORNODAT { get; set; }
        public string DPI_CURRENCY { get; set; }
        public double DPI_CURRENCY_RATE { get; set; }
        public string DPI_OK { get; set; }
        public Nullable<System.DateTime> DPI_OKDATE { get; set; }
        public Nullable<decimal> DPI_NETTO { get; set; }
        public Nullable<decimal> DPI_DISCOUNT { get; set; }
        public Nullable<decimal> DPI_TAX { get; set; }
        public Nullable<decimal> DPI_BRUTTO { get; set; }
        public Nullable<decimal> DPI_PAY_BRUTTO { get; set; }
        public decimal DPI_PRECISION { get; set; }
        public string DPI_CUSTOMERNAME { get; set; }
        public string DPI_FIRSTNAME { get; set; }
        public string DPI_LASTNAME { get; set; }
        public string DPI_COUNTRY { get; set; }
        public string DPI_ZIP { get; set; }
        public string DPI_CITY { get; set; }
        public string DPI_STREET { get; set; }
        public string DPI_BANKNAME { get; set; }
        public string DPI_ACCOUNTNUMBER { get; set; }
        public string DPI_TAXNUMBER { get; set; }
        public string DPI_EUTAXNUMBER { get; set; }
        public string DPI_NOTE { get; set; }
        public string DPI_POSTSCRIPT { get; set; }
        public Nullable<int> DPI_PARITYID { get; set; }
        public Nullable<int> DPI_NETWEIGHT { get; set; }
        public Nullable<int> DPI_GROSSWEIGHT { get; set; }
        public Nullable<int> DPI_ORIGINID { get; set; }
        public Nullable<int> DPI_NUMBEROFSKID { get; set; }
        public Nullable<System.DateTime> DPI_CONSIGNMENTDATE { get; set; }
        public Nullable<int> DPI_PAYMENTTERMID { get; set; }
        public Nullable<int> DPI_PROJECTOID { get; set; }
        public Nullable<int> DPI_PROJECTTID { get; set; }
    
        public virtual COSTCENTER COSTCENTER { get; set; }
        public virtual CURRENCY CURRENCY { get; set; }
        public virtual CUSTOMER CUSTOMER { get; set; }
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        public virtual PRODUCTORIGIN PRODUCTORIGIN { get; set; }
        public virtual PARITY PARITY { get; set; }
        public virtual PAYMENTTERM PAYMENTTERM { get; set; }
        public virtual I_INVOICE I_INVOICE { get; set; }
        public virtual PAYMENT PAYMENT { get; set; }
        public virtual PROJECT PROJECT { get; set; }
        public virtual SECTION SECTION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DPI_INVOICEDETAIL> DPI_INVOICEDETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DPI_TAXDETAIL> DPI_TAXDETAIL { get; set; }
    }
}
