//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DUN_DETAIL
    {
        public int OID { get; set; }
        public int TID { get; set; }
        public int DD_DUNOID { get; set; }
        public int DD_DUNTID { get; set; }
        public int DD_INVOICEOID { get; set; }
        public int DD_INVOICETID { get; set; }
        public System.DateTime DD_INVOICEDATE { get; set; }
        public Nullable<System.DateTime> DD_DEADLINE { get; set; }
        public int DD_DELAYINDAYS { get; set; }
        public int DD_DUNREASONID { get; set; }
        public int DD_DUNNUMBER { get; set; }
        public decimal DD_PAY_BRUTTO { get; set; }
        public string DD_CURRENCY { get; set; }
        public double DD_CURRENCY_RATE { get; set; }
        public decimal DD_BRUTTO { get; set; }
        public decimal DD_SETTLEDBRUTTO { get; set; }
        public decimal DD_REMAINEDBRUTTO { get; set; }
        public decimal DD_DELAY_INTEREST { get; set; }
        public decimal DD_DELAY_INTEREST_GROWTH { get; set; }
        public Nullable<int> DD_DETAILGROUP { get; set; }
        public string DD_CONTCODE { get; set; }
        public string DD_TACC { get; set; }
        public string DD_KACC { get; set; }
        public Nullable<int> DD_PROJECTOID { get; set; }
        public Nullable<int> DD_PROJECTTID { get; set; }
        public string DD_DESCRIPTION { get; set; }
        public Nullable<int> DD_COSTCENTEROID { get; set; }
        public Nullable<int> DD_COSTCENTERTID { get; set; }
    
        public virtual COSTCENTER COSTCENTER { get; set; }
        public virtual CURRENCY CURRENCY { get; set; }
        public virtual DUN DUN { get; set; }
        public virtual DUNREASON DUNREASON { get; set; }
        public virtual O_INVOICE O_INVOICE { get; set; }
        public virtual PROJECT PROJECT { get; set; }
    }
}
