//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DWAREHOUSE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DWAREHOUSE()
        {
            this.DWBANKGUARANTEE = new HashSet<DWBANKGUARANTEE>();
        }
    
        public int DW_ID { get; set; }
        public string DW_LICENCE { get; set; }
        public Nullable<System.DateTime> DW_LICENCEDATE { get; set; }
        public Nullable<System.DateTime> DW_REQUIREDATE { get; set; }
        public Nullable<System.DateTime> DW_LICENCEVALIDFROM { get; set; }
        public Nullable<System.DateTime> DW_LICENCEVALIDTO { get; set; }
        public string DW_OFFICENAME { get; set; }
        public string DW_OFFICECITY { get; set; }
        public string DW_OFFICEZIP { get; set; }
        public string DW_OFFICESTREET { get; set; }
        public string DW_OFFICER { get; set; }
        public string DW_RANK { get; set; }
        public string DW_FILENUMBER { get; set; }
        public int DW_PROCTYPE { get; set; }
        public int DW_WAREHOUSETYPE { get; set; }
        public Nullable<int> DW_STOCKKEEPEROID { get; set; }
        public Nullable<int> DW_STOCKKEEPERTID { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
        public virtual WAREHOUSE WAREHOUSE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DWBANKGUARANTEE> DWBANKGUARANTEE { get; set; }
    }
}
