//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DWBANKGUARANTEE
    {
        public int DWB_ID { get; set; }
        public int DWB_DWAREHOUSEID { get; set; }
        public decimal DWB_AMOUNT { get; set; }
        public int DWB_BANK { get; set; }
        public Nullable<System.DateTime> DWB_VALIDFROM { get; set; }
        public Nullable<System.DateTime> DWB_VALIDTO { get; set; }
    
        public virtual BANK BANK { get; set; }
        public virtual DWAREHOUSE DWAREHOUSE { get; set; }
    }
}
