//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE_HOLIDAY_ENTITLEMENT
    {
        public int EHE_EMPLOYEEID { get; set; }
        public int EHE_YEAR { get; set; }
        public int EHE_DAYCOUNT { get; set; }
        public int EHE_SICK_DAYCOUNT { get; set; }
        public string EHE_NOTE { get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
    }
}
