//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPLOYEE()
        {
            this.AGENTCONTRACT = new HashSet<AGENTCONTRACT>();
            this.ANALYTICTAX = new HashSet<ANALYTICTAX>();
            this.AUDIT_INVENTORY = new HashSet<AUDIT_INVENTORY>();
            this.AVISO = new HashSet<AVISO>();
            this.BANKSTAT = new HashSet<BANKSTAT>();
            this.BANKTRANSFER = new HashSet<BANKTRANSFER>();
            this.BOOKCLOSURE = new HashSet<BOOKCLOSURE>();
            this.BOOKOPENING = new HashSet<BOOKOPENING>();
            this.BOOKOUTPUT = new HashSet<BOOKOUTPUT>();
            this.BOOKPOST = new HashSet<BOOKPOST>();
            this.BUYUP = new HashSet<BUYUP>();
            this.CAMPAIGN = new HashSet<CAMPAIGN>();
            this.CASHDESK_CLOSE = new HashSet<CASHDESK_CLOSE>();
            this.CASHFLOWDEF = new HashSet<CASHFLOWDEF>();
            this.CASHFLOWSTORAGE = new HashSet<CASHFLOWSTORAGE>();
            this.COMPENSATION = new HashSet<COMPENSATION>();
            this.CONSIGNMENT_IN = new HashSet<CONSIGNMENT_IN>();
            this.CONSIGNMENT_OUT = new HashSet<CONSIGNMENT_OUT>();
            this.CONSIGNMENTREPORT = new HashSet<CONSIGNMENTREPORT>();
            this.CREATESERIAL = new HashSet<CREATESERIAL>();
            this.CUST_PROJ_EVENTBOOK = new HashSet<CUST_PROJ_EVENTBOOK>();
            this.CUSTOMDOC = new HashSet<CUSTOMDOC>();
            this.CUSTOMDOC1 = new HashSet<CUSTOMDOC>();
            this.CUSTOMREPORT = new HashSet<CUSTOMREPORT>();
            this.DELIVERYCONTRACT = new HashSet<DELIVERYCONTRACT>();
            this.DELIVERYOFFER = new HashSet<DELIVERYOFFER>();
            this.DELIVERYORDER = new HashSet<DELIVERYORDER>();
            this.DELIVERYORDERMOD = new HashSet<DELIVERYORDERMOD>();
            this.DIRECTBUY = new HashSet<DIRECTBUY>();
            this.DIRECTSELL = new HashSet<DIRECTSELL>();
            this.DPI_INVOICE = new HashSet<DPI_INVOICE>();
            this.DPO_INVOICE = new HashSet<DPO_INVOICE>();
            this.DUN = new HashSet<DUN>();
            this.EMPLOYEE_ASSIGNMENT = new HashSet<EMPLOYEE_ASSIGNMENT>();
            this.EMPLOYEE_DOCUMENT = new HashSet<EMPLOYEE_DOCUMENT>();
            this.EMPLOYEE_EXPENDITURE = new HashSet<EMPLOYEE_EXPENDITURE>();
            this.EMPLOYEE_HOLIDAY_ENTITLEMENT = new HashSet<EMPLOYEE_HOLIDAY_ENTITLEMENT>();
            this.EMPLOYEESCHILDREN = new HashSet<EMPLOYEESCHILDREN>();
            this.EMPLOYEESQUALIFICATIONS = new HashSet<EMPLOYEESQUALIFICATIONS>();
            this.EMPLOYEESWORKPLACES = new HashSet<EMPLOYEESWORKPLACES>();
            this.GADFILE = new HashSet<GADFILE>();
            this.GADFILE1 = new HashSet<GADFILE>();
            this.GADNEWGAD = new HashSet<GADNEWGAD>();
            this.GENPROD = new HashSet<GENPROD>();
            this.GENPROD_PHASE = new HashSet<GENPROD_PHASE>();
            this.GOVANLINEPASS = new HashSet<GOVANLINEPASS>();
            this.INVENTORY_GAP = new HashSet<INVENTORY_GAP>();
            this.JUSTVANLINEPASS = new HashSet<JUSTVANLINEPASS>();
            this.JUSTWAYBILL = new HashSet<JUSTWAYBILL>();
            this.MOVESTOCK_IN = new HashSet<MOVESTOCK_IN>();
            this.MOVESTOCK_OUT = new HashSet<MOVESTOCK_OUT>();
            this.PC_MANUCLOSE = new HashSet<PC_MANUCLOSE>();
            this.PC_MANUFACTURELOG = new HashSet<PC_MANUFACTURELOG>();
            this.PC_MANUMOVE_IN = new HashSet<PC_MANUMOVE_IN>();
            this.PC_MANUMOVE_OUT = new HashSet<PC_MANUMOVE_OUT>();
            this.PC_MANUSEND = new HashSet<PC_MANUSEND>();
            this.PC_OPERATIONSHEET = new HashSet<PC_OPERATIONSHEET>();
            this.PC_OPERATIVES = new HashSet<PC_OPERATIVES>();
            this.PC_PLAN = new HashSet<PC_PLAN>();
            this.PC_QCMEASURESHEETS = new HashSet<PC_QCMEASURESHEETS>();
            this.PC_QCREPORT = new HashSet<PC_QCREPORT>();
            this.PR_BATCHES = new HashSet<PR_BATCHES>();
            this.PROD_STIN = new HashSet<PROD_STIN>();
            this.PROD_STOUT = new HashSet<PROD_STOUT>();
            this.RECEIPT_MACHINE = new HashSet<RECEIPT_MACHINE>();
            this.RETURNED = new HashSet<RETURNED>();
            this.RETURNEDCHANGE = new HashSet<RETURNEDCHANGE>();
            this.SERVICESHEET = new HashSet<SERVICESHEET>();
            this.STOCKMOD = new HashSet<STOCKMOD>();
            this.SUPPLYOFFER = new HashSet<SUPPLYOFFER>();
            this.TAGCHANGE = new HashSet<TAGCHANGE>();
            this.TOOL = new HashSet<TOOL>();
            this.TOOLEMPLOYEE = new HashSet<TOOLEMPLOYEE>();
            this.TOOLHISTORY = new HashSet<TOOLHISTORY>();
            this.TOOLMAKECONTRACT = new HashSet<TOOLMAKECONTRACT>();
            this.TOOLSERVICE = new HashSet<TOOLSERVICE>();
            this.TOOLTRAVELLING = new HashSet<TOOLTRAVELLING>();
            this.TOOLTRAVELS_DETAIL = new HashSet<TOOLTRAVELS_DETAIL>();
            this.VANLINEPASS = new HashSet<VANLINEPASS>();
            this.WAYBILL = new HashSet<WAYBILL>();
            this.GADFILEMOD_POST = new HashSet<GADFILEMOD_POST>();
            this.I_ACCOUNTCOMPENSATION = new HashSet<I_ACCOUNTCOMPENSATION>();
            this.I_CASHDOC = new HashSet<I_CASHDOC>();
            this.I_CASHDOC1 = new HashSet<I_CASHDOC>();
            this.I_CASHDOC2 = new HashSet<I_CASHDOC>();
            this.I_CASHDOC3 = new HashSet<I_CASHDOC>();
            this.I_CASHDOC4 = new HashSet<I_CASHDOC>();
            this.I_CASHDOC5 = new HashSet<I_CASHDOC>();
            this.I_CASHDOC6 = new HashSet<I_CASHDOC>();
            this.I_INVOICE = new HashSet<I_INVOICE>();
            this.I_SETTLE = new HashSet<I_SETTLE>();
            this.INTRASTAT = new HashSet<INTRASTAT>();
            this.INVENTORY = new HashSet<INVENTORY>();
            this.JUNK = new HashSet<JUNK>();
            this.KOMISSIO = new HashSet<KOMISSIO>();
            this.KOMISSIO1 = new HashSet<KOMISSIO>();
            this.KOMISSIOMOD = new HashSet<KOMISSIOMOD>();
            this.LEASEASSET_EVENT = new HashSet<LEASEASSET_EVENT>();
            this.LEASEASSET = new HashSet<LEASEASSET>();
            this.LEASECONTRACT = new HashSet<LEASECONTRACT>();
            this.LEASECONTRACTBACK = new HashSet<LEASECONTRACTBACK>();
            this.LEASECONTRACTMOD = new HashSet<LEASECONTRACTMOD>();
            this.LOADDIVISION = new HashSet<LOADDIVISION>();
            this.MARKETREGISTER = new HashSet<MARKETREGISTER>();
            this.MARKETREGISTER1 = new HashSet<MARKETREGISTER>();
            this.MARKETREGISTER2 = new HashSet<MARKETREGISTER>();
            this.MARKETREGISTER3 = new HashSet<MARKETREGISTER>();
            this.MEO = new HashSet<MEO>();
            this.MFDEFS = new HashSet<MFDEFS>();
            this.MFDEFS1 = new HashSet<MFDEFS>();
            this.MIXING = new HashSet<MIXING>();
            this.MOVESTOCK_OUT1 = new HashSet<MOVESTOCK_OUT>();
            this.NOTIFIER = new HashSet<NOTIFIER>();
            this.O_ACCOUNTCOMPENSATION = new HashSet<O_ACCOUNTCOMPENSATION>();
            this.O_CASHDOC = new HashSet<O_CASHDOC>();
            this.O_CASHDOC1 = new HashSet<O_CASHDOC>();
            this.O_CASHDOC2 = new HashSet<O_CASHDOC>();
            this.O_CASHDOC3 = new HashSet<O_CASHDOC>();
            this.O_CASHDOC4 = new HashSet<O_CASHDOC>();
            this.O_CASHDOC5 = new HashSet<O_CASHDOC>();
            this.O_CASHDOC6 = new HashSet<O_CASHDOC>();
            this.O_INVOICE = new HashSet<O_INVOICE>();
            this.O_SETTLE = new HashSet<O_SETTLE>();
            this.OPTIONEDMOD = new HashSet<OPTIONEDMOD>();
            this.PACKING = new HashSet<PACKING>();
            this.PACKING1 = new HashSet<PACKING>();
            this.PC_COST = new HashSet<PC_COST>();
            this.PC_MANOPERINFO = new HashSet<PC_MANOPERINFO>();
            this.PC_MANUFACTURE = new HashSet<PC_MANUFACTURE>();
            this.PRODBAR = new HashSet<PRODBAR>();
            this.PRODBAR1 = new HashSet<PRODBAR>();
            this.PRODDELIVERY = new HashSet<PRODDELIVERY>();
            this.PRODEMPLOYEE = new HashSet<PRODEMPLOYEE>();
            this.PRODREQUEST = new HashSet<PRODREQUEST>();
            this.PROD_STIN1 = new HashSet<PROD_STIN>();
            this.PROD_STOUT1 = new HashSet<PROD_STOUT>();
            this.PRODUCTION = new HashSet<PRODUCTION>();
            this.PRODUCTION1 = new HashSet<PRODUCTION>();
            this.PRODUCTION2 = new HashSet<PRODUCTION>();
            this.PRODUCTION3 = new HashSet<PRODUCTION>();
            this.PRODUCTION4 = new HashSet<PRODUCTION>();
            this.PRODUCTION5 = new HashSet<PRODUCTION>();
            this.PRODUCTION_EVENT = new HashSet<PRODUCTION_EVENT>();
            this.RECEIPT_CLOSE = new HashSet<RECEIPT_CLOSE>();
            this.RECEIPT = new HashSet<RECEIPT>();
            this.RECORD = new HashSet<RECORD>();
            this.RECORD1 = new HashSet<RECORD>();
            this.RECORD_SIGNERS = new HashSet<RECORD_SIGNERS>();
            this.REPAIR = new HashSet<REPAIR>();
            this.REPAIRBACK = new HashSet<REPAIRBACK>();
            this.RETREIVEANAL = new HashSet<RETREIVEANAL>();
            this.RETREIVEANAL1 = new HashSet<RETREIVEANAL>();
            this.RETREIVECHANGE = new HashSet<RETREIVECHANGE>();
            this.SCALINGCONFIRMATION = new HashSet<SCALINGCONFIRMATION>();
            this.SCALINGCONFIRMATION1 = new HashSet<SCALINGCONFIRMATION>();
            this.SCALINGCONFIRMATION2 = new HashSet<SCALINGCONFIRMATION>();
            this.SERVICEASSET_EVENT = new HashSet<SERVICEASSET_EVENT>();
            this.SERVICEASSET_RESPONSIBLE = new HashSet<SERVICEASSET_RESPONSIBLE>();
            this.SERVICECONTRACT = new HashSet<SERVICECONTRACT>();
            this.SERVICECONTRACT1 = new HashSet<SERVICECONTRACT>();
            this.SERVICESHEET_FIELDWORK = new HashSet<SERVICESHEET_FIELDWORK>();
            this.SERVICESHEET_FIELDWORK_EMPLOYEE = new HashSet<SERVICESHEET_FIELDWORK_EMPLOYEE>();
            this.SERVICESHEET_OPERATION = new HashSet<SERVICESHEET_OPERATION>();
            this.SERVICESHEET1 = new HashSet<SERVICESHEET>();
            this.STOCKKEEPERREPORT = new HashSet<STOCKKEEPERREPORT>();
            this.STORE_IN = new HashSet<STORE_IN>();
            this.STORE_IN1 = new HashSet<STORE_IN>();
            this.STORE_OUT = new HashSet<STORE_OUT>();
            this.STORE_OUT1 = new HashSet<STORE_OUT>();
            this.SUPPLYORDER = new HashSet<SUPPLYORDER>();
            this.SUPPLYORDERMOD = new HashSet<SUPPLYORDERMOD>();
            this.THEORETICAL_INVENTORY = new HashSet<THEORETICAL_INVENTORY>();
            this.TOOL1 = new HashSet<TOOL>();
            this.TOOLBENCH = new HashSet<TOOLBENCH>();
            this.TOOLINPUT = new HashSet<TOOLINPUT>();
            this.TOOLSERVICE1 = new HashSet<TOOLSERVICE>();
            this.TOOLTRAVELLING1 = new HashSet<TOOLTRAVELLING>();
            this.TOOLTRAVELS = new HashSet<TOOLTRAVELS>();
            this.PRODUCT_EVENTBOOK = new HashSet<PRODUCT_EVENTBOOK>();
            this.RECORD_EVENTBOOK = new HashSet<RECORD_EVENTBOOK>();
            this.TOOL_EVENTBOOK = new HashSet<TOOL_EVENTBOOK>();
            this.UNONTHEWAY = new HashSet<UNONTHEWAY>();
            this.UNOPTIONED = new HashSet<UNOPTIONED>();
            this.VEHICLE_RESPONSIBLE = new HashSet<VEHICLE_RESPONSIBLE>();
            this.VEHICLE_USER = new HashSet<VEHICLE_USER>();
            this.WBH_WAREBASE_AGENT = new HashSet<WBH_WAREBASE_AGENT>();
            this.WBH_WAREBASE_DIVISION = new HashSet<WBH_WAREBASE_DIVISION>();
            this.EMPLOYEEGROUPNAME = new HashSet<EMPLOYEEGROUPNAME>();
        }
    
        public int EMPLOYEEID { get; set; }
        public string FULLNAME { get; set; }
        public string EM_IDENTIFIER { get; set; }
        public int SECTIONOID { get; set; }
        public int SECTIONTID { get; set; }
        public string FIRSTNAME { get; set; }
        public string LASTNAME { get; set; }
        public string ZIP { get; set; }
        public string COUNTRY { get; set; }
        public string CITY { get; set; }
        public string STREET { get; set; }
        public string PHONEHOME { get; set; }
        public string PHONEWORK { get; set; }
        public string CALLER { get; set; }
        public string FAX { get; set; }
        public string EMAIL { get; set; }
        public Nullable<System.DateTime> STARTDATE { get; set; }
        public Nullable<System.DateTime> ENDDATE { get; set; }
        public string PICTUREGUID { get; set; }
        public string SIGNATUREGUID { get; set; }
        public string EM_POLLING { get; set; }
        public string EM_NICKNAME { get; set; }
        public Nullable<System.DateTime> EM_BIRTHDATE { get; set; }
        public string EM_ROOM { get; set; }
        public Nullable<int> EM_TITLEID { get; set; }
        public Nullable<int> EM_PFFICTIVESTORAGEOID { get; set; }
        public Nullable<int> EM_PFFICTIVESTORAGETID { get; set; }
        public string EM_BIRTHPLACE { get; set; }
        public string EM_MOTHERNAME { get; set; }
        public Nullable<int> EM_LANGUAGEID { get; set; }
        public Nullable<int> EM_FORENAMEID { get; set; }
        public string EM_DOCUMENTNUMBER { get; set; }
        public string EM_OWNNUMBER { get; set; }
        public string EM_SOCSECNUMBER { get; set; }
        public string EM_GENDER { get; set; }
        public string EM_STATE { get; set; }
        public string EM_CITIZENSHIP { get; set; }
        public string EM_DISPOSITION { get; set; }
        public string EM_MAIDENNAME { get; set; }
        public string EM_NOTE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AGENTCONTRACT> AGENTCONTRACT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ANALYTICTAX> ANALYTICTAX { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AUDIT_INVENTORY> AUDIT_INVENTORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AVISO> AVISO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BANKSTAT> BANKSTAT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BANKTRANSFER> BANKTRANSFER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOOKCLOSURE> BOOKCLOSURE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOOKOPENING> BOOKOPENING { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOOKOUTPUT> BOOKOUTPUT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOOKPOST> BOOKPOST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BUYUP> BUYUP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAMPAIGN> CAMPAIGN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CASHDESK_CLOSE> CASHDESK_CLOSE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CASHFLOWDEF> CASHFLOWDEF { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CASHFLOWSTORAGE> CASHFLOWSTORAGE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMPENSATION> COMPENSATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONSIGNMENT_IN> CONSIGNMENT_IN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONSIGNMENT_OUT> CONSIGNMENT_OUT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONSIGNMENTREPORT> CONSIGNMENTREPORT { get; set; }
        public virtual COUNTRY COUNTRY1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CREATESERIAL> CREATESERIAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUST_PROJ_EVENTBOOK> CUST_PROJ_EVENTBOOK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUSTOMDOC> CUSTOMDOC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUSTOMDOC> CUSTOMDOC1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUSTOMREPORT> CUSTOMREPORT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DELIVERYCONTRACT> DELIVERYCONTRACT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DELIVERYOFFER> DELIVERYOFFER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DELIVERYORDER> DELIVERYORDER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DELIVERYORDERMOD> DELIVERYORDERMOD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DIRECTBUY> DIRECTBUY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DIRECTSELL> DIRECTSELL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DPI_INVOICE> DPI_INVOICE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DPO_INVOICE> DPO_INVOICE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DUN> DUN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPLOYEE_ASSIGNMENT> EMPLOYEE_ASSIGNMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPLOYEE_DOCUMENT> EMPLOYEE_DOCUMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPLOYEE_EXPENDITURE> EMPLOYEE_EXPENDITURE { get; set; }
        public virtual FORENAME FORENAME { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPLOYEE_HOLIDAY_ENTITLEMENT> EMPLOYEE_HOLIDAY_ENTITLEMENT { get; set; }
        public virtual LANGUAGE LANGUAGE { get; set; }
        public virtual SECTION SECTION { get; set; }
        public virtual PFFICTIVESTORAGE PFFICTIVESTORAGE { get; set; }
        public virtual TITLE TITLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPLOYEESCHILDREN> EMPLOYEESCHILDREN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPLOYEESQUALIFICATIONS> EMPLOYEESQUALIFICATIONS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPLOYEESWORKPLACES> EMPLOYEESWORKPLACES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GADFILE> GADFILE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GADFILE> GADFILE1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GADNEWGAD> GADNEWGAD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GENPROD> GENPROD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GENPROD_PHASE> GENPROD_PHASE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GOVANLINEPASS> GOVANLINEPASS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INVENTORY_GAP> INVENTORY_GAP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JUSTVANLINEPASS> JUSTVANLINEPASS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JUSTWAYBILL> JUSTWAYBILL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MOVESTOCK_IN> MOVESTOCK_IN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MOVESTOCK_OUT> MOVESTOCK_OUT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PC_MANUCLOSE> PC_MANUCLOSE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PC_MANUFACTURELOG> PC_MANUFACTURELOG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PC_MANUMOVE_IN> PC_MANUMOVE_IN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PC_MANUMOVE_OUT> PC_MANUMOVE_OUT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PC_MANUSEND> PC_MANUSEND { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PC_OPERATIONSHEET> PC_OPERATIONSHEET { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PC_OPERATIVES> PC_OPERATIVES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PC_PLAN> PC_PLAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PC_QCMEASURESHEETS> PC_QCMEASURESHEETS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PC_QCREPORT> PC_QCREPORT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PR_BATCHES> PR_BATCHES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROD_STIN> PROD_STIN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROD_STOUT> PROD_STOUT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RECEIPT_MACHINE> RECEIPT_MACHINE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RETURNED> RETURNED { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RETURNEDCHANGE> RETURNEDCHANGE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SERVICESHEET> SERVICESHEET { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STOCKMOD> STOCKMOD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUPPLYOFFER> SUPPLYOFFER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAGCHANGE> TAGCHANGE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TOOL> TOOL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TOOLEMPLOYEE> TOOLEMPLOYEE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TOOLHISTORY> TOOLHISTORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TOOLMAKECONTRACT> TOOLMAKECONTRACT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TOOLSERVICE> TOOLSERVICE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TOOLTRAVELLING> TOOLTRAVELLING { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TOOLTRAVELS_DETAIL> TOOLTRAVELS_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VANLINEPASS> VANLINEPASS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WAYBILL> WAYBILL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GADFILEMOD_POST> GADFILEMOD_POST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_ACCOUNTCOMPENSATION> I_ACCOUNTCOMPENSATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_CASHDOC> I_CASHDOC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_CASHDOC> I_CASHDOC1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_CASHDOC> I_CASHDOC2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_CASHDOC> I_CASHDOC3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_CASHDOC> I_CASHDOC4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_CASHDOC> I_CASHDOC5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_CASHDOC> I_CASHDOC6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_INVOICE> I_INVOICE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_SETTLE> I_SETTLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INTRASTAT> INTRASTAT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INVENTORY> INVENTORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JUNK> JUNK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KOMISSIO> KOMISSIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KOMISSIO> KOMISSIO1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KOMISSIOMOD> KOMISSIOMOD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LEASEASSET_EVENT> LEASEASSET_EVENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LEASEASSET> LEASEASSET { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LEASECONTRACT> LEASECONTRACT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LEASECONTRACTBACK> LEASECONTRACTBACK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LEASECONTRACTMOD> LEASECONTRACTMOD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOADDIVISION> LOADDIVISION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MARKETREGISTER> MARKETREGISTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MARKETREGISTER> MARKETREGISTER1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MARKETREGISTER> MARKETREGISTER2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MARKETREGISTER> MARKETREGISTER3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MEO> MEO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MFDEFS> MFDEFS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MFDEFS> MFDEFS1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MIXING> MIXING { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MOVESTOCK_OUT> MOVESTOCK_OUT1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NOTIFIER> NOTIFIER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<O_ACCOUNTCOMPENSATION> O_ACCOUNTCOMPENSATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<O_CASHDOC> O_CASHDOC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<O_CASHDOC> O_CASHDOC1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<O_CASHDOC> O_CASHDOC2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<O_CASHDOC> O_CASHDOC3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<O_CASHDOC> O_CASHDOC4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<O_CASHDOC> O_CASHDOC5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<O_CASHDOC> O_CASHDOC6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<O_INVOICE> O_INVOICE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<O_SETTLE> O_SETTLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OPTIONEDMOD> OPTIONEDMOD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PACKING> PACKING { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PACKING> PACKING1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PC_COST> PC_COST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PC_MANOPERINFO> PC_MANOPERINFO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PC_MANUFACTURE> PC_MANUFACTURE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODBAR> PRODBAR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODBAR> PRODBAR1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODDELIVERY> PRODDELIVERY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODEMPLOYEE> PRODEMPLOYEE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODREQUEST> PRODREQUEST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROD_STIN> PROD_STIN1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROD_STOUT> PROD_STOUT1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCTION> PRODUCTION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCTION> PRODUCTION1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCTION> PRODUCTION2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCTION> PRODUCTION3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCTION> PRODUCTION4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCTION> PRODUCTION5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCTION_EVENT> PRODUCTION_EVENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RECEIPT_CLOSE> RECEIPT_CLOSE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RECEIPT> RECEIPT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RECORD> RECORD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RECORD> RECORD1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RECORD_SIGNERS> RECORD_SIGNERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REPAIR> REPAIR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REPAIRBACK> REPAIRBACK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RETREIVEANAL> RETREIVEANAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RETREIVEANAL> RETREIVEANAL1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RETREIVECHANGE> RETREIVECHANGE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SCALINGCONFIRMATION> SCALINGCONFIRMATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SCALINGCONFIRMATION> SCALINGCONFIRMATION1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SCALINGCONFIRMATION> SCALINGCONFIRMATION2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SERVICEASSET_EVENT> SERVICEASSET_EVENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SERVICEASSET_RESPONSIBLE> SERVICEASSET_RESPONSIBLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SERVICECONTRACT> SERVICECONTRACT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SERVICECONTRACT> SERVICECONTRACT1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SERVICESHEET_FIELDWORK> SERVICESHEET_FIELDWORK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SERVICESHEET_FIELDWORK_EMPLOYEE> SERVICESHEET_FIELDWORK_EMPLOYEE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SERVICESHEET_OPERATION> SERVICESHEET_OPERATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SERVICESHEET> SERVICESHEET1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STOCKKEEPERREPORT> STOCKKEEPERREPORT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STORE_IN> STORE_IN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STORE_IN> STORE_IN1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STORE_OUT> STORE_OUT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STORE_OUT> STORE_OUT1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUPPLYORDER> SUPPLYORDER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUPPLYORDERMOD> SUPPLYORDERMOD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THEORETICAL_INVENTORY> THEORETICAL_INVENTORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TOOL> TOOL1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TOOLBENCH> TOOLBENCH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TOOLINPUT> TOOLINPUT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TOOLSERVICE> TOOLSERVICE1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TOOLTRAVELLING> TOOLTRAVELLING1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TOOLTRAVELS> TOOLTRAVELS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCT_EVENTBOOK> PRODUCT_EVENTBOOK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RECORD_EVENTBOOK> RECORD_EVENTBOOK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TOOL_EVENTBOOK> TOOL_EVENTBOOK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UNONTHEWAY> UNONTHEWAY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UNOPTIONED> UNOPTIONED { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VEHICLE_RESPONSIBLE> VEHICLE_RESPONSIBLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VEHICLE_USER> VEHICLE_USER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WBH_WAREBASE_AGENT> WBH_WAREBASE_AGENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WBH_WAREBASE_DIVISION> WBH_WAREBASE_DIVISION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPLOYEEGROUPNAME> EMPLOYEEGROUPNAME { get; set; }
    }
}
