//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE_EXPENDITURE_DETAIL
    {
        public int OID { get; set; }
        public int TID { get; set; }
        public int EEXD_EMPLOYEE_EXPENDITUREOID { get; set; }
        public int EEXD_EMPLOYEE_EXPENDITURETID { get; set; }
        public int EEXD_EXPENDITURETYPEID { get; set; }
        public double EEXD_AMOUNT { get; set; }
        public string EEXD_CURRENCY { get; set; }
        public string EEXD_NOTE { get; set; }
    
        public virtual CURRENCY CURRENCY { get; set; }
        public virtual EMPLOYEE_EXPENDITURE EMPLOYEE_EXPENDITURE { get; set; }
        public virtual EXPENDITURETYPE EXPENDITURETYPE { get; set; }
    }
}
