//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENTITYPICTURES
    {
        public int EP_OID { get; set; }
        public int EP_TID { get; set; }
        public int EP_AID { get; set; }
        public string EP_ID { get; set; }
        public string EP_ENTITY { get; set; }
        public string EP_NOTE { get; set; }
        public string EP_PICTUREMODE { get; set; }
        public Nullable<int> EP_PAGENO { get; set; }
    }
}
