//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVENTTYPE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EVENTTYPE()
        {
            this.CUST_PROJ_EVENTBOOK = new HashSet<CUST_PROJ_EVENTBOOK>();
            this.PRODUCT_EVENTBOOK = new HashSet<PRODUCT_EVENTBOOK>();
            this.RECORD_EVENTBOOK = new HashSet<RECORD_EVENTBOOK>();
            this.TOOL_EVENTBOOK = new HashSet<TOOL_EVENTBOOK>();
            this.VEHICLE_EVENT = new HashSet<VEHICLE_EVENT>();
        }
    
        public int ET_ID { get; set; }
        public string ET_NAME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUST_PROJ_EVENTBOOK> CUST_PROJ_EVENTBOOK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCT_EVENTBOOK> PRODUCT_EVENTBOOK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RECORD_EVENTBOOK> RECORD_EVENTBOOK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TOOL_EVENTBOOK> TOOL_EVENTBOOK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VEHICLE_EVENT> VEHICLE_EVENT { get; set; }
    }
}
