//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXPENDITURETYPE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EXPENDITURETYPE()
        {
            this.EMPLOYEE_EXPENDITURE_DETAIL = new HashSet<EMPLOYEE_EXPENDITURE_DETAIL>();
        }
    
        public int ET_ID { get; set; }
        public string ET_NAME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPLOYEE_EXPENDITURE_DETAIL> EMPLOYEE_EXPENDITURE_DETAIL { get; set; }
    }
}
