//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class GADFILE_DETAIL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GADFILE_DETAIL()
        {
            this.GADFILE_DETAIL_POSTS = new HashSet<GADFILE_DETAIL_POSTS>();
            this.GADFILE_SHADOW = new HashSet<GADFILE_SHADOW>();
        }
    
        public int OID { get; set; }
        public int TID { get; set; }
        public int GFD_GADFILEOID { get; set; }
        public int GFD_GADFILETID { get; set; }
        public System.DateTime GFD_MODAT { get; set; }
        public Nullable<int> GFD_MODDOCOID { get; set; }
        public Nullable<int> GFD_MODDOCTID { get; set; }
        public string GFD_NOTE { get; set; }
        public Nullable<decimal> GFD_BRINCREMENT { get; set; }
        public Nullable<decimal> GFD_BRDECREMENT { get; set; }
        public Nullable<decimal> GFD_BRUTTO { get; set; }
        public Nullable<decimal> GFD_NEINCREMENT { get; set; }
        public Nullable<decimal> GFD_NEDECREMENT { get; set; }
        public Nullable<decimal> GFD_NETTO { get; set; }
        public string GFD_NPDECREMENT { get; set; }
        public Nullable<decimal> GFD_CORRECTION { get; set; }
        public Nullable<decimal> GFD_COINCREMENT { get; set; }
        public Nullable<decimal> GFD_CODECREMENT { get; set; }
        public Nullable<decimal> GFD_CUMNPVALUEDECR { get; set; }
        public string GFD_STATE { get; set; }
        public Nullable<System.DateTime> GFD_ACTIVATED { get; set; }
        public Nullable<decimal> GFD_ACTIVATEDVALUE { get; set; }
        public Nullable<System.DateTime> GFD_VALUEDATE { get; set; }
        public string GFD_TAXING { get; set; }
        public string GFD_METHOD { get; set; }
        public string GFD_RECALCULATING { get; set; }
        public Nullable<double> GFD_KEY { get; set; }
        public Nullable<double> GFD_HELPERKEY { get; set; }
    
        public virtual GADFILE GADFILE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GADFILE_DETAIL_POSTS> GADFILE_DETAIL_POSTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GADFILE_SHADOW> GADFILE_SHADOW { get; set; }
    }
}
