//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class GADFILEMOD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GADFILEMOD()
        {
            this.GADFILEMOD_POST = new HashSet<GADFILEMOD_POST>();
            this.PC_PROTOOLSERVICING_DETAIL = new HashSet<PC_PROTOOLSERVICING_DETAIL>();
        }
    
        public int OID { get; set; }
        public int TID { get; set; }
        public string GFM_DOCUNUMBER { get; set; }
        public Nullable<int> GFM_GADFILEOID { get; set; }
        public Nullable<int> GFM_GADFILETID { get; set; }
        public string GFM_EVENT { get; set; }
        public string GFM_NOTE { get; set; }
        public Nullable<decimal> GFM_VALUE { get; set; }
        public Nullable<decimal> GFM_MODIFVALUE { get; set; }
        public string GFM_DECRMETHOD { get; set; }
        public Nullable<double> GFM_KEY { get; set; }
        public Nullable<double> GFM_HELPERKEY { get; set; }
        public string GFM_FILECONSTRAINT { get; set; }
        public Nullable<int> GFM_EMPLOYEEID { get; set; }
        public string GFM_OK { get; set; }
        public Nullable<System.DateTime> GFM_OKDATE { get; set; }
        public string GFM_STORNO { get; set; }
        public Nullable<System.DateTime> GFM_DATE { get; set; }
        public Nullable<System.DateTime> GFM_REFDATE { get; set; }
        public string GFM_CONTCODE { get; set; }
    
        public virtual GADFILE GADFILE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GADFILEMOD_POST> GADFILEMOD_POST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PC_PROTOOLSERVICING_DETAIL> PC_PROTOOLSERVICING_DETAIL { get; set; }
    }
}
