//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class GADNEWGAD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GADNEWGAD()
        {
            this.GADNEWGAD_DETAIL = new HashSet<GADNEWGAD_DETAIL>();
            this.GADNEWGAD_FROM = new HashSet<GADNEWGAD_FROM>();
            this.GADNEWGAD_INVEST = new HashSet<GADNEWGAD_INVEST>();
            this.GADNEWGAD_SERIAL = new HashSet<GADNEWGAD_SERIAL>();
        }
    
        public int OID { get; set; }
        public int TID { get; set; }
        public string GNG_WHY { get; set; }
        public string GNG_DOCUNUMBER { get; set; }
        public System.DateTime GNG_DOCUDATE { get; set; }
        public Nullable<int> GNG_EMPLOYEEID { get; set; }
        public Nullable<int> GNG_SECTIONOID { get; set; }
        public Nullable<int> GNG_SECTIONTID { get; set; }
        public Nullable<decimal> GNG_FULLCOST { get; set; }
        public Nullable<decimal> GNG_INVESTCOST { get; set; }
        public Nullable<decimal> GNG_BUILTINGAD { get; set; }
        public Nullable<decimal> GNG_DIFFERENCE { get; set; }
        public Nullable<int> GNG_WAREHOUSEID { get; set; }
        public string GNG_DIRECTLYFROMBUY { get; set; }
        public string GNG_OK { get; set; }
        public Nullable<System.DateTime> GNG_OKDATE { get; set; }
        public string GNG_STORNO { get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GADNEWGAD_DETAIL> GADNEWGAD_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GADNEWGAD_FROM> GADNEWGAD_FROM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GADNEWGAD_INVEST> GADNEWGAD_INVEST { get; set; }
        public virtual SECTION SECTION { get; set; }
        public virtual WAREHOUSE WAREHOUSE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GADNEWGAD_SERIAL> GADNEWGAD_SERIAL { get; set; }
    }
}
