//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class GENPROD_SELECTION
    {
        public int GPSL_PRODRESOID { get; set; }
        public int GPSL_PRODRESTID { get; set; }
        public int GPSL_GENPRODOID { get; set; }
        public int GPSL_GENPRODTID { get; set; }
        public int GPSL_PHASEOID { get; set; }
        public int GPSL_PHASETID { get; set; }
        public int GPSL_GPPHOID { get; set; }
        public int GPSL_GPPHTID { get; set; }
        public int GPSL_PRODUCTOID { get; set; }
        public int GPSL_PRODUCTTID { get; set; }
        public string GPSL_METHOD { get; set; }
        public double GPSL_NEEDQUANTITY { get; set; }
        public Nullable<double> GPSL_REALLYUSED { get; set; }
        public double GPSL_AVAILQUANTITY { get; set; }
        public Nullable<int> GPSL_GROUP { get; set; }
        public string GPSL_SELECTED { get; set; }
        public string GPSL_CONDITION { get; set; }
        public string GPSL_SELECTGROUP { get; set; }
        public string GPSL_COMMENT { get; set; }
    
        public virtual GENPROD GENPROD { get; set; }
        public virtual GENPROD_PHASE GENPROD_PHASE { get; set; }
        public virtual PRDPHASE PRDPHASE { get; set; }
        public virtual PRODRESOURCE PRODRESOURCE { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
