//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class GENPROD_PHASE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GENPROD_PHASE()
        {
            this.GENPROD_PRODUCED = new HashSet<GENPROD_PRODUCED>();
            this.GENPROD_SELECTION = new HashSet<GENPROD_SELECTION>();
        }
    
        public int OID { get; set; }
        public int TID { get; set; }
        public int GPP_GENPRODOID { get; set; }
        public int GPP_GENPRODTID { get; set; }
        public string GPP_STATE { get; set; }
        public int GPP_SEQUENCE { get; set; }
        public int GPP_PHASEOID { get; set; }
        public int GPP_PHASETID { get; set; }
        public double GPP_MULTIPLIER { get; set; }
        public Nullable<int> GPP_EMPLOYEEID { get; set; }
        public string GPP_COMMENT { get; set; }
        public string GPP_TACC { get; set; }
        public string GPP_KACC { get; set; }
        public Nullable<int> GPP_PROJECTOID { get; set; }
        public Nullable<int> GPP_PROJECTTID { get; set; }
        public Nullable<int> GPP_COSTCENTEROID { get; set; }
        public Nullable<int> GPP_COSTCENTERTID { get; set; }
    
        public virtual COSTCENTER COSTCENTER { get; set; }
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        public virtual GENPROD GENPROD { get; set; }
        public virtual PRDPHASE PRDPHASE { get; set; }
        public virtual PROJECT PROJECT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GENPROD_PRODUCED> GENPROD_PRODUCED { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GENPROD_SELECTION> GENPROD_SELECTION { get; set; }
    }
}
