//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class GR_GROUPINFO
    {
        public string GRI_GNAME { get; set; }
        public string GRI_GROUP { get; set; }
        public int GRI_ID { get; set; }
        public string GRI_NOTE { get; set; }
        public Nullable<double> GRI_VALUE { get; set; }
        public int OID { get; set; }
        public int TID { get; set; }
    }
}
