//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOLIDAYS
    {
        public System.DateTime H_HOLIDAYDATE { get; set; }
        public string H_HOLIDAYNAME { get; set; }
        public string H_ISHOLIDAY { get; set; }
        public Nullable<int> H_WORKINGDAY { get; set; }
    }
}
