//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class I_ACCOUNTCOMPENSATION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public I_ACCOUNTCOMPENSATION()
        {
            this.I_ACCOUNTCOMPENSATION_DETAIL = new HashSet<I_ACCOUNTCOMPENSATION_DETAIL>();
        }
    
        public int OID { get; set; }
        public int TID { get; set; }
        public Nullable<int> IC_DOCUOWNNUMBER { get; set; }
        public string IC_DOCUNUMBER { get; set; }
        public Nullable<int> IC_SECTIONOID { get; set; }
        public Nullable<int> IC_SECTIONTID { get; set; }
        public int IC_CUSTOMEROID { get; set; }
        public int IC_CUSTOMERTID { get; set; }
        public System.DateTime IC_DOCUDATE { get; set; }
        public string IC_CURRENCYID { get; set; }
        public string IC_OK { get; set; }
        public Nullable<System.DateTime> IC_OKDATE { get; set; }
        public string IC_STORNO { get; set; }
        public Nullable<System.DateTime> IC_STORNODAT { get; set; }
        public Nullable<int> IC_EMPLOYEEID { get; set; }
        public string IC_NOTE { get; set; }
        public double IC_CURRENCY_RATE { get; set; }
    
        public virtual CURRENCY CURRENCY { get; set; }
        public virtual CUSTOMER CUSTOMER { get; set; }
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_ACCOUNTCOMPENSATION_DETAIL> I_ACCOUNTCOMPENSATION_DETAIL { get; set; }
        public virtual SECTION SECTION { get; set; }
    }
}
