//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class I_INVOICEDETAIL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public I_INVOICEDETAIL()
        {
            this.I_INVOICEDETAIL_DISTRIB = new HashSet<I_INVOICEDETAIL_DISTRIB>();
        }
    
        public int OID { get; set; }
        public int TID { get; set; }
        public int ID_INVOICEOID { get; set; }
        public int ID_INVOICETID { get; set; }
        public Nullable<int> ID_PRODUCTOID { get; set; }
        public Nullable<int> ID_PRODUCTTID { get; set; }
        public Nullable<int> ID_CPCOID { get; set; }
        public Nullable<int> ID_CPCTID { get; set; }
        public string ID_CUSTOMCODE { get; set; }
        public double ID_QUANTITY { get; set; }
        public int ID_NEGATIV { get; set; }
        public int ID_QUID { get; set; }
        public double ID_UNITPRICE { get; set; }
        public Nullable<double> ID_UNITPRICEBC { get; set; }
        public Nullable<double> ID_CURRENCY_RATE { get; set; }
        public Nullable<double> ID_DISCOUNTPERCENT { get; set; }
        public Nullable<decimal> ID_DISCOUNT { get; set; }
        public Nullable<decimal> ID_NETTO { get; set; }
        public int ID_TAXDEFID { get; set; }
        public Nullable<decimal> ID_TAXVALUE { get; set; }
        public Nullable<decimal> ID_EUTAX { get; set; }
        public Nullable<decimal> ID_SUPPLIERTAX { get; set; }
        public Nullable<decimal> ID_BRUTTO { get; set; }
        public Nullable<double> ID_DIVISIONPERCENT { get; set; }
        public Nullable<int> ID_DETAILGROUP { get; set; }
        public string ID_DESCRIPTION { get; set; }
        public string ID_CONTCODE { get; set; }
        public string ID_TACC { get; set; }
        public string ID_KACC { get; set; }
        public Nullable<int> ID_PROJECTOID { get; set; }
        public Nullable<int> ID_PROJECTTID { get; set; }
        public Nullable<int> ID_RECTIFYDETOID { get; set; }
        public Nullable<int> ID_RECTIFYDETTID { get; set; }
        public string ID_CUSTPRODUCTCODE { get; set; }
        public string ID_CANREQUESTTAX { get; set; }
        public Nullable<int> ID_CUSTOMCHARGE { get; set; }
        public Nullable<double> ID_CUSTOMPERCENT { get; set; }
        public Nullable<double> ID_GROSSWEIGHT { get; set; }
        public Nullable<double> ID_NETWEIGHT { get; set; }
        public Nullable<decimal> ID_OTHERCOSTBC { get; set; }
    
        public virtual COSTCENTER COSTCENTER { get; set; }
        public virtual I_INVOICE I_INVOICE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_INVOICEDETAIL_DISTRIB> I_INVOICEDETAIL_DISTRIB { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual PROJECT PROJECT { get; set; }
        public virtual QUANTITY_UNIT QUANTITY_UNIT { get; set; }
        public virtual TAXDEF TAXDEF { get; set; }
    }
}
