//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class INTRASTAT_DETAIL
    {
        public int OID { get; set; }
        public int TID { get; set; }
        public int ISTD_INTRASTATOID { get; set; }
        public int ISTD_INTRASTATTID { get; set; }
        public Nullable<int> ISTD_DOCTID { get; set; }
        public Nullable<int> ISTD_DOCOID { get; set; }
        public Nullable<int> ISTD_DOCDETAILTID { get; set; }
        public Nullable<int> ISTD_DOCDETAILOID { get; set; }
        public int ISTD_PRODUCTOID { get; set; }
        public int ISTD_PRODUCTTID { get; set; }
        public string ISTD_STORNOED { get; set; }
        public string ISTD_TRANSACTIONNUMBER { get; set; }
        public string ISTD_MOVEMENTTYPE { get; set; }
        public Nullable<int> ISTD_SHIPMENTID { get; set; }
        public string ISTD_COUNTRY { get; set; }
        public string ISTD_ORIGINCOUNTRY { get; set; }
        public Nullable<int> ISTD_PARITYID { get; set; }
        public Nullable<int> ISTD_QUANTITY { get; set; }
        public Nullable<double> ISTD_NETTOWEIGHT { get; set; }
        public int ISTD_BRUTTO { get; set; }
        public Nullable<int> ISTD_STATBRUTTO { get; set; }
    
        public virtual COUNTRY COUNTRY { get; set; }
        public virtual INTRASTAT INTRASTAT { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual PARITY PARITY { get; set; }
        public virtual SHIPMENT SHIPMENT { get; set; }
    }
}
