//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class INTRASTAT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INTRASTAT()
        {
            this.INTRASTAT_DETAIL = new HashSet<INTRASTAT_DETAIL>();
        }
    
        public int OID { get; set; }
        public int TID { get; set; }
        public Nullable<int> IST_DOCUOWNNUMBER { get; set; }
        public string IST_DOCUNUMBER { get; set; }
        public Nullable<int> IST_SECTIONOID { get; set; }
        public Nullable<int> IST_SECTIONTID { get; set; }
        public Nullable<int> IST_ORIGINOID { get; set; }
        public Nullable<int> IST_ORIGINTID { get; set; }
        public System.DateTime IST_DATE { get; set; }
        public Nullable<int> IST_EMPLOYEEID { get; set; }
        public string IST_STORNO { get; set; }
        public Nullable<System.DateTime> IST_STORNODATE { get; set; }
        public string IST_OK { get; set; }
        public Nullable<System.DateTime> IST_OKDATE { get; set; }
        public string IST_DETAILGENERATED { get; set; }
        public string IST_ISREVISION { get; set; }
        public string IST_NOTE { get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INTRASTAT_DETAIL> INTRASTAT_DETAIL { get; set; }
        public virtual SECTION SECTION { get; set; }
    }
}
