//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVENTORY_DETAIL
    {
        public int OID { get; set; }
        public int TID { get; set; }
        public int IND_INVENTORYOID { get; set; }
        public int IND_INVENTORYTID { get; set; }
        public int IND_PRODUCTOID { get; set; }
        public int IND_PRODUCTTID { get; set; }
        public double IND_QUANTITY { get; set; }
        public Nullable<double> IND_CQUANTITY { get; set; }
        public int IND_QUID { get; set; }
        public Nullable<double> IND_UNITPRICEBC { get; set; }
        public string IND_SERIALNUMBER { get; set; }
        public Nullable<System.DateTime> IND_LIMITDAY { get; set; }
        public string IND_TAG { get; set; }
        public string IND_COMMENT { get; set; }
        public string IND_FORCE { get; set; }
    
        public virtual INVENTORY INVENTORY { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual QUANTITY_UNIT QUANTITY_UNIT { get; set; }
    }
}
