//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVENTORY_PGS
    {
        public int OID { get; set; }
        public int TID { get; set; }
        public int INPGS_MASTER_OID { get; set; }
        public int INPGS_MASTER_TID { get; set; }
        public int INPGS_PGSN_ID { get; set; }
    
        public virtual INVENTORY INVENTORY { get; set; }
        public virtual PRODUCTGROUPSNAME PRODUCTGROUPSNAME { get; set; }
    }
}
