//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class KOMISSIOMOD_INDETAIL
    {
        public int OID { get; set; }
        public int TID { get; set; }
        public int KOMID_KOMISSIOMODOID { get; set; }
        public int KOMID_KOMISSIOMODTID { get; set; }
        public int KOMID_WAREHOUSEID { get; set; }
        public int KOMID_PRODUCTOID { get; set; }
        public int KOMID_PRODUCTTID { get; set; }
        public double KOMID_QUANTITY { get; set; }
        public int KOMID_QUID { get; set; }
        public Nullable<System.DateTime> KOMID_LIMITDAY { get; set; }
        public string KOMID_SERIALNUMBER { get; set; }
        public string KOMID_TAG { get; set; }
        public string KOMID_DESCRIPTION { get; set; }
        public Nullable<int> KOMID_PROJECTTID { get; set; }
        public Nullable<int> KOMID_PROJECTOID { get; set; }
        public Nullable<int> KOMID_COSTCENTEROID { get; set; }
        public Nullable<int> KOMID_COSTCENTERTID { get; set; }
    
        public virtual COSTCENTER COSTCENTER { get; set; }
        public virtual KOMISSIOMOD KOMISSIOMOD { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual QUANTITY_UNIT QUANTITY_UNIT { get; set; }
        public virtual PROJECT PROJECT { get; set; }
    }
}
