//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOADDIVISION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOADDIVISION()
        {
            this.LOADDIVISION_DETAIL = new HashSet<LOADDIVISION_DETAIL>();
        }
    
        public int OID { get; set; }
        public int TID { get; set; }
        public string LD_DOCNUMBER { get; set; }
        public string LD_DOCUOWNNUMBER { get; set; }
        public System.DateTime LD_DOCUDATE { get; set; }
        public Nullable<int> LD_SECTIONOID { get; set; }
        public Nullable<int> LD_SECTIONTID { get; set; }
        public Nullable<int> LD_EMPLOYEEID { get; set; }
        public Nullable<int> LD_DIVISIONTYPEID { get; set; }
        public string LD_CURRENCY { get; set; }
        public double LD_CURRENCY_RATE { get; set; }
        public string LD_OK { get; set; }
        public Nullable<System.DateTime> LD_OKDATE { get; set; }
        public string LD_STORNO { get; set; }
        public Nullable<System.DateTime> LD_STORNODAT { get; set; }
        public string LD_BASEDOC { get; set; }
        public Nullable<int> LD_IINVOICEOID { get; set; }
        public Nullable<int> LD_IINVOICETID { get; set; }
        public Nullable<int> LD_AVISOOID { get; set; }
        public Nullable<int> LD_AVISOTID { get; set; }
        public decimal LD_AMOUNT { get; set; }
        public decimal LD_AMOUNTBC { get; set; }
        public string LD_DIVMODE { get; set; }
        public Nullable<int> LD_QUID { get; set; }
        public string LD_DIVDOC { get; set; }
        public string LD_COMMENT { get; set; }
        public string LD_TACC { get; set; }
        public string LD_KACC { get; set; }
        public Nullable<int> LD_PROJECTOID { get; set; }
        public Nullable<int> LD_PROJECTTID { get; set; }
        public Nullable<int> LD_COSTCENTEROID { get; set; }
        public Nullable<int> LD_COSTCENTERTID { get; set; }
    
        public virtual AVISO AVISO { get; set; }
        public virtual COSTCENTER COSTCENTER { get; set; }
        public virtual CURRENCY CURRENCY { get; set; }
        public virtual DIVISIONTYPE DIVISIONTYPE { get; set; }
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        public virtual I_INVOICE I_INVOICE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOADDIVISION_DETAIL> LOADDIVISION_DETAIL { get; set; }
        public virtual PROJECT PROJECT { get; set; }
        public virtual SECTION SECTION { get; set; }
        public virtual QUANTITY_UNIT QUANTITY_UNIT { get; set; }
    }
}
