//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOADDIVISION_DETAIL
    {
        public int OID { get; set; }
        public int TID { get; set; }
        public int LDD_LOADDIVISIONOID { get; set; }
        public int LDD_LOADDIVISIONTID { get; set; }
        public int LDD_DOCOID { get; set; }
        public int LDD_DOCTID { get; set; }
        public int LDD_DOCDETOID { get; set; }
        public int LDD_DOCDETTID { get; set; }
        public string LDD_DOCCURRENCY { get; set; }
        public Nullable<double> LDD_DOCCURRENCYRATE { get; set; }
        public Nullable<double> LDD_DOCVALUE { get; set; }
        public Nullable<double> LDD_DOCVALUEBC { get; set; }
        public Nullable<System.DateTime> LDD_DOCDATE { get; set; }
        public Nullable<int> LDD_PRODUCTOID { get; set; }
        public Nullable<int> LDD_PRODUCTTID { get; set; }
        public Nullable<double> LDD_DIVRATE { get; set; }
        public Nullable<double> LDD_AMOUNTBC { get; set; }
        public Nullable<double> LDD_CUSTOMCHARGERATE { get; set; }
        public Nullable<double> LDD_CUSTOMCHARGEAMOUNT { get; set; }
        public Nullable<double> LDD_PRODCUSTCHARGESUMBC { get; set; }
        public Nullable<double> LDD_QUANTITY { get; set; }
        public Nullable<int> LDD_QUID { get; set; }
        public string LDD_FIXED { get; set; }
        public string LDD_CONTCODE { get; set; }
        public string LDD_TACC { get; set; }
        public string LDD_KACC { get; set; }
        public Nullable<int> LDD_PROJECTOID { get; set; }
        public Nullable<int> LDD_PROJECTTID { get; set; }
        public Nullable<int> LDD_COSTCENTEROID { get; set; }
        public Nullable<int> LDD_COSTCENTERTID { get; set; }
    
        public virtual COSTCENTER COSTCENTER { get; set; }
        public virtual CURRENCY CURRENCY { get; set; }
        public virtual LOADDIVISION LOADDIVISION { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual PROJECT PROJECT { get; set; }
        public virtual QUANTITY_UNIT QUANTITY_UNIT { get; set; }
    }
}
