//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MARKETREGISTER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MARKETREGISTER()
        {
            this.MARKETREGISTER_DETAIL = new HashSet<MARKETREGISTER_DETAIL>();
        }
    
        public int OID { get; set; }
        public int TID { get; set; }
        public Nullable<int> MR_DOCUOWNNUMBER { get; set; }
        public string MR_SELLINGNUMBER { get; set; }
        public int MR_PAYMENTID { get; set; }
        public Nullable<int> MR_SECTIONOID { get; set; }
        public Nullable<int> MR_SECTIONTID { get; set; }
        public int MR_WAREHOUSEID { get; set; }
        public int MR_CUSTOMEROID { get; set; }
        public int MR_CUSTOMERTID { get; set; }
        public string MR_CUSTOMERNAME { get; set; }
        public string MR_FIRSTNAME { get; set; }
        public string MR_LASTNAME { get; set; }
        public string MR_COUNTRY { get; set; }
        public string MR_ZIP { get; set; }
        public string MR_CITY { get; set; }
        public string MR_STREET { get; set; }
        public string MR_ACCOUNTNUMBER { get; set; }
        public Nullable<int> MR_EMPLOYEEID { get; set; }
        public Nullable<int> MR_SHIPPINGEMPLOYEEID { get; set; }
        public Nullable<int> MR_MONITORINGEMPLOYEEID { get; set; }
        public Nullable<int> MR_SETUPEMPLOYEEID { get; set; }
        public System.DateTime MR_INVOICEDATE { get; set; }
        public System.DateTime MR_FULFILMENT { get; set; }
        public Nullable<System.DateTime> MR_DEADLINE { get; set; }
        public Nullable<System.DateTime> MR_ORIGINDATE { get; set; }
        public string MR_FULFILM_PLACE { get; set; }
        public string MR_STORNO { get; set; }
        public Nullable<System.DateTime> MR_STORNODAT { get; set; }
        public string MR_OK { get; set; }
        public Nullable<System.DateTime> MR_OKDATE { get; set; }
        public Nullable<decimal> MR_NETTO { get; set; }
        public double MR_PRICEMULTIPLIER { get; set; }
        public Nullable<double> MR_DISCOUNTPERCENT { get; set; }
        public Nullable<decimal> MR_DISCOUNT { get; set; }
        public Nullable<decimal> MR_TAX { get; set; }
        public Nullable<decimal> MR_BRUTTO { get; set; }
        public Nullable<decimal> MR_PAY_BRUTTO { get; set; }
        public Nullable<int> MR_PRICETYPEID { get; set; }
        public decimal MR_PRECISION { get; set; }
        public string MR_NOTE { get; set; }
        public Nullable<decimal> MR_DETAILPRECISION { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        public virtual EMPLOYEE EMPLOYEE1 { get; set; }
        public virtual EMPLOYEE EMPLOYEE2 { get; set; }
        public virtual EMPLOYEE EMPLOYEE3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MARKETREGISTER_DETAIL> MARKETREGISTER_DETAIL { get; set; }
        public virtual SECTION SECTION { get; set; }
        public virtual WAREHOUSE WAREHOUSE { get; set; }
        public virtual PAYMENT PAYMENT { get; set; }
        public virtual PRICETYPE PRICETYPE { get; set; }
    }
}
