//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEOVALUE
    {
        public int OID { get; set; }
        public int TID { get; set; }
        public int MV_MEOOID { get; set; }
        public int MV_MEOTID { get; set; }
        public int MV_MEOPARAMNAMEID { get; set; }
        public string MV_TYPE { get; set; }
        public string MV_CHARVALUE { get; set; }
        public Nullable<double> MV_FLOATVALUE { get; set; }
        public Nullable<int> MV_INTVALUE { get; set; }
        public Nullable<int> MV_QUID { get; set; }
    
        public virtual MEO MEO { get; set; }
        public virtual MEOPARAMNAME MEOPARAMNAME { get; set; }
        public virtual QUANTITY_UNIT QUANTITY_UNIT { get; set; }
    }
}
