//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MFPROVINCE
    {
        public int OID { get; set; }
        public int TID { get; set; }
        public string MFP_METHOD { get; set; }
        public int MFP_MFOID { get; set; }
        public int MFP_MFTID { get; set; }
        public Nullable<decimal> MFP_CRAMOUNT { get; set; }
        public Nullable<decimal> MFP_DEAMOUNT { get; set; }
        public Nullable<int> MFP_DOCOID { get; set; }
        public Nullable<int> MFP_DOCTID { get; set; }
        public Nullable<int> MFP_DOCDOID { get; set; }
        public Nullable<int> MFP_DOCDTID { get; set; }
        public string MFP_DOCNUMBER { get; set; }
        public Nullable<int> MFP_CONTOID { get; set; }
        public Nullable<int> MFP_CONTTID { get; set; }
        public string MFP_NAME { get; set; }
        public string MFP_NOTE { get; set; }
        public Nullable<System.DateTime> MFP_BOOKDATE { get; set; }
        public System.DateTime MFP_VALUEDATE { get; set; }
    
        public virtual MFDEFS MFDEFS { get; set; }
    }
}
