//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOVESTOCK_IN_SERIAL
    {
        public Nullable<double> MSIS_C_QUANTITY { get; set; }
        public Nullable<int> MSIS_C_QUID { get; set; }
        public string MSIS_CONTROLLED { get; set; }
        public Nullable<int> MSIS_DETAIL_OID { get; set; }
        public Nullable<int> MSIS_DETAIL_TID { get; set; }
        public string MSIS_FORCE { get; set; }
        public Nullable<System.DateTime> MSIS_LIMITDAY { get; set; }
        public int MSIS_MASTER_OID { get; set; }
        public int MSIS_MASTER_TID { get; set; }
        public Nullable<double> MSIS_MB_QUANTITY { get; set; }
        public Nullable<int> MSIS_MB_QUID { get; set; }
        public Nullable<double> MSIS_MN_QUANTITY { get; set; }
        public Nullable<int> MSIS_MN_QUID { get; set; }
        public Nullable<int> MSIS_NOTICEOID { get; set; }
        public string MSIS_NUMTYPE { get; set; }
        public int OID { get; set; }
        public Nullable<int> MSIS_PFDIVISIONOID { get; set; }
        public Nullable<int> MSIS_PFDIVISIONTID { get; set; }
        public Nullable<int> MSIS_PRODUCTOID { get; set; }
        public Nullable<int> MSIS_PRODUCTTID { get; set; }
        public Nullable<double> MSIS_QUANTITY { get; set; }
        public Nullable<int> MSIS_QUID { get; set; }
        public string MSIS_SERIALNUMBER { get; set; }
        public Nullable<double> MSIS_STOCKQUANTITY { get; set; }
        public string MSIS_TAG { get; set; }
        public int TID { get; set; }
        public Nullable<double> MSIS_UNITPRICEBC { get; set; }
        public Nullable<double> MSIS_V_QUANTITY { get; set; }
        public Nullable<int> MSIS_V_QUID { get; set; }
        public Nullable<int> MSIS_MOVESTOCK_OUT_SERIALOID { get; set; }
        public Nullable<int> MSIS_MOVESTOCK_OUT_SERIALTID { get; set; }
    
        public virtual C_QUANTITY_UNIT C_QUANTITY_UNIT { get; set; }
        public virtual MB_QUANTITY_UNIT MB_QUANTITY_UNIT { get; set; }
        public virtual MN_QUANTITY_UNIT MN_QUANTITY_UNIT { get; set; }
        public virtual MOVESTOCK_IN MOVESTOCK_IN { get; set; }
        public virtual MOVESTOCK_OUT_SERIAL MOVESTOCK_OUT_SERIAL { get; set; }
        public virtual PFDIVISION PFDIVISION { get; set; }
        public virtual QUANTITY_UNIT QUANTITY_UNIT { get; set; }
        public virtual V_QUANTITY_UNIT V_QUANTITY_UNIT { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
