//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOVESTOCK_OUT_DETAIL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MOVESTOCK_OUT_DETAIL()
        {
            this.STOCKKEEPERREPORT_DETAIL = new HashSet<STOCKKEEPERREPORT_DETAIL>();
        }
    
        public string MSOD_COMMENT { get; set; }
        public string MSOD_CONTCODE { get; set; }
        public Nullable<double> MSOD_CQUANTITY { get; set; }
        public string MSOD_FORCE { get; set; }
        public string MSOD_KACC { get; set; }
        public Nullable<System.DateTime> MSOD_LIMITDAY { get; set; }
        public int MSOD_MASTER_OID { get; set; }
        public int MSOD_MASTER_TID { get; set; }
        public int OID { get; set; }
        public int MSOD_PRODUCTOID { get; set; }
        public int MSOD_PRODUCTTID { get; set; }
        public Nullable<int> MSOD_PROJECTOID { get; set; }
        public Nullable<int> MSOD_PROJECTTID { get; set; }
        public double MSOD_QUANTITY { get; set; }
        public int MSOD_QUID { get; set; }
        public string MSOD_SERIALNUMBER { get; set; }
        public string MSOD_TACC { get; set; }
        public string MSOD_TAG { get; set; }
        public int TID { get; set; }
        public Nullable<int> MSOD_COSTCENTEROID { get; set; }
        public Nullable<int> MSOD_COSTCENTERTID { get; set; }
    
        public virtual COSTCENTER COSTCENTER { get; set; }
        public virtual MOVESTOCK_OUT MOVESTOCK_OUT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STOCKKEEPERREPORT_DETAIL> STOCKKEEPERREPORT_DETAIL { get; set; }
        public virtual PROJECT PROJECT { get; set; }
        public virtual QUANTITY_UNIT QUANTITY_UNIT { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
