//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class OC_OPERATIONS_PROCESSED
    {
        public string BATCHID { get; set; }
        public int OID { get; set; }
        public int TID { get; set; }
        public Nullable<double> MULTIPLIER { get; set; }
        public string SKIPPED { get; set; }
    }
}
