//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPTIONEDMOD_PRODUCTGROUPS
    {
        public int OID { get; set; }
        public int TID { get; set; }
        public int OPG_MASTER_OID { get; set; }
        public int OPG_MASTER_TID { get; set; }
        public int OPG_PRODUCTGROUPID { get; set; }
    
        public virtual OPTIONEDMOD OPTIONEDMOD { get; set; }
        public virtual PRODUCTGROUP PRODUCTGROUP { get; set; }
    }
}
