//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PACKINGWORK_PACKINGUNITS
    {
        public int OID { get; set; }
        public int TID { get; set; }
        public int PWU_PACKINGOID { get; set; }
        public int PWU_PACKINGTID { get; set; }
        public Nullable<int> PWU_PRODUCTOID { get; set; }
        public Nullable<int> PWU_PRODUCTTID { get; set; }
        public string PWU_SERIALNUMBER { get; set; }
        public Nullable<double> PWU_NETTOWEIGHT { get; set; }
        public Nullable<double> PWU_BRUTTOWEIGHT { get; set; }
        public string PWU_STATE { get; set; }
    
        public virtual PACKING PACKING { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
