//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PACKINGWORK_CONTAINS
    {
        public int PWC_OID1 { get; set; }
        public int PWC_TID1 { get; set; }
        public int PWC_OID2 { get; set; }
        public int PWC_TID2 { get; set; }
        public double PWC_QUANTITY { get; set; }
        public string PWC_SERIALNUMBER { get; set; }
    }
}
