//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PACKING_DETAIL
    {
        public int OID { get; set; }
        public int TID { get; set; }
        public int PCD_PACKINGOID { get; set; }
        public int PCD_PACKINGTID { get; set; }
        public Nullable<int> PCD_PRODUCTOID { get; set; }
        public Nullable<int> PCD_PRODUCTTID { get; set; }
        public double PCD_QUANTITY { get; set; }
        public Nullable<double> PCD_CQUANTITY { get; set; }
        public int PCD_QUID { get; set; }
        public double PCD_UNITPRICE { get; set; }
        public string PCD_CURRENCY { get; set; }
        public double PCD_CURRENCY_RATE { get; set; }
        public Nullable<double> PCD_UNITPRICEBC { get; set; }
        public Nullable<decimal> PCD_NETTO { get; set; }
        public int PCD_TAXDEFID { get; set; }
        public Nullable<decimal> PCD_TAXVALUE { get; set; }
        public Nullable<decimal> PCD_BRUTTO { get; set; }
        public Nullable<System.DateTime> PCD_LIMITDAY { get; set; }
        public string PCD_SERIALNUMBER { get; set; }
        public string PCD_TAG { get; set; }
        public string PCD_FORCE { get; set; }
        public string PCD_DESCRIPTION { get; set; }
        public string PCD_NOTE { get; set; }
        public Nullable<double> PCD_NETTOWEIGHT { get; set; }
        public Nullable<double> PCD_BRUTTOWEIGHT { get; set; }
        public Nullable<double> PCD_HEIGHT { get; set; }
        public Nullable<double> PCD_WIDTH { get; set; }
        public Nullable<double> PCD_LENGTH { get; set; }
        public Nullable<int> PCD_DETAILGROUP { get; set; }
    
        public virtual CURRENCY CURRENCY { get; set; }
        public virtual PACKING PACKING { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual QUANTITY_UNIT QUANTITY_UNIT { get; set; }
        public virtual TAXDEF TAXDEF { get; set; }
    }
}
