//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAYMENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PAYMENT()
        {
            this.AGENTPREMIUMRULE = new HashSet<AGENTPREMIUMRULE>();
            this.AVISO = new HashSet<AVISO>();
            this.BUYUP = new HashSet<BUYUP>();
            this.CASHFLOWDEF = new HashSet<CASHFLOWDEF>();
            this.CONSIGNMENT_IN = new HashSet<CONSIGNMENT_IN>();
            this.CONSIGNMENT_OUT = new HashSet<CONSIGNMENT_OUT>();
            this.CONSIGNMENTREPORT = new HashSet<CONSIGNMENTREPORT>();
            this.CUSTOMDOC = new HashSet<CUSTOMDOC>();
            this.CUSTOMER = new HashSet<CUSTOMER>();
            this.DELIVERYCONTRACT = new HashSet<DELIVERYCONTRACT>();
            this.DELIVERYOFFER = new HashSet<DELIVERYOFFER>();
            this.DELIVERYORDER = new HashSet<DELIVERYORDER>();
            this.DIRECTBUY = new HashSet<DIRECTBUY>();
            this.DIRECTSELL = new HashSet<DIRECTSELL>();
            this.DISCOUNTRULE = new HashSet<DISCOUNTRULE>();
            this.DPI_INVOICE = new HashSet<DPI_INVOICE>();
            this.DPO_INVOICE = new HashSet<DPO_INVOICE>();
            this.I_INVOICE = new HashSet<I_INVOICE>();
            this.I_INVOICE_SCANSION = new HashSet<I_INVOICE_SCANSION>();
            this.I_SETTLE = new HashSet<I_SETTLE>();
            this.JUSTWAYBILL = new HashSet<JUSTWAYBILL>();
            this.KOMISSIO = new HashSet<KOMISSIO>();
            this.MARKETREGISTER = new HashSet<MARKETREGISTER>();
            this.O_INVOICE = new HashSet<O_INVOICE>();
            this.O_INVOICE_SCANSION = new HashSet<O_INVOICE_SCANSION>();
            this.O_SETTLE = new HashSet<O_SETTLE>();
            this.PRODREQUEST = new HashSet<PRODREQUEST>();
            this.SERVICECONTRACT = new HashSet<SERVICECONTRACT>();
            this.TOOLMAKECONTRACT = new HashSet<TOOLMAKECONTRACT>();
            this.WAYBILL = new HashSet<WAYBILL>();
            this.RETREIVECHANGE = new HashSet<RETREIVECHANGE>();
            this.STORE_OUT = new HashSet<STORE_OUT>();
        }
    
        public int PAYMENTID { get; set; }
        public string PAYMENTNAME { get; set; }
        public string CASHDESKTYPE { get; set; }
        public string PAYMENTCODE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AGENTPREMIUMRULE> AGENTPREMIUMRULE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AVISO> AVISO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BUYUP> BUYUP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CASHFLOWDEF> CASHFLOWDEF { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONSIGNMENT_IN> CONSIGNMENT_IN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONSIGNMENT_OUT> CONSIGNMENT_OUT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONSIGNMENTREPORT> CONSIGNMENTREPORT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUSTOMDOC> CUSTOMDOC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUSTOMER> CUSTOMER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DELIVERYCONTRACT> DELIVERYCONTRACT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DELIVERYOFFER> DELIVERYOFFER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DELIVERYORDER> DELIVERYORDER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DIRECTBUY> DIRECTBUY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DIRECTSELL> DIRECTSELL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DISCOUNTRULE> DISCOUNTRULE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DPI_INVOICE> DPI_INVOICE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DPO_INVOICE> DPO_INVOICE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_INVOICE> I_INVOICE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_INVOICE_SCANSION> I_INVOICE_SCANSION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_SETTLE> I_SETTLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JUSTWAYBILL> JUSTWAYBILL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KOMISSIO> KOMISSIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MARKETREGISTER> MARKETREGISTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<O_INVOICE> O_INVOICE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<O_INVOICE_SCANSION> O_INVOICE_SCANSION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<O_SETTLE> O_SETTLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODREQUEST> PRODREQUEST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SERVICECONTRACT> SERVICECONTRACT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TOOLMAKECONTRACT> TOOLMAKECONTRACT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WAYBILL> WAYBILL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RETREIVECHANGE> RETREIVECHANGE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STORE_OUT> STORE_OUT { get; set; }
    }
}
