//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAYMENTKIND
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PAYMENTKIND()
        {
            this.I_INVOICE_SCANSION = new HashSet<I_INVOICE_SCANSION>();
            this.O_INVOICE_SCANSION = new HashSet<O_INVOICE_SCANSION>();
        }
    
        public int PAYMENTKINDID { get; set; }
        public string PAYMENTKINDNAME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_INVOICE_SCANSION> I_INVOICE_SCANSION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<O_INVOICE_SCANSION> O_INVOICE_SCANSION { get; set; }
    }
}
