//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PC_BASEPRCOST
    {
        public int BPRD_OPERATIONOID { get; set; }
        public int BPRD_OPERATIONTID { get; set; }
        public int BPRD_PRODUCTOID { get; set; }
        public int BPRD_PRODUCTTID { get; set; }
        public int BPRD_SUBSTATESOID { get; set; }
        public int BPRD_SUBSTATESTID { get; set; }
        public decimal BPRD_VALUE { get; set; }
        public double BPRD_QUANTITY { get; set; }
        public int BPRD_QUID { get; set; }
    
        public virtual QUANTITY_UNIT QUANTITY_UNIT { get; set; }
        public virtual PC_OPERATIONS PC_OPERATIONS { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
