//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PC_COLLDEF
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PC_COLLDEF()
        {
            this.PC_COLLECTED = new HashSet<PC_COLLECTED>();
            this.PC_COLLECTORS = new HashSet<PC_COLLECTORS>();
            this.PC_QUOTES = new HashSet<PC_QUOTES>();
            this.PC_COLLDEFINCLUDE = new HashSet<PC_COLLDEFINCLUDE>();
            this.PC_COLLECTORINFLUENCE = new HashSet<PC_COLLECTORINFLUENCE>();
            this.PC_COST_DETAIL = new HashSet<PC_COST_DETAIL>();
            this.PC_COSTNAMES = new HashSet<PC_COSTNAMES>();
            this.PC_DIVIDED_COST = new HashSet<PC_DIVIDED_COST>();
            this.PC_OFFERVARIATION_PLANNEDCOLLECTIONS = new HashSet<PC_OFFERVARIATION_PLANNEDCOLLECTIONS>();
            this.PC_OPERATIONSHEET_COLLECTORS_DETAIL = new HashSet<PC_OPERATIONSHEET_COLLECTORS_DETAIL>();
            this.PC_PRECALCULATED_COST = new HashSet<PC_PRECALCULATED_COST>();
            this.PC_PLANNEDCOLLECTION = new HashSet<PC_PLANNEDCOLLECTION>();
        }
    
        public int CD_ID { get; set; }
        public string CD_NAME { get; set; }
        public string CD_AQ { get; set; }
        public Nullable<int> CD_QUID { get; set; }
    
        public virtual QUANTITY_UNIT QUANTITY_UNIT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PC_COLLECTED> PC_COLLECTED { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PC_COLLECTORS> PC_COLLECTORS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PC_QUOTES> PC_QUOTES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PC_COLLDEFINCLUDE> PC_COLLDEFINCLUDE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PC_COLLECTORINFLUENCE> PC_COLLECTORINFLUENCE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PC_COST_DETAIL> PC_COST_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PC_COSTNAMES> PC_COSTNAMES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PC_DIVIDED_COST> PC_DIVIDED_COST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PC_OFFERVARIATION_PLANNEDCOLLECTIONS> PC_OFFERVARIATION_PLANNEDCOLLECTIONS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PC_OPERATIONSHEET_COLLECTORS_DETAIL> PC_OPERATIONSHEET_COLLECTORS_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PC_PRECALCULATED_COST> PC_PRECALCULATED_COST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PC_PLANNEDCOLLECTION> PC_PLANNEDCOLLECTION { get; set; }
    }
}
