//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PC_COST_POSTS_SH
    {
        public int CTP_STATEID { get; set; }
        public System.DateTime CTP_STATEDATE { get; set; }
        public int CTP_MANUFACTUREOID { get; set; }
        public int CTP_MANUFACTURETID { get; set; }
        public int CTP_COSTOID { get; set; }
        public int CTP_COSTTID { get; set; }
        public int CTP_PRODUCTOID { get; set; }
        public int CTP_PRODUCTTID { get; set; }
        public decimal CTP_POSTEDVALUE { get; set; }
    }
}
