//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PC_MANUFACTURE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PC_MANUFACTURE()
        {
            this.PC_ALLOCATION = new HashSet<PC_ALLOCATION>();
            this.PC_MANOPERINFO = new HashSet<PC_MANOPERINFO>();
            this.PC_MANOPERPREV = new HashSet<PC_MANOPERPREV>();
            this.PC_MANUCLOSE = new HashSet<PC_MANUCLOSE>();
            this.PC_MANUFACTURE_UNTAGGED_PRODUCTS = new HashSet<PC_MANUFACTURE_UNTAGGED_PRODUCTS>();
            this.PC_MANUFACTURELOG = new HashSet<PC_MANUFACTURELOG>();
            this.PC_MANUMOVE_IN = new HashSet<PC_MANUMOVE_IN>();
            this.PC_MANUMOVE_OUT = new HashSet<PC_MANUMOVE_OUT>();
            this.PC_MANUSEND = new HashSet<PC_MANUSEND>();
            this.PC_OFFERTARGETQUANTITIES = new HashSet<PC_OFFERTARGETQUANTITIES>();
            this.PC_OFFERVARIATIONS = new HashSet<PC_OFFERVARIATIONS>();
            this.PC_OPERATIONSHEET = new HashSet<PC_OPERATIONSHEET>();
            this.PC_PLIST = new HashSet<PC_PLIST>();
            this.PC_PRODUCEDPRODUCTS = new HashSet<PC_PRODUCEDPRODUCTS>();
            this.PC_QCREPORT = new HashSet<PC_QCREPORT>();
            this.PC_COST_POSTS = new HashSet<PC_COST_POSTS>();
        }
    
        public int OID { get; set; }
        public int TID { get; set; }
        public string MF_NUMBER { get; set; }
        public string MF_NAME { get; set; }
        public Nullable<int> MF_PROJECTOID { get; set; }
        public Nullable<int> MF_PROJECTTID { get; set; }
        public System.DateTime MF_DEADLINE { get; set; }
        public Nullable<System.DateTime> MF_PLANNEDSTART { get; set; }
        public Nullable<decimal> MF_PLANNEDCOST { get; set; }
        public double MF_PLANNEDDURATION { get; set; }
        public string MF_TIMEBASE { get; set; }
        public int MF_ORGANIZER { get; set; }
        public string MF_MATURECALC { get; set; }
        public Nullable<int> MF_SECTIONOID { get; set; }
        public Nullable<int> MF_SECTIONTID { get; set; }
        public int MF_WORKSHIFTID { get; set; }
        public Nullable<int> MF_SOURCETECHINSTRUCTIONSOID { get; set; }
        public Nullable<int> MF_SOURCETECHINSTRUCTIONSTID { get; set; }
        public int MF_BASESTORAGEID { get; set; }
        public string MF_NOTE { get; set; }
        public Nullable<int> MF_RESERVATIONBEGINNING { get; set; }
        public Nullable<int> MF_PLANTSOID { get; set; }
        public Nullable<int> MF_PLANTSTID { get; set; }
        public string MF_STATE { get; set; }
        public string MF_CALCULATION { get; set; }
        public int MF_VALUEDIFFFORCALC { get; set; }
        public string MF_TAGMODE { get; set; }
        public string MF_VIP { get; set; }
        public Nullable<int> MF_TARGETPRODUCTOID { get; set; }
        public Nullable<int> MF_TARGETPRODUCTTID { get; set; }
        public Nullable<int> MF_TARGETQUID { get; set; }
        public string MF_OFFERRECALC { get; set; }
        public Nullable<int> MF_COSTCENTEROID { get; set; }
        public Nullable<int> MF_COSTCENTERTID { get; set; }
    
        public virtual COSTCENTER COSTCENTER { get; set; }
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PC_ALLOCATION> PC_ALLOCATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PC_MANOPERINFO> PC_MANOPERINFO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PC_MANOPERPREV> PC_MANOPERPREV { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PC_MANUCLOSE> PC_MANUCLOSE { get; set; }
        public virtual PC_PLANTS PC_PLANTS { get; set; }
        public virtual PC_TECHINSTRUCTIONS PC_TECHINSTRUCTIONS { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual PROJECT PROJECT { get; set; }
        public virtual SECTION SECTION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PC_MANUFACTURE_UNTAGGED_PRODUCTS> PC_MANUFACTURE_UNTAGGED_PRODUCTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PC_MANUFACTURELOG> PC_MANUFACTURELOG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PC_MANUMOVE_IN> PC_MANUMOVE_IN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PC_MANUMOVE_OUT> PC_MANUMOVE_OUT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PC_MANUSEND> PC_MANUSEND { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PC_OFFERTARGETQUANTITIES> PC_OFFERTARGETQUANTITIES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PC_OFFERVARIATIONS> PC_OFFERVARIATIONS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PC_OPERATIONSHEET> PC_OPERATIONSHEET { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PC_PLIST> PC_PLIST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PC_PRODUCEDPRODUCTS> PC_PRODUCEDPRODUCTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PC_QCREPORT> PC_QCREPORT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PC_COST_POSTS> PC_COST_POSTS { get; set; }
        public virtual QUANTITY_UNIT QUANTITY_UNIT { get; set; }
        public virtual WAREHOUSE WAREHOUSE { get; set; }
        public virtual PC_WORKSHIFT PC_WORKSHIFT { get; set; }
    }
}
