//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PC_MANUFACTURE_UNTAGGED_PRODUCTS
    {
        public int OID { get; set; }
        public int TID { get; set; }
        public int MUP_MANUFACTUREOID { get; set; }
        public int MUP_MANUFACTURETID { get; set; }
        public int MUP_PRODUCTOID { get; set; }
        public int MUP_PRODUCTTID { get; set; }
    
        public virtual PC_MANUFACTURE PC_MANUFACTURE { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
