//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PC_MANOPERTOOLS
    {
        public int OID { get; set; }
        public int TID { get; set; }
        public Nullable<int> MOT_TOOLOID { get; set; }
        public Nullable<int> MOT_TOOLTID { get; set; }
        public Nullable<int> MOT_OPERATIONOID { get; set; }
        public Nullable<int> MOT_OPERATIONTID { get; set; }
        public int MOT_PROTOOLDEMANDOID { get; set; }
        public int MOT_PROTOOLDEMANDTID { get; set; }
    
        public virtual PC_OPERATIONS PC_OPERATIONS { get; set; }
        public virtual PC_PROTOOLDEMAND PC_PROTOOLDEMAND { get; set; }
        public virtual PC_PROTOOLS PC_PROTOOLS { get; set; }
    }
}
