//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PC_MANUMOVE_OUT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PC_MANUMOVE_OUT()
        {
            this.PC_MANUMOVE_OUT_DETAIL = new HashSet<PC_MANUMOVE_OUT_DETAIL>();
            this.PC_MANUMOVE_OUT_SERIAL_FROM = new HashSet<PC_MANUMOVE_OUT_SERIAL_FROM>();
            this.PC_MANUMOVE_OUT_SERIAL_TO = new HashSet<PC_MANUMOVE_OUT_SERIAL_TO>();
        }
    
        public int OID { get; set; }
        public int TID { get; set; }
        public Nullable<int> MMO_DOCUOWNNUMBER { get; set; }
        public string MMO_DOCUNUMBER { get; set; }
        public System.DateTime MMO_DOCUDATE { get; set; }
        public Nullable<int> MMO_WAREHOUSEID { get; set; }
        public int MMO_MANUFACTUREOID { get; set; }
        public int MMO_MANUFACTURETID { get; set; }
        public Nullable<int> MMO_EMPLOYEEID { get; set; }
        public Nullable<int> MMO_SECTIONOID { get; set; }
        public Nullable<int> MMO_SECTIONTID { get; set; }
        public string MMO_OK { get; set; }
        public Nullable<System.DateTime> MMO_OKDATE { get; set; }
        public string MMO_STORNO { get; set; }
        public Nullable<System.DateTime> MMO_STORNODAT { get; set; }
        public string MMO_COMMENT { get; set; }
        public string MMO_TACC { get; set; }
        public string MMO_KACC { get; set; }
        public Nullable<int> MMO_PROJECTOID { get; set; }
        public Nullable<int> MMO_PROJECTTID { get; set; }
        public Nullable<int> MMO_COSTCENTEROID { get; set; }
        public Nullable<int> MMO_COSTCENTERTID { get; set; }
    
        public virtual COSTCENTER COSTCENTER { get; set; }
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        public virtual PC_MANUFACTURE PC_MANUFACTURE { get; set; }
        public virtual PROJECT PROJECT { get; set; }
        public virtual SECTION SECTION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PC_MANUMOVE_OUT_DETAIL> PC_MANUMOVE_OUT_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PC_MANUMOVE_OUT_SERIAL_FROM> PC_MANUMOVE_OUT_SERIAL_FROM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PC_MANUMOVE_OUT_SERIAL_TO> PC_MANUMOVE_OUT_SERIAL_TO { get; set; }
    }
}
