//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PC_MANUMOVE_OUT_SERIAL_FROM
    {
        public Nullable<double> MOSF_C_QUANTITY { get; set; }
        public Nullable<int> MOSF_C_QUID { get; set; }
        public string MOSF_CONTROLLED { get; set; }
        public Nullable<int> MOSF_DETAIL_OID { get; set; }
        public Nullable<int> MOSF_DETAIL_TID { get; set; }
        public string MOSF_FORCE { get; set; }
        public Nullable<System.DateTime> MOSF_LIMITDAY { get; set; }
        public int MOSF_MASTER_OID { get; set; }
        public int MOSF_MASTER_TID { get; set; }
        public Nullable<double> MOSF_MB_QUANTITY { get; set; }
        public Nullable<int> MOSF_MB_QUID { get; set; }
        public Nullable<double> MOSF_MN_QUANTITY { get; set; }
        public Nullable<int> MOSF_MN_QUID { get; set; }
        public Nullable<int> MOSF_NOTICEOID { get; set; }
        public string MOSF_NUMTYPE { get; set; }
        public int OID { get; set; }
        public Nullable<int> MOSF_PFDIVISIONOID { get; set; }
        public Nullable<int> MOSF_PFDIVISIONTID { get; set; }
        public Nullable<int> MOSF_PRODUCTOID { get; set; }
        public Nullable<int> MOSF_PRODUCTTID { get; set; }
        public Nullable<double> MOSF_QUANTITY { get; set; }
        public Nullable<int> MOSF_QUID { get; set; }
        public string MOSF_SERIALNUMBER { get; set; }
        public Nullable<double> MOSF_STOCKQUANTITY { get; set; }
        public string MOSF_TAG { get; set; }
        public int TID { get; set; }
        public Nullable<double> MOSF_UNITPRICEBC { get; set; }
        public Nullable<double> MOSF_V_QUANTITY { get; set; }
        public Nullable<int> MOSF_V_QUID { get; set; }
        public Nullable<double> MOSF_CQUANTITY { get; set; }
    
        public virtual C_QUANTITY_UNIT C_QUANTITY_UNIT { get; set; }
        public virtual MB_QUANTITY_UNIT MB_QUANTITY_UNIT { get; set; }
        public virtual MN_QUANTITY_UNIT MN_QUANTITY_UNIT { get; set; }
        public virtual PC_MANUMOVE_OUT PC_MANUMOVE_OUT { get; set; }
        public virtual PFDIVISION PFDIVISION { get; set; }
        public virtual QUANTITY_UNIT QUANTITY_UNIT { get; set; }
        public virtual V_QUANTITY_UNIT V_QUANTITY_UNIT { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
