//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PC_MANUFACTURELOG
    {
        public int OID { get; set; }
        public int TID { get; set; }
        public int MFL_MANUFACTUREOID { get; set; }
        public int MFL_MANUFACTURETID { get; set; }
        public System.DateTime MFL_EVENTDATE { get; set; }
        public string MFL_ACTION { get; set; }
        public int MFL_EMPLOYEEEMPLOYEEID { get; set; }
        public string MFL_NOTE { get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        public virtual PC_MANUFACTURE PC_MANUFACTURE { get; set; }
    }
}
