//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PC_OPFINALPRODUCT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PC_OPFINALPRODUCT()
        {
            this.PC_WORKINSTRUCTION_FINALPRODUCTS = new HashSet<PC_WORKINSTRUCTION_FINALPRODUCTS>();
        }
    
        public int OID { get; set; }
        public int TID { get; set; }
        public int OFP_OPERATIONSOID { get; set; }
        public int OFP_OPERATIONSTID { get; set; }
        public int OFP_PRODUCTOID { get; set; }
        public int OFP_PRODUCTTID { get; set; }
        public Nullable<int> OFP_SUBSTATESOID { get; set; }
        public Nullable<int> OFP_SUBSTATESTID { get; set; }
        public Nullable<double> OFP_F { get; set; }
        public Nullable<double> OFP_NORMMINUS { get; set; }
        public Nullable<double> OFP_NORMPLUS { get; set; }
        public int OFP_QUID { get; set; }
        public Nullable<double> OFP_R { get; set; }
        public Nullable<double> OFP_S { get; set; }
        public Nullable<double> OFP_U { get; set; }
        public string OFP_NORMMATERIAL { get; set; }
        public string OFP_MULTDEPENDS { get; set; }
        public string OFP_POTALLOC { get; set; }
    
        public virtual PC_OPERATIONS PC_OPERATIONS { get; set; }
        public virtual PC_SUBSTATES PC_SUBSTATES { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PC_WORKINSTRUCTION_FINALPRODUCTS> PC_WORKINSTRUCTION_FINALPRODUCTS { get; set; }
        public virtual QUANTITY_UNIT QUANTITY_UNIT { get; set; }
    }
}
