//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PC_OPERATIONSHEET_PROD_DETAIL
    {
        public Nullable<double> OSPD_C_QUANTITY { get; set; }
        public Nullable<int> OSPD_C_QUID { get; set; }
        public string OSPD_CONTROLLED { get; set; }
        public Nullable<int> OSPD_DETAIL_OID { get; set; }
        public Nullable<int> OSPD_DETAIL_TID { get; set; }
        public string OSPD_FORCE { get; set; }
        public Nullable<System.DateTime> OSPD_LIMITDAY { get; set; }
        public int OSPD_MASTER_OID { get; set; }
        public int OSPD_MASTER_TID { get; set; }
        public Nullable<double> OSPD_MB_QUANTITY { get; set; }
        public Nullable<int> OSPD_MB_QUID { get; set; }
        public Nullable<double> OSPD_MN_QUANTITY { get; set; }
        public Nullable<int> OSPD_MN_QUID { get; set; }
        public Nullable<int> OSPD_NOTICEOID { get; set; }
        public string OSPD_NUMTYPE { get; set; }
        public int OID { get; set; }
        public Nullable<int> OSPD_PFDIVISIONOID { get; set; }
        public Nullable<int> OSPD_PFDIVISIONTID { get; set; }
        public Nullable<int> OSPD_PRODUCTOID { get; set; }
        public Nullable<int> OSPD_PRODUCTTID { get; set; }
        public Nullable<double> OSPD_QUANTITY { get; set; }
        public Nullable<int> OSPD_QUID { get; set; }
        public string OSPD_SERIALNUMBER { get; set; }
        public Nullable<double> OSPD_STOCKQUANTITY { get; set; }
        public string OSPD_TAG { get; set; }
        public int TID { get; set; }
        public Nullable<double> OSPD_UNITPRICEBC { get; set; }
        public Nullable<double> OSPD_V_QUANTITY { get; set; }
        public Nullable<int> OSPD_V_QUID { get; set; }
        public Nullable<int> OSPD_OPERATION_FPOID { get; set; }
        public Nullable<int> OSPD_OPERATION_FPTID { get; set; }
        public Nullable<int> OSPD_SUBSTATESOID { get; set; }
        public Nullable<int> OSPD_SUBSTATESTID { get; set; }
        public Nullable<int> OSPD_WAREHOUSEID { get; set; }
        public string OSPD_MATERIALSOURCE { get; set; }
        public string OSPD_CHECKDIFF { get; set; }
        public Nullable<double> OSPD_CQUANTITY { get; set; }
        public Nullable<int> OSPD_PROJECTOID { get; set; }
        public Nullable<int> OSPD_PROJECTTID { get; set; }
        public string OSPD_COMMENT { get; set; }
        public Nullable<int> OSPD_COSTCENTEROID { get; set; }
        public Nullable<int> OSPD_COSTCENTERTID { get; set; }
    
        public virtual C_QUANTITY_UNIT C_QUANTITY_UNIT { get; set; }
        public virtual COSTCENTER COSTCENTER { get; set; }
        public virtual MB_QUANTITY_UNIT MB_QUANTITY_UNIT { get; set; }
        public virtual MN_QUANTITY_UNIT MN_QUANTITY_UNIT { get; set; }
        public virtual PC_OPERATIONSHEET PC_OPERATIONSHEET { get; set; }
        public virtual PC_SUBSTATES PC_SUBSTATES { get; set; }
        public virtual PROJECT PROJECT { get; set; }
        public virtual PFDIVISION PFDIVISION { get; set; }
        public virtual QUANTITY_UNIT QUANTITY_UNIT { get; set; }
        public virtual V_QUANTITY_UNIT V_QUANTITY_UNIT { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
