//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PC_PLAN_DETAIL
    {
        public int OID { get; set; }
        public int TID { get; set; }
        public int PLD_PLANOID { get; set; }
        public int PLD_PLANTID { get; set; }
        public Nullable<int> PLD_PRODUCTOID { get; set; }
        public Nullable<int> PLD_PRODUCTTID { get; set; }
        public Nullable<int> PLD_CUSTOMEROID { get; set; }
        public Nullable<int> PLD_CUSTOMERTID { get; set; }
        public double PLD_QUANTITY { get; set; }
        public int PLD_QUID { get; set; }
        public Nullable<int> PLD_TECHINSTRUCTIONOID { get; set; }
        public Nullable<int> PLD_TECHINSTRUCTIONTID { get; set; }
        public string PLD_NOTE { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
        public virtual PC_PLAN PC_PLAN { get; set; }
        public virtual PC_TECHINSTRUCTIONS PC_TECHINSTRUCTIONS { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual QUANTITY_UNIT QUANTITY_UNIT { get; set; }
    }
}
