//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PC_PRECALCULATED_COST_SH
    {
        public int PCC_STATEID { get; set; }
        public System.DateTime PCC_STATEDATE { get; set; }
        public int PCC_OPERATIONOID { get; set; }
        public int PCC_OPERATIONTID { get; set; }
        public int PCC_COLLDEFID { get; set; }
        public int PCC_REFOID { get; set; }
        public int PCC_REFTID { get; set; }
        public decimal PCC_VALUE { get; set; }
        public string PCC_TYPE { get; set; }
        public Nullable<int> PCC_COSTNAMEID { get; set; }
    }
}
