//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PC_PLANNEDCOLLECTION
    {
        public int PC_ID { get; set; }
        public int PC_COLLDEFID { get; set; }
        public Nullable<int> PC_EOID { get; set; }
        public Nullable<int> PC_ETID { get; set; }
        public Nullable<int> PC_TYPEID { get; set; }
        public Nullable<int> PC_SORTID { get; set; }
        public Nullable<int> PC_OPGROUP { get; set; }
        public Nullable<double> PC_VALUE { get; set; }
        public Nullable<int> PC_OPERATIONOID { get; set; }
        public Nullable<int> PC_OPERATIONTID { get; set; }
    
        public virtual PC_COLLDEF PC_COLLDEF { get; set; }
        public virtual PC_OPERATIONGROUPNAMES PC_OPERATIONGROUPNAMES { get; set; }
        public virtual PC_OPERATIONS PC_OPERATIONS { get; set; }
        public virtual PC_PROTOOLSORT PC_PROTOOLSORT { get; set; }
        public virtual PC_PROTOOLTYPE PC_PROTOOLTYPE { get; set; }
    }
}
