//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PC_PRODUCEDPRODUCTS
    {
        public int OID { get; set; }
        public int TID { get; set; }
        public int PP_MANUCLOSEOID { get; set; }
        public int PP_MANUCLOSETID { get; set; }
        public int PP_MANUFACTUREOID { get; set; }
        public int PP_MANUFACTURETID { get; set; }
        public int PP_PRODUCTOID { get; set; }
        public int PP_PRODUCTTID { get; set; }
        public int PP_QUID { get; set; }
        public double PP_QUANTITY { get; set; }
        public Nullable<double> PP_VALUE { get; set; }
        public Nullable<double> PP_ORIGPRDVALUE { get; set; }
        public Nullable<double> PP_ORIGSTOCKINDEPVALUE { get; set; }
        public Nullable<double> PP_CURRENTSTOCKINDEPVALUE { get; set; }
        public Nullable<double> PP_POSTEDSTOCKINDEPVALUE { get; set; }
        public Nullable<double> PP_POSTEDVALUE { get; set; }
    
        public virtual PC_MANUCLOSE PC_MANUCLOSE { get; set; }
        public virtual PC_MANUFACTURE PC_MANUFACTURE { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual QUANTITY_UNIT QUANTITY_UNIT { get; set; }
    }
}
