//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PC_PLANTSWORKTIME
    {
        public int OID { get; set; }
        public int TID { get; set; }
        public int PWT_PLANTSOID { get; set; }
        public int PWT_PLANTSTID { get; set; }
        public System.DateTime PWT_FROM { get; set; }
        public System.DateTime PWT_TO { get; set; }
        public string PWT_ISMON { get; set; }
        public string PWT_ISTHU { get; set; }
        public string PWT_ISWED { get; set; }
        public string PWT_ISTHR { get; set; }
        public string PWT_ISFRI { get; set; }
        public string PWT_ISSAT { get; set; }
        public string PWT_ISSUN { get; set; }
    
        public virtual PC_PLANTS PC_PLANTS { get; set; }
    }
}
