//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PC_QCREPORT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PC_QCREPORT()
        {
            this.PC_QCMEASURESHEETS = new HashSet<PC_QCMEASURESHEETS>();
            this.PC_QCREPORT_SLOTS = new HashSet<PC_QCREPORT_SLOTS>();
        }
    
        public int OID { get; set; }
        public int TID { get; set; }
        public Nullable<int> QR_DOCUOWNNUMBER { get; set; }
        public string QR_DOCUNUMBER { get; set; }
        public System.DateTime QR_DOCUDATE { get; set; }
        public string QR_OK { get; set; }
        public Nullable<System.DateTime> QR_OKDATE { get; set; }
        public string QR_STORNO { get; set; }
        public Nullable<System.DateTime> QR_STORNODAT { get; set; }
        public int QR_EMPLOYEEID { get; set; }
        public Nullable<int> QR_SECTIONOID { get; set; }
        public Nullable<int> QR_SECTIONTID { get; set; }
        public Nullable<int> QR_PROJECTOID { get; set; }
        public Nullable<int> QR_PROJECTTID { get; set; }
        public string QR_NOTE { get; set; }
        public Nullable<int> QR_MANUFACTUREOID { get; set; }
        public Nullable<int> QR_MANUFACTURETID { get; set; }
        public Nullable<int> QR_OPERATIONSOID { get; set; }
        public Nullable<int> QR_OPERATIONSTID { get; set; }
        public Nullable<int> QR_QCROPERATIONDEFOID { get; set; }
        public Nullable<int> QR_QCROPERATIONDEFTID { get; set; }
        public int QR_OPERATIONSHEETOID { get; set; }
        public int QR_OPERATIONSHEETTID { get; set; }
        public string QR_VALUATED { get; set; }
        public Nullable<int> QR_VALUATEDQUALITY { get; set; }
        public string QR_VALUATEDCLASS { get; set; }
        public string QR_ENABLEAUTOCLOSE { get; set; }
        public string QR_DIRECTCLOSE { get; set; }
        public Nullable<int> QR_COSTCENTEROID { get; set; }
        public Nullable<int> QR_COSTCENTERTID { get; set; }
    
        public virtual COSTCENTER COSTCENTER { get; set; }
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        public virtual PC_MANUFACTURE PC_MANUFACTURE { get; set; }
        public virtual PC_OPERATIONS PC_OPERATIONS { get; set; }
        public virtual PC_OPERATIONSHEET PC_OPERATIONSHEET { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PC_QCMEASURESHEETS> PC_QCMEASURESHEETS { get; set; }
        public virtual PC_QCROPERATIONDEF PC_QCROPERATIONDEF { get; set; }
        public virtual PROJECT PROJECT { get; set; }
        public virtual SECTION SECTION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PC_QCREPORT_SLOTS> PC_QCREPORT_SLOTS { get; set; }
    }
}
