//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PC_QCROPERATIONDEF
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PC_QCROPERATIONDEF()
        {
            this.PC_OPERATIONS = new HashSet<PC_OPERATIONS>();
            this.PC_QCREPORT = new HashSet<PC_QCREPORT>();
            this.PC_QCROPERATION_QCPRODUCT = new HashSet<PC_QCROPERATION_QCPRODUCT>();
            this.PC_QCROPERATION_SHEETDEF = new HashSet<PC_QCROPERATION_SHEETDEF>();
        }
    
        public int OID { get; set; }
        public int TID { get; set; }
        public string QOPD_NAME { get; set; }
        public string QOPD_DESCRIPTION { get; set; }
        public string QOPD_QCTYPE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PC_OPERATIONS> PC_OPERATIONS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PC_QCREPORT> PC_QCREPORT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PC_QCROPERATION_QCPRODUCT> PC_QCROPERATION_QCPRODUCT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PC_QCROPERATION_SHEETDEF> PC_QCROPERATION_SHEETDEF { get; set; }
    }
}
