//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PC_QCRSLOTINFO_LIMITS
    {
        public int QSIL_ID { get; set; }
        public int QSIL_QSI_ID { get; set; }
        public double QSIL_VALUE { get; set; }
        public string QSIL_LIMITTYPE { get; set; }
        public string QSIL_RULE { get; set; }
        public Nullable<int> QSIL_RULELIMIT { get; set; }
        public Nullable<int> QSIL_RULESUGGEST { get; set; }
    
        public virtual PC_QCRSLOTINFO PC_QCRSLOTINFO { get; set; }
    }
}
