//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PC_QCREPORT_SLOTS
    {
        public int QRS_MASTER_OID { get; set; }
        public int QRS_MASTER_TID { get; set; }
        public int OID { get; set; }
        public int QRS_QCROPERATION_SHEETDEFOID { get; set; }
        public int QRS_QCROPERATION_SHEETDEFTID { get; set; }
        public int QRS_QSI_ID { get; set; }
        public int TID { get; set; }
        public Nullable<double> QRS_VALUE { get; set; }
    
        public virtual PC_QCREPORT PC_QCREPORT { get; set; }
        public virtual PC_QCROPERATION_SHEETDEF PC_QCROPERATION_SHEETDEF { get; set; }
        public virtual PC_QCRSLOTINFO PC_QCRSLOTINFO { get; set; }
    }
}
