//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PC_WORKINSTRUCTION_BASEMATERIALS
    {
        public int WIBM_OPERATIONOID { get; set; }
        public int WIBM_OPERATIONTID { get; set; }
        public Nullable<int> WIBM_ID { get; set; }
        public int WIBM_BASEMATERIALOID { get; set; }
        public int WIBM_BASEMATERIALTID { get; set; }
        public Nullable<double> WIBM_QUANTITY { get; set; }
    
        public virtual PC_OPBASEMATERIALDEMAND PC_OPBASEMATERIALDEMAND { get; set; }
        public virtual PC_OPERATIONS PC_OPERATIONS { get; set; }
    }
}
