//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PFNOTICES
    {
        public int OID { get; set; }
        public int TID { get; set; }
        public int PFN_PRODUCTOID { get; set; }
        public int PFN_PRODUCTTID { get; set; }
        public int PFN_PFSTORAGEID { get; set; }
        public string PFN_METHOD { get; set; }
        public string PFN_STORNOED { get; set; }
        public double PFN_QUANTITY { get; set; }
        public Nullable<double> PFN_UNITPRICEBC { get; set; }
        public Nullable<System.DateTime> PFN_DATE { get; set; }
        public System.DateTime PFN_DOCUDATE { get; set; }
        public string PFN_SUBINDEX { get; set; }
        public Nullable<int> PFN_STOCKMODOID { get; set; }
        public Nullable<int> PFN_STOCKMODTID { get; set; }
        public Nullable<int> PFN_DOCOID { get; set; }
        public Nullable<int> PFN_DOCTID { get; set; }
        public Nullable<int> PFN_CUSTOMEROID { get; set; }
        public Nullable<int> PFN_CUSTOMERTID { get; set; }
        public string PFN_INITIATIVE { get; set; }
    
        public virtual PFSTORAGE PFSTORAGE { get; set; }
    }
}
