//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PFPROVINCE
    {
        public int OID { get; set; }
        public int TID { get; set; }
        public int PFP_PRODUCTOID { get; set; }
        public int PFP_PRODUCTTID { get; set; }
        public int PFP_PFSTORAGEID { get; set; }
        public string PFP_METHOD { get; set; }
        public double PFP_QUANTITY { get; set; }
        public Nullable<double> PFP_UNITPRICEBC { get; set; }
        public Nullable<System.DateTime> PFP_NOTICEDATE { get; set; }
    
        public virtual PFSTORAGE PFSTORAGE { get; set; }
    }
}
