//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PFSTOREDVALUE
    {
        public int TID { get; set; }
        public int PFSV_PRODUCTOID { get; set; }
        public int PFSV_PRODUCTTID { get; set; }
        public int PFSV_PFSTORAGEID { get; set; }
        public int PFSV_IDX { get; set; }
        public double PFSV_QUANTITY { get; set; }
        public double PFSV_VALUE { get; set; }
        public double PFSV_UNITPRICEBC { get; set; }
    
        public virtual PFSTORAGE PFSTORAGE { get; set; }
    }
}
