//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PFTAGDISTANCE
    {
        public int TID { get; set; }
        public int PFTD_WAREHOUSEID { get; set; }
        public string PFTD_TAG { get; set; }
        public string PFTD_OTHERTAG { get; set; }
        public int PFTD_DISTANCE { get; set; }
    
        public virtual WAREHOUSE WAREHOUSE { get; set; }
    }
}
