//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHSPRDCOLL
    {
        public int OID { get; set; }
        public int TID { get; set; }
        public int PHS_PHASEOID { get; set; }
        public int PHS_PHASETID { get; set; }
        public int PHS_PRDCOLLOID { get; set; }
        public int PHS_PRDCOLLTID { get; set; }
        public decimal PHS_VALUE { get; set; }
        public string PHS_RATIOTYPE { get; set; }
        public Nullable<double> PHS_STEPQNT { get; set; }
    
        public virtual PRDCOLL PRDCOLL { get; set; }
        public virtual PRDPHASE PRDPHASE { get; set; }
    }
}
