//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class POTENTIAL_STOCKINFO
    {
        public int PSI_PARTITIONTID { get; set; }
        public int PSI_WAREHOUSEID { get; set; }
        public int PSI_PRODUCTOID { get; set; }
        public int PSI_PRODUCTTID { get; set; }
        public System.DateTime PSI_DATED { get; set; }
        public int PSI_DATEI { get; set; }
        public int PSI_TIMEI { get; set; }
        public double PSI_POTENTIALSTOCK { get; set; }
        public double PSI_PLANNEDSTOCK { get; set; }
        public double PSI_AVAILABLESTOCK { get; set; }
    
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual WAREHOUSE WAREHOUSE { get; set; }
    }
}
