//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class POTENTIAL_STOCKINFO_MOVE
    {
        public int PSM_EOID { get; set; }
        public int PSM_ETID { get; set; }
        public int PSM_ROID { get; set; }
        public int PSM_RTID { get; set; }
        public int PSM_IDX { get; set; }
        public int PSM_FROMPARTITIONTID { get; set; }
        public int PSM_FROMWAREHOUSEID { get; set; }
        public int PSM_TOPARTITIONTID { get; set; }
        public int PSM_TOWAREHOUSEID { get; set; }
        public Nullable<int> PSM_PIDX { get; set; }
        public int PSM_IOID { get; set; }
        public int PSM_ITID { get; set; }
        public System.DateTime PSM_TIMESTAMP { get; set; }
    
        public virtual WAREHOUSE WAREHOUSE { get; set; }
        public virtual WAREHOUSE WAREHOUSE1 { get; set; }
    }
}
