//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class POTENTIAL_STOCKINFO_STOCK
    {
        public int PSS_EOID { get; set; }
        public int PSS_ETID { get; set; }
        public int PSS_ROID { get; set; }
        public int PSS_RTID { get; set; }
        public int PSS_IDX { get; set; }
        public string PSS_TYPE { get; set; }
        public int PSS_PARTITIONTID { get; set; }
        public int PSS_WAREHOUSEID { get; set; }
        public int PSS_PRODUCTOID { get; set; }
        public int PSS_PRODUCTTID { get; set; }
        public double PSS_QUANTITY { get; set; }
        public int PSS_QUID { get; set; }
        public System.DateTime PSS_BEGINTIME { get; set; }
        public Nullable<System.DateTime> PSS_ENDTIME { get; set; }
        public Nullable<int> PSS_MOVEIDX { get; set; }
        public Nullable<int> PSS_RESCHEDULEIDX { get; set; }
        public Nullable<int> PSS_QUANTITYIDX { get; set; }
        public int PSS_IOID { get; set; }
        public int PSS_ITID { get; set; }
        public System.DateTime PSS_TIMESTAMP { get; set; }
    
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual QUANTITY_UNIT QUANTITY_UNIT { get; set; }
        public virtual WAREHOUSE WAREHOUSE { get; set; }
    }
}
