//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class POTENTIAL_STOCKINFO_RESCHEDULE
    {
        public int PSR_EOID { get; set; }
        public int PSR_ETID { get; set; }
        public int PSR_ROID { get; set; }
        public int PSR_RTID { get; set; }
        public int PSR_IDX { get; set; }
        public System.DateTime PSR_FROMBEGINTIME { get; set; }
        public Nullable<System.DateTime> PSR_FROMENDTIME { get; set; }
        public System.DateTime PSR_TOBEGINTIME { get; set; }
        public Nullable<System.DateTime> PSR_TOENDTIME { get; set; }
        public Nullable<int> PSR_PIDX { get; set; }
        public int PSR_IOID { get; set; }
        public int PSR_ITID { get; set; }
        public System.DateTime PSR_TIMESTAMP { get; set; }
    }
}
