//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRMPHASE
    {
        public int PMPH_PRODMETHODID { get; set; }
        public int PMPH_PHASEOID { get; set; }
        public int PMPH_PHASETID { get; set; }
        public int PMPH_SEQUENCE { get; set; }
        public int PMPH_RATIO { get; set; }
    
        public virtual PRDPHASE PRDPHASE { get; set; }
        public virtual PRODMETHOD PRODMETHOD { get; set; }
    }
}
