//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTQRATES
    {
        public int PQR_PRODUCTOID { get; set; }
        public int PQR_PRODUCTTID { get; set; }
        public int PQR_QUID { get; set; }
        public double PQR_RATE { get; set; }
        public Nullable<double> PQR_NUMERATOR { get; set; }
        public Nullable<double> PQR_DENOMINATOR { get; set; }
        public string PQR_TYPE { get; set; }
        public string PQR_SUBCHANGER { get; set; }
        public string PQR_IMPLICATED { get; set; }
    
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual QUANTITY_UNIT QUANTITY_UNIT { get; set; }
    }
}
