//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTLANGCODES
    {
        public int OID { get; set; }
        public int TID { get; set; }
        public int PLC_PRODUCTOID { get; set; }
        public int PLC_PRODUCTTID { get; set; }
        public int PLC_LANGUAGEID { get; set; }
        public string PRIDENTIFIER { get; set; }
        public string PRODUCTNAME { get; set; }
    
        public virtual LANGUAGE LANGUAGE { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
