//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODATTRIBUTES
    {
        public int OID { get; set; }
        public int TID { get; set; }
        public int PRA_PRODUCTOID { get; set; }
        public int PRA_PRODUCTTID { get; set; }
        public int PRA_AOID { get; set; }
        public int PRA_ATID { get; set; }
        public int PRA_ATTRIBUTUMID { get; set; }
        public string PRA_NAME { get; set; }
        public Nullable<double> PRA_VALUE { get; set; }
        public Nullable<int> PRA_QUID { get; set; }
        public Nullable<double> PRA_PRICEMULTIPLIER { get; set; }
        public string PRA_PRMULTVALUEDEP { get; set; }
        public Nullable<int> PRA_PRICEREFPRODUCTOID { get; set; }
        public Nullable<int> PRA_PRICEREFPRODUCTTID { get; set; }
        public string PRA_ADDVALUEDEP { get; set; }
        public string PRA_NOTE { get; set; }
    
        public virtual PRODATTRIBUTENAMES PRODATTRIBUTENAMES { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual QUANTITY_UNIT QUANTITY_UNIT { get; set; }
    }
}
