//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROD_STIN_SERIAL
    {
        public Nullable<double> PSIS_C_QUANTITY { get; set; }
        public Nullable<int> PSIS_C_QUID { get; set; }
        public string PSIS_CONTROLLED { get; set; }
        public Nullable<int> PSIS_DETAIL_OID { get; set; }
        public Nullable<int> PSIS_DETAIL_TID { get; set; }
        public string PSIS_FORCE { get; set; }
        public Nullable<System.DateTime> PSIS_LIMITDAY { get; set; }
        public int PSIS_MASTER_OID { get; set; }
        public int PSIS_MASTER_TID { get; set; }
        public Nullable<double> PSIS_MB_QUANTITY { get; set; }
        public Nullable<int> PSIS_MB_QUID { get; set; }
        public Nullable<double> PSIS_MN_QUANTITY { get; set; }
        public Nullable<int> PSIS_MN_QUID { get; set; }
        public Nullable<int> PSIS_NOTICEOID { get; set; }
        public string PSIS_NUMTYPE { get; set; }
        public int OID { get; set; }
        public Nullable<int> PSIS_PFDIVISIONOID { get; set; }
        public Nullable<int> PSIS_PFDIVISIONTID { get; set; }
        public Nullable<int> PSIS_PRODUCTOID { get; set; }
        public Nullable<int> PSIS_PRODUCTTID { get; set; }
        public Nullable<double> PSIS_QUANTITY { get; set; }
        public Nullable<int> PSIS_QUID { get; set; }
        public string PSIS_SERIALNUMBER { get; set; }
        public Nullable<double> PSIS_STOCKQUANTITY { get; set; }
        public string PSIS_TAG { get; set; }
        public int TID { get; set; }
        public Nullable<double> PSIS_UNITPRICEBC { get; set; }
        public Nullable<double> PSIS_V_QUANTITY { get; set; }
        public Nullable<int> PSIS_V_QUID { get; set; }
    
        public virtual C_QUANTITY_UNIT C_QUANTITY_UNIT { get; set; }
        public virtual MB_QUANTITY_UNIT MB_QUANTITY_UNIT { get; set; }
        public virtual MN_QUANTITY_UNIT MN_QUANTITY_UNIT { get; set; }
        public virtual PFDIVISION PFDIVISION { get; set; }
        public virtual PROD_STIN PROD_STIN { get; set; }
        public virtual QUANTITY_UNIT QUANTITY_UNIT { get; set; }
        public virtual V_QUANTITY_UNIT V_QUANTITY_UNIT { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
