//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTCARDINALWEIGHTS
    {
        public int PCW_PRODUCTOID { get; set; }
        public int PCW_PRODUCTTID { get; set; }
        public int PCW_CARDQUID { get; set; }
        public Nullable<double> PCW_NETTO { get; set; }
        public Nullable<double> PCW_BRUTTO { get; set; }
        public Nullable<double> PCW_TARA { get; set; }
        public int PCW_WEIGHTQUID { get; set; }
    
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual QUANTITY_UNIT QUANTITY_UNIT { get; set; }
        public virtual QUANTITY_UNIT QUANTITY_UNIT1 { get; set; }
    }
}
