//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTION_DETAIL
    {
        public int OID { get; set; }
        public int TID { get; set; }
        public int PRD_PRODUCTIONOID { get; set; }
        public int PRD_PRODUCTIONTID { get; set; }
        public int PRD_PRODUCTOID { get; set; }
        public int PRD_PRODUCTTID { get; set; }
        public string PRD_CUSTOMCODE { get; set; }
        public double PRD_QUANTITY { get; set; }
        public Nullable<double> PRD_CQUANTITY { get; set; }
        public int PRD_NEGATIV { get; set; }
        public int PRD_QUID { get; set; }
        public double PRD_UNITPRICE { get; set; }
        public string PRD_CURRENCY { get; set; }
        public double PRD_CURRENCY_RATE { get; set; }
        public Nullable<double> PRD_UNITPRICEBC { get; set; }
        public double PRD_PRICEMULTIPLIER { get; set; }
        public Nullable<double> PRD_DISCOUNTPERCENT { get; set; }
        public Nullable<decimal> PRD_DISCOUNT { get; set; }
        public Nullable<decimal> PRD_NETTO { get; set; }
        public int PRD_TAXDEFID { get; set; }
        public Nullable<decimal> PRD_TAXVALUE { get; set; }
        public Nullable<decimal> PRD_BRUTTO { get; set; }
        public string PRD_DESCRIPTION { get; set; }
        public string PRD_CONTCODE { get; set; }
        public string PRD_TOLIST { get; set; }
        public Nullable<int> PRD_NOCUSTSUPPLIERID { get; set; }
    
        public virtual CURRENCY CURRENCY { get; set; }
        public virtual NOCUSTSUPPLIER NOCUSTSUPPLIER { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual PRODUCTION PRODUCTION { get; set; }
        public virtual QUANTITY_UNIT QUANTITY_UNIT { get; set; }
        public virtual TAXDEF TAXDEF { get; set; }
    }
}
