//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTRECORDTYPENAME
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCTRECORDTYPENAME()
        {
            this.DELIVERYOFFER_DETAIL = new HashSet<DELIVERYOFFER_DETAIL>();
            this.DELIVERYORDER_DETAIL = new HashSet<DELIVERYORDER_DETAIL>();
            this.O_INVOICEDETAIL = new HashSet<O_INVOICEDETAIL>();
            this.STORE_OUT_DETAIL = new HashSet<STORE_OUT_DETAIL>();
            this.PRODUCT = new HashSet<PRODUCT>();
        }
    
        public int PRTN_ID { get; set; }
        public string PRTN_NAME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DELIVERYOFFER_DETAIL> DELIVERYOFFER_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DELIVERYORDER_DETAIL> DELIVERYORDER_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<O_INVOICEDETAIL> O_INVOICEDETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STORE_OUT_DETAIL> STORE_OUT_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCT> PRODUCT { get; set; }
    }
}
