//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTION_STATIC
    {
        public int PS_PRODUCTION_STATICID { get; set; }
        public int PS_PRODUCTGROUPID { get; set; }
        public int PS_APPEARORDER { get; set; }
    
        public virtual PRODUCTGROUP PRODUCTGROUP { get; set; }
    }
}
