//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODDELIVERY_DETAIL
    {
        public int OID { get; set; }
        public int TID { get; set; }
        public int PDD_PRODDELIVERYOID { get; set; }
        public int PDD_PRODDELIVERYTID { get; set; }
        public Nullable<int> PDD_PRODUCTOID { get; set; }
        public Nullable<int> PDD_PRODUCTTID { get; set; }
        public string PDD_CUSTOMCODE { get; set; }
        public double PDD_QUANTITY { get; set; }
        public int PDD_NEGATIV { get; set; }
        public int PDD_QUID { get; set; }
        public double PDD_UNITPRICE { get; set; }
        public string PDD_CURRENCY { get; set; }
        public double PDD_CURRENCY_RATE { get; set; }
        public Nullable<double> PDD_UNITPRICEBC { get; set; }
        public Nullable<decimal> PDD_COSTPRICE { get; set; }
        public double PDD_PRICEMULTIPLIER { get; set; }
        public Nullable<double> PDD_DISCOUNTPERCENT { get; set; }
        public Nullable<decimal> PDD_DISCOUNT { get; set; }
        public Nullable<decimal> PDD_NETTO { get; set; }
        public int PDD_TAXDEFID { get; set; }
        public Nullable<decimal> PDD_TAXVALUE { get; set; }
        public Nullable<decimal> PDD_BRUTTO { get; set; }
        public Nullable<int> PDD_DETAILGROUP { get; set; }
        public string PDD_CUSTPRODUCTCODE { get; set; }
        public string PDD_DESCRIPTION { get; set; }
        public string PDD_TOLIST { get; set; }
        public Nullable<int> PDD_NOCUSTSUPPLIERID { get; set; }
        public Nullable<int> PDD_COSTCENTEROID { get; set; }
        public Nullable<int> PDD_COSTCENTERTID { get; set; }
        public Nullable<int> PDD_PROJECTOID { get; set; }
        public Nullable<int> PDD_PROJECTTID { get; set; }
    
        public virtual COSTCENTER COSTCENTER { get; set; }
        public virtual CURRENCY CURRENCY { get; set; }
        public virtual NOCUSTSUPPLIER NOCUSTSUPPLIER { get; set; }
        public virtual PRODDELIVERY PRODDELIVERY { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual PROJECT PROJECT { get; set; }
        public virtual QUANTITY_UNIT QUANTITY_UNIT { get; set; }
        public virtual TAXDEF TAXDEF { get; set; }
    }
}
