//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODREQUEST_METHOD
    {
        public int OID { get; set; }
        public int TID { get; set; }
        public int PRQM_PRODREQUESTOID { get; set; }
        public int PRQM_PRODREQUESTTID { get; set; }
        public int PRQM_PRODMETHODID { get; set; }
        public Nullable<int> PRQM_MULTIPLIER { get; set; }
    
        public virtual PRODMETHOD PRODMETHOD { get; set; }
        public virtual PRODREQUEST PRODREQUEST { get; set; }
    }
}
