//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODREQUEST_DETAIL
    {
        public int OID { get; set; }
        public int TID { get; set; }
        public int PRQD_PRODREQUESTOID { get; set; }
        public int PRQD_PRODREQUESTTID { get; set; }
        public Nullable<int> PRQD_PRODUCTOID { get; set; }
        public Nullable<int> PRQD_PRODUCTTID { get; set; }
        public string PRQD_CUSTOMCODE { get; set; }
        public double PRQD_QUANTITY { get; set; }
        public int PRQD_QUID { get; set; }
        public Nullable<double> PRQD_UNITPRICE { get; set; }
        public string PRQD_CURRENCY { get; set; }
        public Nullable<double> PRQD_CURRENCY_RATE { get; set; }
        public Nullable<double> PRQD_UNITPRICEBC { get; set; }
        public Nullable<double> PRQD_PRICEMULTIPLIER { get; set; }
        public Nullable<double> PRQD_DISCOUNTPERCENT { get; set; }
        public Nullable<decimal> PRQD_DISCOUNT { get; set; }
        public Nullable<decimal> PRQD_NETTO { get; set; }
        public Nullable<int> PRQD_TAXDEFID { get; set; }
        public Nullable<decimal> PRQD_TAXVALUE { get; set; }
        public Nullable<decimal> PRQD_BRUTTO { get; set; }
        public Nullable<int> PRQD_DETAILGROUP { get; set; }
        public string PRQD_AUTODISCOUNT { get; set; }
        public string PRQD_DESCRIPTION { get; set; }
        public string PRQD_CUSTPRODUCTCODE { get; set; }
        public Nullable<double> PRQD_STOCKQUANTITY { get; set; }
    
        public virtual CURRENCY CURRENCY { get; set; }
        public virtual PRODREQUEST PRODREQUEST { get; set; }
        public virtual QUANTITY_UNIT QUANTITY_UNIT { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual TAXDEF TAXDEF { get; set; }
    }
}
