//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODPRODUCT
    {
        public int OID { get; set; }
        public int TID { get; set; }
        public int PRDP_PHASEOID { get; set; }
        public int PRDP_PHASETID { get; set; }
        public int PRDP_PRODUCTOID { get; set; }
        public int PRDP_PRODUCTTID { get; set; }
        public string PRDP_RATIOTYPE { get; set; }
        public double PRDP_QUANTITY { get; set; }
        public Nullable<double> PRDP_STEPQNT { get; set; }
        public Nullable<double> PRDP_NORMALIZER { get; set; }
        public int PRDP_QUID { get; set; }
        public string PRDP_PROTYPE { get; set; }
        public string PRDP_CONDITION { get; set; }
    
        public virtual PRDPHASE PRDPHASE { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual QUANTITY_UNIT QUANTITY_UNIT { get; set; }
    }
}
