//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODEMPLOYEE
    {
        public int OID { get; set; }
        public int TID { get; set; }
        public Nullable<int> PRDE_PHASEOID { get; set; }
        public Nullable<int> PRDE_PHASETID { get; set; }
        public int PRDE_EMPLOYEEID { get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        public virtual PRDPHASE PRDPHASE { get; set; }
    }
}
