//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUANTITY_UNIT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QUANTITY_UNIT()
        {
            this.AGENTPREMIUMCONDITION = new HashSet<AGENTPREMIUMCONDITION>();
            this.AUDIT_INVENTORY_DETAIL = new HashSet<AUDIT_INVENTORY_DETAIL>();
            this.AUDIT_INVENTORY_DETAIL1 = new HashSet<AUDIT_INVENTORY_DETAIL>();
            this.AUDIT_INVENTORY_DETAIL2 = new HashSet<AUDIT_INVENTORY_DETAIL>();
            this.AUDIT_INVENTORY_DETAIL3 = new HashSet<AUDIT_INVENTORY_DETAIL>();
            this.AUDIT_INVENTORY_DETAIL4 = new HashSet<AUDIT_INVENTORY_DETAIL>();
            this.AVISO_DETAIL = new HashSet<AVISO_DETAIL>();
            this.BOOKCONT = new HashSet<BOOKCONT>();
            this.BOOKPOST = new HashSet<BOOKPOST>();
            this.BOOKSTOCK = new HashSet<BOOKSTOCK>();
            this.BOOKSTOCKSH = new HashSet<BOOKSTOCKSH>();
            this.BUYUP_DETAIL = new HashSet<BUYUP_DETAIL>();
            this.BUYUP_DETAIL_ALT = new HashSet<BUYUP_DETAIL_ALT>();
            this.BUYUP_SUMDETAIL = new HashSet<BUYUP_SUMDETAIL>();
            this.CONSIGNMENT_IN_DETAIL = new HashSet<CONSIGNMENT_IN_DETAIL>();
            this.CONSIGNMENT_IN_SERIAL = new HashSet<CONSIGNMENT_IN_SERIAL>();
            this.CONSIGNMENT_OUT_DETAIL = new HashSet<CONSIGNMENT_OUT_DETAIL>();
            this.CONSIGNMENT_OUT_SERIAL = new HashSet<CONSIGNMENT_OUT_SERIAL>();
            this.CONSIGNMENTREPORT_DETAIL = new HashSet<CONSIGNMENTREPORT_DETAIL>();
            this.CONSIGNMENTREPORT_SERIAL = new HashSet<CONSIGNMENTREPORT_SERIAL>();
            this.CUSTOMDOC_DETAIL = new HashSet<CUSTOMDOC_DETAIL>();
            this.CUSTPRODUCTCODE = new HashSet<CUSTPRODUCTCODE>();
            this.CUSTPRODUCTCODE1 = new HashSet<CUSTPRODUCTCODE>();
            this.DELIVERYCONTRACT_DETAIL = new HashSet<DELIVERYCONTRACT_DETAIL>();
            this.DELIVERYOFFER_DETAIL = new HashSet<DELIVERYOFFER_DETAIL>();
            this.DELIVERYORDER_DETAIL = new HashSet<DELIVERYORDER_DETAIL>();
            this.DELIVERYORDER_EXPANDED = new HashSet<DELIVERYORDER_EXPANDED>();
            this.DELIVERYORDERMOD_DETAIL = new HashSet<DELIVERYORDERMOD_DETAIL>();
            this.DELIVERYORDERMOD_EXPANDED = new HashSet<DELIVERYORDERMOD_EXPANDED>();
            this.DIRECTBUY_DETAIL = new HashSet<DIRECTBUY_DETAIL>();
            this.DIRECTSELL_DETAIL = new HashSet<DIRECTSELL_DETAIL>();
            this.DISCOUNTCONDITION = new HashSet<DISCOUNTCONDITION>();
            this.DPI_INVOICEDETAIL = new HashSet<DPI_INVOICEDETAIL>();
            this.DPI_TAXDETAIL = new HashSet<DPI_TAXDETAIL>();
            this.DPO_INVOICEDETAIL = new HashSet<DPO_INVOICEDETAIL>();
            this.DPO_TAXDETAIL = new HashSet<DPO_TAXDETAIL>();
            this.GADFILEMOD_POST = new HashSet<GADFILEMOD_POST>();
            this.GADNEWGAD_DETAIL = new HashSet<GADNEWGAD_DETAIL>();
            this.GADNEWGAD_INVEST = new HashSet<GADNEWGAD_INVEST>();
            this.GADNEWGAD_SERIAL = new HashSet<GADNEWGAD_SERIAL>();
            this.GENPROD_REQUEST = new HashSet<GENPROD_REQUEST>();
            this.GENPROD_STOCK = new HashSet<GENPROD_STOCK>();
            this.I_INVOICEDETAIL = new HashSet<I_INVOICEDETAIL>();
            this.INVENTORY_DETAIL = new HashSet<INVENTORY_DETAIL>();
            this.INVENTORY_GAP_DETAIL = new HashSet<INVENTORY_GAP_DETAIL>();
            this.INVENTORY_GAP_SERIAL = new HashSet<INVENTORY_GAP_SERIAL>();
            this.INVENTORY_SERIAL = new HashSet<INVENTORY_SERIAL>();
            this.JUNK_DETAIL = new HashSet<JUNK_DETAIL>();
            this.JUNK_SERIAL = new HashSet<JUNK_SERIAL>();
            this.JUSTWAYBILL_DETAIL = new HashSet<JUSTWAYBILL_DETAIL>();
            this.JUSTWAYBILL_SERIAL = new HashSet<JUSTWAYBILL_SERIAL>();
            this.KOMISSIO_DETAIL = new HashSet<KOMISSIO_DETAIL>();
            this.KOMISSIOMOD_INDETAIL = new HashSet<KOMISSIOMOD_INDETAIL>();
            this.KOMISSIOMOD_OUTDETAIL = new HashSet<KOMISSIOMOD_OUTDETAIL>();
            this.LEASECONTRACT_SERVICE = new HashSet<LEASECONTRACT_SERVICE>();
            this.LEASECONTRACTBACK_DEFICIENCY = new HashSet<LEASECONTRACTBACK_DEFICIENCY>();
            this.LEASECONTRACTBACK_SERVICE = new HashSet<LEASECONTRACTBACK_SERVICE>();
            this.LOADDIVISION = new HashSet<LOADDIVISION>();
            this.LOADDIVISION_DETAIL = new HashSet<LOADDIVISION_DETAIL>();
            this.MARKETREGISTER_DETAIL = new HashSet<MARKETREGISTER_DETAIL>();
            this.MEOPARAMNAME = new HashSet<MEOPARAMNAME>();
            this.MEOVALUE = new HashSet<MEOVALUE>();
            this.MOVESTOCK_IN_DETAIL = new HashSet<MOVESTOCK_IN_DETAIL>();
            this.MOVESTOCK_IN_SERIAL = new HashSet<MOVESTOCK_IN_SERIAL>();
            this.MOVESTOCK_OUT_DETAIL = new HashSet<MOVESTOCK_OUT_DETAIL>();
            this.MOVESTOCK_OUT_SERIAL = new HashSet<MOVESTOCK_OUT_SERIAL>();
            this.NOTIFIER_DETAIL = new HashSet<NOTIFIER_DETAIL>();
            this.O_INVOICEDETAIL = new HashSet<O_INVOICEDETAIL>();
            this.OPTIONEDMOD_DETAIL = new HashSet<OPTIONEDMOD_DETAIL>();
            this.OPTIONEDMOD_EXPANDED = new HashSet<OPTIONEDMOD_EXPANDED>();
            this.PACKING_DETAIL = new HashSet<PACKING_DETAIL>();
            this.PACKING_DONEDETAIL = new HashSet<PACKING_DONEDETAIL>();
            this.PACKING_DONESERIAL = new HashSet<PACKING_DONESERIAL>();
            this.PACKING_SERIAL = new HashSet<PACKING_SERIAL>();
            this.PACKINGWORK_PRODUCTS = new HashSet<PACKINGWORK_PRODUCTS>();
            this.PC_ALLOCATION = new HashSet<PC_ALLOCATION>();
            this.PC_BASEPRCOST = new HashSet<PC_BASEPRCOST>();
            this.PC_COLLDEF = new HashSet<PC_COLLDEF>();
            this.PC_MANUFACTURE = new HashSet<PC_MANUFACTURE>();
            this.PC_MANUMOVE_IN_DETAIL = new HashSet<PC_MANUMOVE_IN_DETAIL>();
            this.PC_MANUMOVE_IN_SERIAL_FROM = new HashSet<PC_MANUMOVE_IN_SERIAL_FROM>();
            this.PC_MANUMOVE_IN_SERIAL_TO = new HashSet<PC_MANUMOVE_IN_SERIAL_TO>();
            this.PC_MANUMOVE_OUT_DETAIL = new HashSet<PC_MANUMOVE_OUT_DETAIL>();
            this.PC_MANUMOVE_OUT_SERIAL_FROM = new HashSet<PC_MANUMOVE_OUT_SERIAL_FROM>();
            this.PC_MANUMOVE_OUT_SERIAL_TO = new HashSet<PC_MANUMOVE_OUT_SERIAL_TO>();
            this.PC_MATUREINFLUENCED = new HashSet<PC_MATUREINFLUENCED>();
            this.PC_OFFERVARIATION_PLIST = new HashSet<PC_OFFERVARIATION_PLIST>();
            this.PC_OPBASEMATERIALDEMAND = new HashSet<PC_OPBASEMATERIALDEMAND>();
            this.PC_OPERATIONSHEET_PROD_DETAIL = new HashSet<PC_OPERATIONSHEET_PROD_DETAIL>();
            this.PC_OPERATIONSHEET_PROD_SERIAL = new HashSet<PC_OPERATIONSHEET_PROD_SERIAL>();
            this.PC_OPERATIONSHEET_USED_DETAIL = new HashSet<PC_OPERATIONSHEET_USED_DETAIL>();
            this.PC_OPERATIONSHEET_USED_SERIAL = new HashSet<PC_OPERATIONSHEET_USED_SERIAL>();
            this.PC_OPFINALPRODUCT = new HashSet<PC_OPFINALPRODUCT>();
            this.PC_PLAN_DETAIL = new HashSet<PC_PLAN_DETAIL>();
            this.PC_PLIST = new HashSet<PC_PLIST>();
            this.PC_PRODUCEDPRODUCTS = new HashSet<PC_PRODUCEDPRODUCTS>();
            this.PC_PRODUCT_PREVIOUS_PRICE = new HashSet<PC_PRODUCT_PREVIOUS_PRICE>();
            this.PC_PROTOOLTECHNICALINFO = new HashSet<PC_PROTOOLTECHNICALINFO>();
            this.PC_PROTOOLTECHNICALINFODEF = new HashSet<PC_PROTOOLTECHNICALINFODEF>();
            this.PC_SUBSTATE_COST = new HashSet<PC_SUBSTATE_COST>();
            this.PC_TECHINSTRUCTIONPLIST = new HashSet<PC_TECHINSTRUCTIONPLIST>();
            this.PFTAGCAPACITY = new HashSet<PFTAGCAPACITY>();
            this.PM_ATTRIBUTES = new HashSet<PM_ATTRIBUTES>();
            this.POTENTIAL_STOCKINFO_QUANTITY_UNIT = new HashSet<POTENTIAL_STOCKINFO_QUANTITY_UNIT>();
            this.POTENTIAL_STOCKINFO_STOCK = new HashSet<POTENTIAL_STOCKINFO_STOCK>();
            this.POTENTIAL_STOCKINFO_WORK = new HashSet<POTENTIAL_STOCKINFO_WORK>();
            this.PR_PARCELS = new HashSet<PR_PARCELS>();
            this.PRMDONEPROD = new HashSet<PRMDONEPROD>();
            this.PRMPROD = new HashSet<PRMPROD>();
            this.PROD_STIN_DETAIL = new HashSet<PROD_STIN_DETAIL>();
            this.PROD_STIN_SERIAL = new HashSet<PROD_STIN_SERIAL>();
            this.PROD_STOUT_DETAIL = new HashSet<PROD_STOUT_DETAIL>();
            this.PROD_STOUT_SERIAL = new HashSet<PROD_STOUT_SERIAL>();
            this.PRODATTRIBUTEDEFS = new HashSet<PRODATTRIBUTEDEFS>();
            this.PRODATTRIBUTES = new HashSet<PRODATTRIBUTES>();
            this.PRODBAR_DETAIL = new HashSet<PRODBAR_DETAIL>();
            this.PRODDELIVERY_DETAIL = new HashSet<PRODDELIVERY_DETAIL>();
            this.PRODPRODUCT = new HashSet<PRODPRODUCT>();
            this.PRODREQUEST_DETAIL = new HashSet<PRODREQUEST_DETAIL>();
            this.PRODRESOURCE = new HashSet<PRODRESOURCE>();
            this.PRODUCT = new HashSet<PRODUCT>();
            this.PRODUCT1 = new HashSet<PRODUCT>();
            this.PRODUCT2 = new HashSet<PRODUCT>();
            this.PRODUCT3 = new HashSet<PRODUCT>();
            this.PRODUCT_STOREINFO = new HashSet<PRODUCT_STOREINFO>();
            this.PRODUCT_STOREINFO1 = new HashSet<PRODUCT_STOREINFO>();
            this.PRODUCT_STOREINFO2 = new HashSet<PRODUCT_STOREINFO>();
            this.PRODUCT_STOREINFO3 = new HashSet<PRODUCT_STOREINFO>();
            this.PRODUCT_STOREINFO4 = new HashSet<PRODUCT_STOREINFO>();
            this.PRODUCTCARDINALWEIGHTS = new HashSet<PRODUCTCARDINALWEIGHTS>();
            this.PRODUCTCARDINALWEIGHTS1 = new HashSet<PRODUCTCARDINALWEIGHTS>();
            this.PRODUCTION_DETAIL = new HashSet<PRODUCTION_DETAIL>();
            this.PRODUCTION_SERIAL = new HashSet<PRODUCTION_SERIAL>();
            this.PRODUCTQRATES = new HashSet<PRODUCTQRATES>();
            this.QPSTORSTRAT_ITEMS = new HashSet<QPSTORSTRAT_ITEMS>();
            this.AVAILABLESTOCKLOG = new HashSet<AVAILABLESTOCKLOG>();
            this.REFERREDQUC = new HashSet<REFERREDQUC>();
            this.REFERREDQUC1 = new HashSet<REFERREDQUC>();
            this.REPAIR_DETAIL = new HashSet<REPAIR_DETAIL>();
            this.REPAIRBACK_DETAIL_ALT = new HashSet<REPAIRBACK_DETAIL_ALT>();
            this.REPAIRBACK_DETAIL = new HashSet<REPAIRBACK_DETAIL>();
            this.RETREIVEANAL_DETAIL = new HashSet<RETREIVEANAL_DETAIL>();
            this.RETREIVECHANGE_DETAIL_ALT = new HashSet<RETREIVECHANGE_DETAIL_ALT>();
            this.RETREIVECHANGE_DETAIL = new HashSet<RETREIVECHANGE_DETAIL>();
            this.RETURNED_DETAIL = new HashSet<RETURNED_DETAIL>();
            this.RETURNEDCHANGE_DETAIL_ALT = new HashSet<RETURNEDCHANGE_DETAIL_ALT>();
            this.RETURNEDCHANGE_DETAIL = new HashSet<RETURNEDCHANGE_DETAIL>();
            this.SCALINGCONFIRMATION_DETAIL = new HashSet<SCALINGCONFIRMATION_DETAIL>();
            this.SERVICE_OPERATIONSET_OPERATION = new HashSet<SERVICE_OPERATIONSET_OPERATION>();
            this.SERVICE_OPERATIONSET_PRODUCT = new HashSet<SERVICE_OPERATIONSET_PRODUCT>();
            this.SERVICEASSET_ADDITION = new HashSet<SERVICEASSET_ADDITION>();
            this.SERVICECONTRACT_COST = new HashSet<SERVICECONTRACT_COST>();
            this.SERVICESHEET_ACCESSORY = new HashSet<SERVICESHEET_ACCESSORY>();
            this.SERVICESHEET_ACCESSORY1 = new HashSet<SERVICESHEET_ACCESSORY>();
            this.SERVICESHEET_OPERATION = new HashSet<SERVICESHEET_OPERATION>();
            this.SERVICESHEET_PRODUCT = new HashSet<SERVICESHEET_PRODUCT>();
            this.STOCKKEEPERREPORT_DETAIL = new HashSet<STOCKKEEPERREPORT_DETAIL>();
            this.STORE_IN_DETAIL = new HashSet<STORE_IN_DETAIL>();
            this.STORE_IN_DETAIL1 = new HashSet<STORE_IN_DETAIL>();
            this.STORE_OUT_DETAIL = new HashSet<STORE_OUT_DETAIL>();
            this.STORE_OUT_DETAIL1 = new HashSet<STORE_OUT_DETAIL>();
            this.SUPPLYOFFER_DETAIL = new HashSet<SUPPLYOFFER_DETAIL>();
            this.SUPPLYORDER_DETAIL = new HashSet<SUPPLYORDER_DETAIL>();
            this.TAGCHANGE_DETAIL = new HashSet<TAGCHANGE_DETAIL>();
            this.THEORETICAL_INVENTORY_DETAIL = new HashSet<THEORETICAL_INVENTORY_DETAIL>();
            this.TOOLACCESSORY = new HashSet<TOOLACCESSORY>();
            this.TOOLACCESSORY1 = new HashSet<TOOLACCESSORY>();
            this.TOOLADDITION = new HashSet<TOOLADDITION>();
            this.TOOLBENCH = new HashSet<TOOLBENCH>();
            this.TOOLCONTRACT_COST = new HashSet<TOOLCONTRACT_COST>();
            this.TOOLINPUT = new HashSet<TOOLINPUT>();
            this.TOOLMAKECONTRACT_COST = new HashSet<TOOLMAKECONTRACT_COST>();
            this.TOOLTRAVELLING_DETAIL = new HashSet<TOOLTRAVELLING_DETAIL>();
            this.TOOLTRAVELS = new HashSet<TOOLTRAVELS>();
            this.VANLINEPASS_DETAIL = new HashSet<VANLINEPASS_DETAIL>();
            this.WAYBILL_DETAIL = new HashSet<WAYBILL_DETAIL>();
            this.QUANTITY_UNIT1 = new HashSet<QUANTITY_UNIT>();
            this.QUSPECRATE = new HashSet<QUSPECRATE>();
            this.QUSPECRATE1 = new HashSet<QUSPECRATE>();
            this.RECEIPT_DETAIL = new HashSet<RECEIPT_DETAIL>();
            this.SERIALWORK = new HashSet<SERIALWORK>();
            this.SERIALWORK1 = new HashSet<SERIALWORK>();
            this.SERIALWORK2 = new HashSet<SERIALWORK>();
            this.SERIALWORK3 = new HashSet<SERIALWORK>();
            this.SUPPLIERENABLE = new HashSet<SUPPLIERENABLE>();
            this.SUPPLIERENABLE1 = new HashSet<SUPPLIERENABLE>();
            this.SUPPLYOFFER_REQUEST = new HashSet<SUPPLYOFFER_REQUEST>();
            this.SUPPLYORDER_REQUEST = new HashSet<SUPPLYORDER_REQUEST>();
            this.SUPPLYORDERMOD_DETAIL = new HashSet<SUPPLYORDERMOD_DETAIL>();
            this.VANLINEPASS_SERIAL = new HashSet<VANLINEPASS_SERIAL>();
            this.STORE_IN_SERIAL = new HashSet<STORE_IN_SERIAL>();
            this.STORE_OUT_SERIAL = new HashSet<STORE_OUT_SERIAL>();
            this.STORE_IN_SERIAL1 = new HashSet<STORE_IN_SERIAL>();
            this.STORE_OUT_SERIAL1 = new HashSet<STORE_OUT_SERIAL>();
            this.THEORETICAL_INVENTORY_SERIAL = new HashSet<THEORETICAL_INVENTORY_SERIAL>();
            this.TEMP_SERIAL = new HashSet<TEMP_SERIAL>();
            this.STOCKMOD_DETAIL = new HashSet<STOCKMOD_DETAIL>();
            this.TAGCHANGE_SRC_SERIAL = new HashSet<TAGCHANGE_SRC_SERIAL>();
            this.TAGCHANGE_DST_SERIAL = new HashSet<TAGCHANGE_DST_SERIAL>();
            this.RETREIVEANAL_SERIAL = new HashSet<RETREIVEANAL_SERIAL>();
            this.SERIALWORK4 = new HashSet<SERIALWORK>();
            this.RETREIVECHANGE_SERIAL = new HashSet<RETREIVECHANGE_SERIAL>();
            this.RETURNED_SERIAL = new HashSet<RETURNED_SERIAL>();
            this.RETURNEDCHANGE_SERIAL = new HashSet<RETURNEDCHANGE_SERIAL>();
            this.REPAIR_SERIAL = new HashSet<REPAIR_SERIAL>();
            this.REPAIRBACK_SERIAL = new HashSet<REPAIRBACK_SERIAL>();
            this.SUPPLYORDER_EXPANDED = new HashSet<SUPPLYORDER_EXPANDED>();
            this.SUPPLYORDERMOD_EXPANDED = new HashSet<SUPPLYORDERMOD_EXPANDED>();
            this.UNONTHEWAY_EXPANDED = new HashSet<UNONTHEWAY_EXPANDED>();
            this.UNOPTIONED_EXPANDED = new HashSet<UNOPTIONED_EXPANDED>();
            this.UNONTHEWAY_DETAIL = new HashSet<UNONTHEWAY_DETAIL>();
            this.UNOPTIONED_DETAIL = new HashSet<UNOPTIONED_DETAIL>();
            this.VEHICLE = new HashSet<VEHICLE>();
        }
    
        public int QUID { get; set; }
        public string QUNAME { get; set; }
        public string QU_TYPE { get; set; }
        public int QU_BASE { get; set; }
        public double QU_RATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AGENTPREMIUMCONDITION> AGENTPREMIUMCONDITION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AUDIT_INVENTORY_DETAIL> AUDIT_INVENTORY_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AUDIT_INVENTORY_DETAIL> AUDIT_INVENTORY_DETAIL1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AUDIT_INVENTORY_DETAIL> AUDIT_INVENTORY_DETAIL2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AUDIT_INVENTORY_DETAIL> AUDIT_INVENTORY_DETAIL3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AUDIT_INVENTORY_DETAIL> AUDIT_INVENTORY_DETAIL4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AVISO_DETAIL> AVISO_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOOKCONT> BOOKCONT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOOKPOST> BOOKPOST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOOKSTOCK> BOOKSTOCK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOOKSTOCKSH> BOOKSTOCKSH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BUYUP_DETAIL> BUYUP_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BUYUP_DETAIL_ALT> BUYUP_DETAIL_ALT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BUYUP_SUMDETAIL> BUYUP_SUMDETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONSIGNMENT_IN_DETAIL> CONSIGNMENT_IN_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONSIGNMENT_IN_SERIAL> CONSIGNMENT_IN_SERIAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONSIGNMENT_OUT_DETAIL> CONSIGNMENT_OUT_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONSIGNMENT_OUT_SERIAL> CONSIGNMENT_OUT_SERIAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONSIGNMENTREPORT_DETAIL> CONSIGNMENTREPORT_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONSIGNMENTREPORT_SERIAL> CONSIGNMENTREPORT_SERIAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUSTOMDOC_DETAIL> CUSTOMDOC_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUSTPRODUCTCODE> CUSTPRODUCTCODE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUSTPRODUCTCODE> CUSTPRODUCTCODE1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DELIVERYCONTRACT_DETAIL> DELIVERYCONTRACT_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DELIVERYOFFER_DETAIL> DELIVERYOFFER_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DELIVERYORDER_DETAIL> DELIVERYORDER_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DELIVERYORDER_EXPANDED> DELIVERYORDER_EXPANDED { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DELIVERYORDERMOD_DETAIL> DELIVERYORDERMOD_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DELIVERYORDERMOD_EXPANDED> DELIVERYORDERMOD_EXPANDED { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DIRECTBUY_DETAIL> DIRECTBUY_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DIRECTSELL_DETAIL> DIRECTSELL_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DISCOUNTCONDITION> DISCOUNTCONDITION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DPI_INVOICEDETAIL> DPI_INVOICEDETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DPI_TAXDETAIL> DPI_TAXDETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DPO_INVOICEDETAIL> DPO_INVOICEDETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DPO_TAXDETAIL> DPO_TAXDETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GADFILEMOD_POST> GADFILEMOD_POST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GADNEWGAD_DETAIL> GADNEWGAD_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GADNEWGAD_INVEST> GADNEWGAD_INVEST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GADNEWGAD_SERIAL> GADNEWGAD_SERIAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GENPROD_REQUEST> GENPROD_REQUEST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GENPROD_STOCK> GENPROD_STOCK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_INVOICEDETAIL> I_INVOICEDETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INVENTORY_DETAIL> INVENTORY_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INVENTORY_GAP_DETAIL> INVENTORY_GAP_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INVENTORY_GAP_SERIAL> INVENTORY_GAP_SERIAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INVENTORY_SERIAL> INVENTORY_SERIAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JUNK_DETAIL> JUNK_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JUNK_SERIAL> JUNK_SERIAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JUSTWAYBILL_DETAIL> JUSTWAYBILL_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JUSTWAYBILL_SERIAL> JUSTWAYBILL_SERIAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KOMISSIO_DETAIL> KOMISSIO_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KOMISSIOMOD_INDETAIL> KOMISSIOMOD_INDETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KOMISSIOMOD_OUTDETAIL> KOMISSIOMOD_OUTDETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LEASECONTRACT_SERVICE> LEASECONTRACT_SERVICE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LEASECONTRACTBACK_DEFICIENCY> LEASECONTRACTBACK_DEFICIENCY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LEASECONTRACTBACK_SERVICE> LEASECONTRACTBACK_SERVICE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOADDIVISION> LOADDIVISION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOADDIVISION_DETAIL> LOADDIVISION_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MARKETREGISTER_DETAIL> MARKETREGISTER_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MEOPARAMNAME> MEOPARAMNAME { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MEOVALUE> MEOVALUE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MOVESTOCK_IN_DETAIL> MOVESTOCK_IN_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MOVESTOCK_IN_SERIAL> MOVESTOCK_IN_SERIAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MOVESTOCK_OUT_DETAIL> MOVESTOCK_OUT_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MOVESTOCK_OUT_SERIAL> MOVESTOCK_OUT_SERIAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NOTIFIER_DETAIL> NOTIFIER_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<O_INVOICEDETAIL> O_INVOICEDETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OPTIONEDMOD_DETAIL> OPTIONEDMOD_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OPTIONEDMOD_EXPANDED> OPTIONEDMOD_EXPANDED { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PACKING_DETAIL> PACKING_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PACKING_DONEDETAIL> PACKING_DONEDETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PACKING_DONESERIAL> PACKING_DONESERIAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PACKING_SERIAL> PACKING_SERIAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PACKINGWORK_PRODUCTS> PACKINGWORK_PRODUCTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PC_ALLOCATION> PC_ALLOCATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PC_BASEPRCOST> PC_BASEPRCOST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PC_COLLDEF> PC_COLLDEF { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PC_MANUFACTURE> PC_MANUFACTURE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PC_MANUMOVE_IN_DETAIL> PC_MANUMOVE_IN_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PC_MANUMOVE_IN_SERIAL_FROM> PC_MANUMOVE_IN_SERIAL_FROM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PC_MANUMOVE_IN_SERIAL_TO> PC_MANUMOVE_IN_SERIAL_TO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PC_MANUMOVE_OUT_DETAIL> PC_MANUMOVE_OUT_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PC_MANUMOVE_OUT_SERIAL_FROM> PC_MANUMOVE_OUT_SERIAL_FROM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PC_MANUMOVE_OUT_SERIAL_TO> PC_MANUMOVE_OUT_SERIAL_TO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PC_MATUREINFLUENCED> PC_MATUREINFLUENCED { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PC_OFFERVARIATION_PLIST> PC_OFFERVARIATION_PLIST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PC_OPBASEMATERIALDEMAND> PC_OPBASEMATERIALDEMAND { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PC_OPERATIONSHEET_PROD_DETAIL> PC_OPERATIONSHEET_PROD_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PC_OPERATIONSHEET_PROD_SERIAL> PC_OPERATIONSHEET_PROD_SERIAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PC_OPERATIONSHEET_USED_DETAIL> PC_OPERATIONSHEET_USED_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PC_OPERATIONSHEET_USED_SERIAL> PC_OPERATIONSHEET_USED_SERIAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PC_OPFINALPRODUCT> PC_OPFINALPRODUCT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PC_PLAN_DETAIL> PC_PLAN_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PC_PLIST> PC_PLIST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PC_PRODUCEDPRODUCTS> PC_PRODUCEDPRODUCTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PC_PRODUCT_PREVIOUS_PRICE> PC_PRODUCT_PREVIOUS_PRICE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PC_PROTOOLTECHNICALINFO> PC_PROTOOLTECHNICALINFO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PC_PROTOOLTECHNICALINFODEF> PC_PROTOOLTECHNICALINFODEF { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PC_SUBSTATE_COST> PC_SUBSTATE_COST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PC_TECHINSTRUCTIONPLIST> PC_TECHINSTRUCTIONPLIST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PFTAGCAPACITY> PFTAGCAPACITY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PM_ATTRIBUTES> PM_ATTRIBUTES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POTENTIAL_STOCKINFO_QUANTITY_UNIT> POTENTIAL_STOCKINFO_QUANTITY_UNIT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POTENTIAL_STOCKINFO_STOCK> POTENTIAL_STOCKINFO_STOCK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POTENTIAL_STOCKINFO_WORK> POTENTIAL_STOCKINFO_WORK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PR_PARCELS> PR_PARCELS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRMDONEPROD> PRMDONEPROD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRMPROD> PRMPROD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROD_STIN_DETAIL> PROD_STIN_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROD_STIN_SERIAL> PROD_STIN_SERIAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROD_STOUT_DETAIL> PROD_STOUT_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROD_STOUT_SERIAL> PROD_STOUT_SERIAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODATTRIBUTEDEFS> PRODATTRIBUTEDEFS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODATTRIBUTES> PRODATTRIBUTES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODBAR_DETAIL> PRODBAR_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODDELIVERY_DETAIL> PRODDELIVERY_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODPRODUCT> PRODPRODUCT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODREQUEST_DETAIL> PRODREQUEST_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODRESOURCE> PRODRESOURCE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCT> PRODUCT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCT> PRODUCT1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCT> PRODUCT2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCT> PRODUCT3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCT_STOREINFO> PRODUCT_STOREINFO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCT_STOREINFO> PRODUCT_STOREINFO1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCT_STOREINFO> PRODUCT_STOREINFO2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCT_STOREINFO> PRODUCT_STOREINFO3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCT_STOREINFO> PRODUCT_STOREINFO4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCTCARDINALWEIGHTS> PRODUCTCARDINALWEIGHTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCTCARDINALWEIGHTS> PRODUCTCARDINALWEIGHTS1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCTION_DETAIL> PRODUCTION_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCTION_SERIAL> PRODUCTION_SERIAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCTQRATES> PRODUCTQRATES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QPSTORSTRAT_ITEMS> QPSTORSTRAT_ITEMS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AVAILABLESTOCKLOG> AVAILABLESTOCKLOG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REFERREDQUC> REFERREDQUC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REFERREDQUC> REFERREDQUC1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REPAIR_DETAIL> REPAIR_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REPAIRBACK_DETAIL_ALT> REPAIRBACK_DETAIL_ALT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REPAIRBACK_DETAIL> REPAIRBACK_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RETREIVEANAL_DETAIL> RETREIVEANAL_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RETREIVECHANGE_DETAIL_ALT> RETREIVECHANGE_DETAIL_ALT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RETREIVECHANGE_DETAIL> RETREIVECHANGE_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RETURNED_DETAIL> RETURNED_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RETURNEDCHANGE_DETAIL_ALT> RETURNEDCHANGE_DETAIL_ALT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RETURNEDCHANGE_DETAIL> RETURNEDCHANGE_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SCALINGCONFIRMATION_DETAIL> SCALINGCONFIRMATION_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SERVICE_OPERATIONSET_OPERATION> SERVICE_OPERATIONSET_OPERATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SERVICE_OPERATIONSET_PRODUCT> SERVICE_OPERATIONSET_PRODUCT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SERVICEASSET_ADDITION> SERVICEASSET_ADDITION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SERVICECONTRACT_COST> SERVICECONTRACT_COST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SERVICESHEET_ACCESSORY> SERVICESHEET_ACCESSORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SERVICESHEET_ACCESSORY> SERVICESHEET_ACCESSORY1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SERVICESHEET_OPERATION> SERVICESHEET_OPERATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SERVICESHEET_PRODUCT> SERVICESHEET_PRODUCT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STOCKKEEPERREPORT_DETAIL> STOCKKEEPERREPORT_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STORE_IN_DETAIL> STORE_IN_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STORE_IN_DETAIL> STORE_IN_DETAIL1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STORE_OUT_DETAIL> STORE_OUT_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STORE_OUT_DETAIL> STORE_OUT_DETAIL1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUPPLYOFFER_DETAIL> SUPPLYOFFER_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUPPLYORDER_DETAIL> SUPPLYORDER_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAGCHANGE_DETAIL> TAGCHANGE_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THEORETICAL_INVENTORY_DETAIL> THEORETICAL_INVENTORY_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TOOLACCESSORY> TOOLACCESSORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TOOLACCESSORY> TOOLACCESSORY1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TOOLADDITION> TOOLADDITION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TOOLBENCH> TOOLBENCH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TOOLCONTRACT_COST> TOOLCONTRACT_COST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TOOLINPUT> TOOLINPUT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TOOLMAKECONTRACT_COST> TOOLMAKECONTRACT_COST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TOOLTRAVELLING_DETAIL> TOOLTRAVELLING_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TOOLTRAVELS> TOOLTRAVELS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VANLINEPASS_DETAIL> VANLINEPASS_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WAYBILL_DETAIL> WAYBILL_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QUANTITY_UNIT> QUANTITY_UNIT1 { get; set; }
        public virtual QUANTITY_UNIT QUANTITY_UNIT2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QUSPECRATE> QUSPECRATE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QUSPECRATE> QUSPECRATE1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RECEIPT_DETAIL> RECEIPT_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SERIALWORK> SERIALWORK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SERIALWORK> SERIALWORK1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SERIALWORK> SERIALWORK2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SERIALWORK> SERIALWORK3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUPPLIERENABLE> SUPPLIERENABLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUPPLIERENABLE> SUPPLIERENABLE1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUPPLYOFFER_REQUEST> SUPPLYOFFER_REQUEST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUPPLYORDER_REQUEST> SUPPLYORDER_REQUEST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUPPLYORDERMOD_DETAIL> SUPPLYORDERMOD_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VANLINEPASS_SERIAL> VANLINEPASS_SERIAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STORE_IN_SERIAL> STORE_IN_SERIAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STORE_OUT_SERIAL> STORE_OUT_SERIAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STORE_IN_SERIAL> STORE_IN_SERIAL1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STORE_OUT_SERIAL> STORE_OUT_SERIAL1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THEORETICAL_INVENTORY_SERIAL> THEORETICAL_INVENTORY_SERIAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEMP_SERIAL> TEMP_SERIAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STOCKMOD_DETAIL> STOCKMOD_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAGCHANGE_SRC_SERIAL> TAGCHANGE_SRC_SERIAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAGCHANGE_DST_SERIAL> TAGCHANGE_DST_SERIAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RETREIVEANAL_SERIAL> RETREIVEANAL_SERIAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SERIALWORK> SERIALWORK4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RETREIVECHANGE_SERIAL> RETREIVECHANGE_SERIAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RETURNED_SERIAL> RETURNED_SERIAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RETURNEDCHANGE_SERIAL> RETURNEDCHANGE_SERIAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REPAIR_SERIAL> REPAIR_SERIAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REPAIRBACK_SERIAL> REPAIRBACK_SERIAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUPPLYORDER_EXPANDED> SUPPLYORDER_EXPANDED { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUPPLYORDERMOD_EXPANDED> SUPPLYORDERMOD_EXPANDED { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UNONTHEWAY_EXPANDED> UNONTHEWAY_EXPANDED { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UNOPTIONED_EXPANDED> UNOPTIONED_EXPANDED { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UNONTHEWAY_DETAIL> UNONTHEWAY_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UNOPTIONED_DETAIL> UNOPTIONED_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VEHICLE> VEHICLE { get; set; }
    }
}
