//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECEIPT_DETAIL
    {
        public int OID { get; set; }
        public int TID { get; set; }
        public int RCD_RECEIPTOID { get; set; }
        public int RCD_RECEIPTTID { get; set; }
        public Nullable<int> RCD_PRODUCTOID { get; set; }
        public Nullable<int> RCD_PRODUCTTID { get; set; }
        public string RCD_DESCRIPTION { get; set; }
        public string RCD_CUSTOMCODE { get; set; }
        public double RCD_QUANTITY { get; set; }
        public int RCD_QUID { get; set; }
        public double RCD_UNITPRICE { get; set; }
        public Nullable<decimal> RCD_NETTO { get; set; }
        public Nullable<double> RCD_DISCOUNTPERCENT { get; set; }
        public Nullable<decimal> RCD_DISCOUNT { get; set; }
        public int RCD_TAXDEFID { get; set; }
        public Nullable<decimal> RCD_TAXVALUE { get; set; }
        public Nullable<decimal> RCD_BRUTTO { get; set; }
        public Nullable<int> RCD_DETAILGROUP { get; set; }
    
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual QUANTITY_UNIT QUANTITY_UNIT { get; set; }
        public virtual RECEIPT RECEIPT { get; set; }
        public virtual TAXDEF TAXDEF { get; set; }
    }
}
