//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class REGISTEREDPROD
    {
        public int OID { get; set; }
        public int TID { get; set; }
        public int RP_SRCPRODOID { get; set; }
        public int RP_SRCPRODTID { get; set; }
        public int RP_DESTPRODOID { get; set; }
        public int RP_DESTPRODTID { get; set; }
        public string RP_DESCRIPTION { get; set; }
        public int RP_PRIORITY { get; set; }
    
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual PRODUCT PRODUCT1 { get; set; }
    }
}
