//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class RETURNEDCHANGE_DETAIL
    {
        public int OID { get; set; }
        public int TID { get; set; }
        public int RTCD_RETURNEDCHANGEOID { get; set; }
        public int RTCD_RETURNEDCHANGETID { get; set; }
        public Nullable<int> RTCD_PRODUCTOID { get; set; }
        public Nullable<int> RTCD_PRODUCTTID { get; set; }
        public double RTCD_QUANTITY { get; set; }
        public Nullable<double> RTCD_CQUANTITY { get; set; }
        public int RTCD_QUID { get; set; }
        public string RTCD_CUSTOMCODE { get; set; }
        public string RTCD_CUSTPRODUCTCODE { get; set; }
        public double RTCD_UNITPRICE { get; set; }
        public string RTCD_CURRENCY { get; set; }
        public Nullable<double> RTCD_CURRENCY_RATE { get; set; }
        public Nullable<double> RTCD_UNITPRICEBC { get; set; }
        public Nullable<double> RTCD_PRICEMULTIPLIER { get; set; }
        public Nullable<double> RTCD_DISCOUNTPERCENT { get; set; }
        public Nullable<decimal> RTCD_DISCOUNT { get; set; }
        public Nullable<decimal> RTCD_NETTO { get; set; }
        public Nullable<int> RTCD_TAXDEFID { get; set; }
        public Nullable<decimal> RTCD_TAXVALUE { get; set; }
        public Nullable<decimal> RTCD_BRUTTO { get; set; }
        public string RTCD_SERIALNUMBER { get; set; }
        public string RTCD_DESCRIPTION { get; set; }
        public Nullable<int> RTCD_ANCESTOROID { get; set; }
        public Nullable<int> RTCD_ANCESTORTID { get; set; }
        public string RTCD_CONTCODE { get; set; }
        public Nullable<System.DateTime> RTCD_LIMITDAY { get; set; }
        public string RTCD_TAG { get; set; }
        public Nullable<System.DateTime> RTCD_GUARANTEEDDATE { get; set; }
        public string RTCD_FORCE { get; set; }
        public string RTCD_TACC { get; set; }
        public string RTCD_KACC { get; set; }
        public Nullable<int> RTCD_PROJECTOID { get; set; }
        public Nullable<int> RTCD_PROJECTTID { get; set; }
        public Nullable<int> RTCD_CUSTOMCHARGE { get; set; }
        public Nullable<double> RTCD_CUSTOMPERCENT { get; set; }
        public Nullable<double> RTCD_GROSSWEIGHT { get; set; }
        public Nullable<double> RTCD_NETWEIGHT { get; set; }
        public Nullable<decimal> RTCD_OTHERCOSTBC { get; set; }
        public Nullable<int> RTCD_COSTCENTEROID { get; set; }
        public Nullable<int> RTCD_COSTCENTERTID { get; set; }
    
        public virtual COSTCENTER COSTCENTER { get; set; }
        public virtual CURRENCY CURRENCY { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual PROJECT PROJECT { get; set; }
        public virtual QUANTITY_UNIT QUANTITY_UNIT { get; set; }
        public virtual RETURNEDCHANGE RETURNEDCHANGE { get; set; }
        public virtual TAXDEF TAXDEF { get; set; }
    }
}
