//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCALINGCONFIRMATION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SCALINGCONFIRMATION()
        {
            this.SCALINGCONFIRMATION_DETAIL = new HashSet<SCALINGCONFIRMATION_DETAIL>();
        }
    
        public int OID { get; set; }
        public int TID { get; set; }
        public Nullable<int> SC_DOCUOWNNUMBER { get; set; }
        public string SC_DOCUGENNUMBER { get; set; }
        public string SC_ORIGNUMBER { get; set; }
        public System.DateTime SC_DOCUDATE { get; set; }
        public Nullable<int> SC_SECTIONOID { get; set; }
        public Nullable<int> SC_SECTIONTID { get; set; }
        public int SC_CUSTOMEROID { get; set; }
        public int SC_CUSTOMERTID { get; set; }
        public Nullable<int> SC_EMPLOYEEID { get; set; }
        public Nullable<System.DateTime> SC_ORIGINDATE { get; set; }
        public string SC_FULFILM_PLACE { get; set; }
        public System.DateTime SC_FULFILMENT { get; set; }
        public string SC_STORNO { get; set; }
        public Nullable<System.DateTime> SC_STORNODAT { get; set; }
        public string SC_OK { get; set; }
        public Nullable<System.DateTime> SC_OKDATE { get; set; }
        public string SC_CUSTOMERNAME { get; set; }
        public string SC_FIRSTNAME { get; set; }
        public string SC_LASTNAME { get; set; }
        public string SC_COUNTRY { get; set; }
        public string SC_ZIP { get; set; }
        public string SC_CITY { get; set; }
        public string SC_STREET { get; set; }
        public string SC_ACCOUNTNUMBER { get; set; }
        public string SC_TAXNUMBER { get; set; }
        public string SC_EUTAXNUMBER { get; set; }
        public string SC_NOTE { get; set; }
        public string SC_POSTSCRIPT { get; set; }
        public Nullable<int> SC_PLACEOFSCALEOID { get; set; }
        public Nullable<int> SC_PLACEOFSCALETID { get; set; }
        public Nullable<int> SC_STOREINWHWAREHOUSEID { get; set; }
        public Nullable<int> SC_SCALEERIN { get; set; }
        public Nullable<int> SC_SCALEEROUT { get; set; }
        public Nullable<int> SC_SCALEID { get; set; }
        public string SC_BUYUPGENMODE { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        public virtual EMPLOYEE EMPLOYEE1 { get; set; }
        public virtual EMPLOYEE EMPLOYEE2 { get; set; }
        public virtual SCALE SCALE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SCALINGCONFIRMATION_DETAIL> SCALINGCONFIRMATION_DETAIL { get; set; }
        public virtual SECTION SECTION { get; set; }
        public virtual SECTION SECTION1 { get; set; }
        public virtual WAREHOUSE WAREHOUSE { get; set; }
    }
}
