//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SECTIONBANK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SECTIONBANK()
        {
            this.BANKSTAT = new HashSet<BANKSTAT>();
            this.BANKTRANSFER = new HashSet<BANKTRANSFER>();
            this.I_SETTLE = new HashSet<I_SETTLE>();
        }
    
        public int OID { get; set; }
        public int TID { get; set; }
        public int SB_SECTIONOID { get; set; }
        public int SB_SECTIONTID { get; set; }
        public int SB_BANKID { get; set; }
        public string SB_ACCOUNTNAME { get; set; }
        public string SB_ACCOUNTNUMBER { get; set; }
        public string SB_ACCOUNTTYPE { get; set; }
        public string SB_ACCOUNTOWNER { get; set; }
        public string SB_GROUPEDCOLLECTION { get; set; }
        public string SB_CARDNUMBERS { get; set; }
        public Nullable<int> SB_BANKCLIENTID { get; set; }
        public string SB_ACTIVE { get; set; }
        public Nullable<System.DateTime> SB_VALIDTODATE { get; set; }
        public string SB_CURRENCYID { get; set; }
        public Nullable<decimal> SB_APPROPRIATION { get; set; }
        public Nullable<System.DateTime> SB_APPROPRIATIONVALIDTO { get; set; }
        public string SB_SUBBOOKACCOUNT { get; set; }
        public string SB_NOTE { get; set; }
        public string SB_BIC { get; set; }
        public string SB_IBANNUMBER { get; set; }
    
        public virtual BANK BANK { get; set; }
        public virtual BANKCLIENTS BANKCLIENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BANKSTAT> BANKSTAT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BANKTRANSFER> BANKTRANSFER { get; set; }
        public virtual CURRENCY CURRENCY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_SETTLE> I_SETTLE { get; set; }
        public virtual SECTION SECTION { get; set; }
    }
}
