//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERIALWORK
    {
        public Nullable<double> C_QUANTITY { get; set; }
        public Nullable<int> C_QUID { get; set; }
        public string CONTROLLED { get; set; }
        public Nullable<int> DETAIL_OID { get; set; }
        public Nullable<int> DETAIL_TID { get; set; }
        public string FORCE { get; set; }
        public Nullable<System.DateTime> LIMITDAY { get; set; }
        public int MASTER_OID { get; set; }
        public int MASTER_TID { get; set; }
        public Nullable<double> MB_QUANTITY { get; set; }
        public Nullable<int> MB_QUID { get; set; }
        public Nullable<double> MN_QUANTITY { get; set; }
        public Nullable<int> MN_QUID { get; set; }
        public Nullable<int> NOTICEOID { get; set; }
        public string NUMTYPE { get; set; }
        public int OID { get; set; }
        public Nullable<int> PFDIVISIONOID { get; set; }
        public Nullable<int> PFDIVISIONTID { get; set; }
        public Nullable<int> PRODUCTOID { get; set; }
        public Nullable<int> PRODUCTTID { get; set; }
        public Nullable<double> QUANTITY { get; set; }
        public Nullable<int> QUID { get; set; }
        public string SERIALNUMBER { get; set; }
        public Nullable<double> STOCKQUANTITY { get; set; }
        public string TAG { get; set; }
        public int TID { get; set; }
        public Nullable<double> UNITPRICEBC { get; set; }
        public Nullable<double> V_QUANTITY { get; set; }
        public Nullable<int> V_QUID { get; set; }
        public string TODO { get; set; }
        public Nullable<int> V_ACCEPTEDQUID { get; set; }
        public string V_EXACT { get; set; }
        public Nullable<int> C_ACCEPTEDQUID { get; set; }
        public string C_EXACT { get; set; }
        public Nullable<int> MN_ACCEPTEDQUID { get; set; }
        public string MN_EXACT { get; set; }
        public Nullable<int> MB_ACCEPTEDQUID { get; set; }
        public string MB_EXACT { get; set; }
    
        public virtual C_QUANTITY_UNIT C_QUANTITY_UNIT { get; set; }
        public virtual MB_QUANTITY_UNIT MB_QUANTITY_UNIT { get; set; }
        public virtual MN_QUANTITY_UNIT MN_QUANTITY_UNIT { get; set; }
        public virtual PFDIVISION PFDIVISION { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual QUANTITY_UNIT QUANTITY_UNIT { get; set; }
        public virtual QUANTITY_UNIT QUANTITY_UNIT1 { get; set; }
        public virtual QUANTITY_UNIT QUANTITY_UNIT2 { get; set; }
        public virtual QUANTITY_UNIT QUANTITY_UNIT3 { get; set; }
        public virtual QUANTITY_UNIT QUANTITY_UNIT4 { get; set; }
        public virtual V_QUANTITY_UNIT V_QUANTITY_UNIT { get; set; }
    }
}
