//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICEASSET
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SERVICEASSET()
        {
            this.SERVICEASSET_ADDITION = new HashSet<SERVICEASSET_ADDITION>();
            this.SERVICEASSET_EVENT = new HashSet<SERVICEASSET_EVENT>();
            this.SERVICEASSET_RESPONSIBLE = new HashSet<SERVICEASSET_RESPONSIBLE>();
            this.SERVICECONTRACT = new HashSet<SERVICECONTRACT>();
            this.SERVICESHEET = new HashSet<SERVICESHEET>();
        }
    
        public int OID { get; set; }
        public int TID { get; set; }
        public string SA_NUMBER { get; set; }
        public string SA_NAME { get; set; }
        public string SA_SERIALNUMBER { get; set; }
        public Nullable<int> SA_ASSETKINDID { get; set; }
        public string SA_DESCRIPTION { get; set; }
        public Nullable<System.DateTime> SA_INVESTDATE { get; set; }
        public string SA_ACTIVE { get; set; }
        public Nullable<System.DateTime> SA_INACTIVEDATE { get; set; }
        public Nullable<int> SA_PRODUCTOID { get; set; }
        public Nullable<int> SA_PRODUCTTID { get; set; }
        public Nullable<int> SA_CUSTOMEROID { get; set; }
        public Nullable<int> SA_CUSTOMERTID { get; set; }
        public Nullable<int> SA_CUSTADDRESSOID { get; set; }
        public Nullable<int> SA_CUSTADDRESSTID { get; set; }
        public Nullable<int> SA_PROJECTOID { get; set; }
        public Nullable<int> SA_PROJECTTID { get; set; }
    
        public virtual CUSTADDRESS CUSTADDRESS { get; set; }
        public virtual CUSTOMER CUSTOMER { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual PROJECT PROJECT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SERVICEASSET_ADDITION> SERVICEASSET_ADDITION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SERVICEASSET_EVENT> SERVICEASSET_EVENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SERVICEASSET_RESPONSIBLE> SERVICEASSET_RESPONSIBLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SERVICECONTRACT> SERVICECONTRACT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SERVICESHEET> SERVICESHEET { get; set; }
        public virtual SERVICEASSETKIND SERVICEASSETKIND { get; set; }
    }
}
