//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICESHEET_PRODUCT
    {
        public int OID { get; set; }
        public int TID { get; set; }
        public int SSP_SERVICESHEETOID { get; set; }
        public int SSP_SERVICESHEETTID { get; set; }
        public Nullable<int> SSP_PRODUCTOID { get; set; }
        public Nullable<int> SSP_PRODUCTTID { get; set; }
        public string SSP_CUSTOMCODE { get; set; }
        public string SSP_INPUTTYPE { get; set; }
        public double SSP_QUANTITY { get; set; }
        public double SSP_ABSQUANTITY { get; set; }
        public int SSP_QUID { get; set; }
        public double SSP_UNITPRICE { get; set; }
        public string SSP_CURRENCY { get; set; }
        public double SSP_CURRENCY_RATE { get; set; }
        public Nullable<double> SSP_UNITPRICEBC { get; set; }
        public double SSP_PRICEMULTIPLIER { get; set; }
        public Nullable<double> SSP_DISCOUNTPERCENT { get; set; }
        public Nullable<decimal> SSP_DISCOUNT { get; set; }
        public Nullable<decimal> SSP_NETTO { get; set; }
        public int SSP_TAXDEFID { get; set; }
        public Nullable<decimal> SSP_TAXVALUE { get; set; }
        public Nullable<decimal> SSP_BRUTTO { get; set; }
        public Nullable<int> SSP_DETAILGROUP { get; set; }
        public string SSP_CUSTPRODUCTCODE { get; set; }
        public string SSP_TAG { get; set; }
        public Nullable<System.DateTime> SSP_LIMITDAY { get; set; }
        public Nullable<System.DateTime> SSP_GUARANTEEDDATE { get; set; }
        public string SSP_SERIALNUMBER { get; set; }
        public string SSP_TOINVOICE { get; set; }
        public string SSP_NOTE { get; set; }
        public Nullable<int> SSP_STOCKMODOID { get; set; }
        public Nullable<int> SSP_STOCKMODTID { get; set; }
    
        public virtual CURRENCY CURRENCY { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual QUANTITY_UNIT QUANTITY_UNIT { get; set; }
        public virtual SERVICESHEET SERVICESHEET { get; set; }
        public virtual TAXDEF TAXDEF { get; set; }
        public virtual STOCKMOD STOCKMOD { get; set; }
    }
}
