//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICESHEET_OPERATION
    {
        public int OID { get; set; }
        public int TID { get; set; }
        public int SSO_SERVICESHEETOID { get; set; }
        public int SSO_SERVICESHEETTID { get; set; }
        public Nullable<int> SSO_PRODUCTOID { get; set; }
        public Nullable<int> SSO_PRODUCTTID { get; set; }
        public double SSO_QUANTITY { get; set; }
        public int SSO_QUID { get; set; }
        public string SSO_CURRENCY { get; set; }
        public double SSO_CURRENCY_RATE { get; set; }
        public double SSO_UNITPRICE { get; set; }
        public Nullable<double> SSO_UNITPRICEBC { get; set; }
        public double SSO_PRICEMULTIPLIER { get; set; }
        public Nullable<double> SSO_DISCOUNTPERCENT { get; set; }
        public int SSO_TAXDEFID { get; set; }
        public Nullable<decimal> SSO_DISCOUNT { get; set; }
        public Nullable<decimal> SSO_NETTO { get; set; }
        public Nullable<decimal> SSO_TAXVALUE { get; set; }
        public Nullable<decimal> SSO_BRUTTO { get; set; }
        public Nullable<int> SSO_DETAILGROUP { get; set; }
        public Nullable<int> SSO_WORKERID { get; set; }
        public string SSO_TOINVOICE { get; set; }
        public string SSO_NOTE { get; set; }
    
        public virtual CURRENCY CURRENCY { get; set; }
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual QUANTITY_UNIT QUANTITY_UNIT { get; set; }
        public virtual SERVICESHEET SERVICESHEET { get; set; }
        public virtual TAXDEF TAXDEF { get; set; }
    }
}
