//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICEASSET_RESPONSIBLE
    {
        public int OID { get; set; }
        public int TID { get; set; }
        public int SAR_SERVICEASSETOID { get; set; }
        public int SAR_SERVICEASSETTID { get; set; }
        public System.DateTime SAR_FROMDATE { get; set; }
        public Nullable<System.DateTime> SAR_TODATE { get; set; }
        public Nullable<int> SAR_EMPLOYEEID { get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        public virtual SERVICEASSET SERVICEASSET { get; set; }
    }
}
