//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class STORE_IN_DETAIL
    {
        public int OID { get; set; }
        public int TID { get; set; }
        public int SID_STOREINOID { get; set; }
        public int SID_STOREINTID { get; set; }
        public Nullable<int> SID_PRODUCTOID { get; set; }
        public Nullable<int> SID_PRODUCTTID { get; set; }
        public string SID_CUSTOMCODE { get; set; }
        public double SID_QUANTITY { get; set; }
        public Nullable<double> SID_CQUANTITY { get; set; }
        public int SID_QUID { get; set; }
        public Nullable<double> SID_MEA_QUANTITY { get; set; }
        public Nullable<int> SID_MEA_QUID { get; set; }
        public double SID_UNITPRICE { get; set; }
        public string SID_CURRENCY { get; set; }
        public double SID_CURRENCY_RATE { get; set; }
        public Nullable<double> SID_UNITPRICEBC { get; set; }
        public double SID_PRICEMULTIPLIER { get; set; }
        public Nullable<double> SID_DISCOUNTPERCENT { get; set; }
        public Nullable<decimal> SID_DISCOUNT { get; set; }
        public Nullable<decimal> SID_NETTO { get; set; }
        public int SID_TAXDEFID { get; set; }
        public Nullable<decimal> SID_TAXVALUE { get; set; }
        public Nullable<decimal> SID_BRUTTO { get; set; }
        public Nullable<int> SID_DETAILGROUP { get; set; }
        public string SID_CUSTPRODUCTCODE { get; set; }
        public Nullable<System.DateTime> SID_LIMITDAY { get; set; }
        public Nullable<System.DateTime> SID_GUARANTEEDDATE { get; set; }
        public string SID_BARCODE { get; set; }
        public string SID_DESCRIPTION { get; set; }
        public string SID_SERIALNUMBER { get; set; }
        public string SID_CONTCODE { get; set; }
        public string SID_TAG { get; set; }
        public Nullable<int> SID_ORIGINID { get; set; }
        public string SID_FORCE { get; set; }
        public string SID_TACC { get; set; }
        public string SID_KACC { get; set; }
        public Nullable<int> SID_PROJECTOID { get; set; }
        public Nullable<int> SID_PROJECTTID { get; set; }
        public Nullable<int> SID_CUSTOMCHARGE { get; set; }
        public Nullable<double> SID_CUSTOMPERCENT { get; set; }
        public Nullable<double> SID_GROSSWEIGHT { get; set; }
        public Nullable<double> SID_NETWEIGHT { get; set; }
        public Nullable<decimal> SID_OTHERCOSTBC { get; set; }
        public Nullable<int> SID_COSTCENTEROID { get; set; }
        public Nullable<int> SID_COSTCENTERTID { get; set; }
    
        public virtual COSTCENTER COSTCENTER { get; set; }
        public virtual CURRENCY CURRENCY { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual PRODUCTORIGIN PRODUCTORIGIN { get; set; }
        public virtual PROJECT PROJECT { get; set; }
        public virtual QUANTITY_UNIT QUANTITY_UNIT { get; set; }
        public virtual QUANTITY_UNIT QUANTITY_UNIT1 { get; set; }
        public virtual STORE_IN STORE_IN { get; set; }
        public virtual TAXDEF TAXDEF { get; set; }
    }
}
