//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class STORE_IN_SERIAL
    {
        public Nullable<double> SIS_C_QUANTITY { get; set; }
        public Nullable<int> SIS_C_QUID { get; set; }
        public string SIS_CONTROLLED { get; set; }
        public Nullable<int> SIS_DETAIL_OID { get; set; }
        public Nullable<int> SIS_DETAIL_TID { get; set; }
        public string SIS_FORCE { get; set; }
        public Nullable<System.DateTime> SIS_LIMITDAY { get; set; }
        public int SIS_MASTER_OID { get; set; }
        public int SIS_MASTER_TID { get; set; }
        public Nullable<double> SIS_MB_QUANTITY { get; set; }
        public Nullable<int> SIS_MB_QUID { get; set; }
        public Nullable<double> SIS_MN_QUANTITY { get; set; }
        public Nullable<int> SIS_MN_QUID { get; set; }
        public Nullable<int> SIS_NOTICEOID { get; set; }
        public string SIS_NUMTYPE { get; set; }
        public int OID { get; set; }
        public Nullable<int> SIS_PFDIVISIONOID { get; set; }
        public Nullable<int> SIS_PFDIVISIONTID { get; set; }
        public Nullable<int> SIS_PRODUCTOID { get; set; }
        public Nullable<int> SIS_PRODUCTTID { get; set; }
        public Nullable<double> SIS_QUANTITY { get; set; }
        public Nullable<int> SIS_QUID { get; set; }
        public string SIS_SERIALNUMBER { get; set; }
        public Nullable<double> SIS_STOCKQUANTITY { get; set; }
        public string SIS_TAG { get; set; }
        public int TID { get; set; }
        public Nullable<double> SIS_UNITPRICEBC { get; set; }
        public Nullable<double> SIS_V_QUANTITY { get; set; }
        public Nullable<int> SIS_V_QUID { get; set; }
    
        public virtual C_QUANTITY_UNIT C_QUANTITY_UNIT { get; set; }
        public virtual MB_QUANTITY_UNIT MB_QUANTITY_UNIT { get; set; }
        public virtual MB_QUANTITY_UNIT MB_QUANTITY_UNIT1 { get; set; }
        public virtual MN_QUANTITY_UNIT MN_QUANTITY_UNIT { get; set; }
        public virtual MN_QUANTITY_UNIT MN_QUANTITY_UNIT1 { get; set; }
        public virtual PFDIVISION PFDIVISION { get; set; }
        public virtual PFDIVISION PFDIVISION1 { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual QUANTITY_UNIT QUANTITY_UNIT { get; set; }
        public virtual QUANTITY_UNIT QUANTITY_UNIT1 { get; set; }
        public virtual STORE_IN STORE_IN { get; set; }
        public virtual V_QUANTITY_UNIT V_QUANTITY_UNIT { get; set; }
        public virtual V_QUANTITY_UNIT V_QUANTITY_UNIT1 { get; set; }
    }
}
