//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUPPLYORDER_REQUEST
    {
        public int OID { get; set; }
        public int TID { get; set; }
        public int SUR_SUPPLYORDEROID { get; set; }
        public int SUR_SUPPLYORDERTID { get; set; }
        public Nullable<int> SUR_DETAIL_OID { get; set; }
        public Nullable<int> SUR_DETAIL_TID { get; set; }
        public int SUR_PRODUCTOID { get; set; }
        public int SUR_PRODUCTTID { get; set; }
        public double SUR_QUANTITY { get; set; }
        public Nullable<double> SUR_SUPPLIEDQUANTITY { get; set; }
        public int SUR_QUID { get; set; }
        public double SUR_UNITPRICE { get; set; }
        public string SUR_CURRENCY { get; set; }
        public double SUR_CURRENCY_RATE { get; set; }
        public Nullable<double> SUR_UNITPRICEBC { get; set; }
        public double SUR_PRICEMULTIPLIER { get; set; }
        public Nullable<double> SUR_DISCOUNTPERCENT { get; set; }
        public Nullable<decimal> SUR_DISCOUNT { get; set; }
        public Nullable<decimal> SUR_NETTO { get; set; }
        public int SUR_TAXDEFID { get; set; }
        public Nullable<decimal> SUR_TAXVALUE { get; set; }
        public Nullable<decimal> SUR_BRUTTO { get; set; }
        public Nullable<int> SUR_DETAILGROUP { get; set; }
        public Nullable<System.DateTime> SUR_DELIVERYDATE { get; set; }
        public Nullable<int> SUR_PROJECTOID { get; set; }
        public Nullable<int> SUR_PROJECTTID { get; set; }
        public string SUR_NOTE { get; set; }
        public Nullable<int> SUR_COSTCENTEROID { get; set; }
        public Nullable<int> SUR_COSTCENTERTID { get; set; }
    
        public virtual COSTCENTER COSTCENTER { get; set; }
        public virtual CURRENCY CURRENCY { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual PROJECT PROJECT { get; set; }
        public virtual QUANTITY_UNIT QUANTITY_UNIT { get; set; }
        public virtual SUPPLYORDER SUPPLYORDER { get; set; }
        public virtual TAXDEF TAXDEF { get; set; }
    }
}
