//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUPPLYOFFER_DETAIL
    {
        public int OID { get; set; }
        public int TID { get; set; }
        public int SFD_SUPPLYOFFEROID { get; set; }
        public int SFD_SUPPLYOFFERTID { get; set; }
        public Nullable<int> SFD_PRODUCTOID { get; set; }
        public Nullable<int> SFD_PRODUCTTID { get; set; }
        public string SFD_CUSTOMCODE { get; set; }
        public double SFD_QUANTITY { get; set; }
        public Nullable<double> SFD_REQUESTEDQUANTITY { get; set; }
        public int SFD_QUID { get; set; }
        public double SFD_UNITPRICE { get; set; }
        public string SFD_CURRENCY { get; set; }
        public double SFD_CURRENCY_RATE { get; set; }
        public Nullable<double> SFD_UNITPRICEBC { get; set; }
        public double SFD_PRICEMULTIPLIER { get; set; }
        public Nullable<double> SFD_DISCOUNTPERCENT { get; set; }
        public Nullable<decimal> SFD_DISCOUNT { get; set; }
        public Nullable<decimal> SFD_NETTO { get; set; }
        public int SFD_TAXDEFID { get; set; }
        public Nullable<decimal> SFD_TAXVALUE { get; set; }
        public Nullable<decimal> SFD_BRUTTO { get; set; }
        public Nullable<System.DateTime> SFD_DELIVERYDATE { get; set; }
        public Nullable<int> SFD_DETAILGROUP { get; set; }
        public string SFD_CUSTPRODUCTCODE { get; set; }
        public string SFD_DESCRIPTION { get; set; }
        public Nullable<System.DateTime> SFD_BEGINTIME { get; set; }
        public Nullable<System.DateTime> SFD_ENDTIME { get; set; }
        public Nullable<int> SFD_PROJECTOID { get; set; }
        public Nullable<int> SFD_PROJECTTID { get; set; }
        public string SFD_NOTE { get; set; }
        public Nullable<int> SFD_CUSTOMCHARGE { get; set; }
        public Nullable<double> SFD_CUSTOMPERCENT { get; set; }
        public Nullable<double> SFD_GROSSWEIGHT { get; set; }
        public Nullable<double> SFD_NETWEIGHT { get; set; }
        public Nullable<decimal> SFD_OTHERCOSTBC { get; set; }
        public Nullable<int> SFD_COSTCENTEROID { get; set; }
        public Nullable<int> SFD_COSTCENTERTID { get; set; }
    
        public virtual COSTCENTER COSTCENTER { get; set; }
        public virtual CURRENCY CURRENCY { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual PROJECT PROJECT { get; set; }
        public virtual QUANTITY_UNIT QUANTITY_UNIT { get; set; }
        public virtual SUPPLYOFFER SUPPLYOFFER { get; set; }
        public virtual TAXDEF TAXDEF { get; set; }
    }
}
