//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_OF_BANKTRANSFER
    {
        public int DOID { get; set; }
        public int DTID { get; set; }
        public int OOID { get; set; }
        public int OTID { get; set; }
        public int STYPE { get; set; }
    }
}
