//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAXDEF
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TAXDEF()
        {
            this.ANALYTICTAX_DETAIL = new HashSet<ANALYTICTAX_DETAIL>();
            this.ANALYTICTAX_TAXES = new HashSet<ANALYTICTAX_TAXES>();
            this.AVISO_DETAIL = new HashSet<AVISO_DETAIL>();
            this.BOOKCONT = new HashSet<BOOKCONT>();
            this.BOOKPOST = new HashSet<BOOKPOST>();
            this.BUYUP_DETAIL = new HashSet<BUYUP_DETAIL>();
            this.BUYUP_DETAIL_ALT = new HashSet<BUYUP_DETAIL_ALT>();
            this.CONSIGNMENT_IN_DETAIL = new HashSet<CONSIGNMENT_IN_DETAIL>();
            this.CONSIGNMENT_OUT_DETAIL = new HashSet<CONSIGNMENT_OUT_DETAIL>();
            this.CONSIGNMENTREPORT_DETAIL = new HashSet<CONSIGNMENTREPORT_DETAIL>();
            this.CUSTOMDOC_DETAIL = new HashSet<CUSTOMDOC_DETAIL>();
            this.DELIVERYCONTRACT_DETAIL = new HashSet<DELIVERYCONTRACT_DETAIL>();
            this.DELIVERYOFFER_DETAIL = new HashSet<DELIVERYOFFER_DETAIL>();
            this.DELIVERYORDER_DETAIL = new HashSet<DELIVERYORDER_DETAIL>();
            this.DIRECTBUY_DETAIL = new HashSet<DIRECTBUY_DETAIL>();
            this.DIRECTSELL_DETAIL = new HashSet<DIRECTSELL_DETAIL>();
            this.DPI_INVOICEDETAIL = new HashSet<DPI_INVOICEDETAIL>();
            this.DPI_TAXDETAIL = new HashSet<DPI_TAXDETAIL>();
            this.DPO_INVOICEDETAIL = new HashSet<DPO_INVOICEDETAIL>();
            this.DPO_TAXDETAIL = new HashSet<DPO_TAXDETAIL>();
            this.GADFILEMOD_POST = new HashSet<GADFILEMOD_POST>();
            this.I_INVOICEDETAIL = new HashSet<I_INVOICEDETAIL>();
            this.INVENTORY_GAP_DETAIL = new HashSet<INVENTORY_GAP_DETAIL>();
            this.JUSTWAYBILL_DETAIL = new HashSet<JUSTWAYBILL_DETAIL>();
            this.KOMISSIO_DETAIL = new HashSet<KOMISSIO_DETAIL>();
            this.LEASECONTRACT_SERVICE = new HashSet<LEASECONTRACT_SERVICE>();
            this.LEASECONTRACTBACK_DEFICIENCY = new HashSet<LEASECONTRACTBACK_DEFICIENCY>();
            this.LEASECONTRACTBACK_LEASE = new HashSet<LEASECONTRACTBACK_LEASE>();
            this.LEASECONTRACTBACK_SERVICE = new HashSet<LEASECONTRACTBACK_SERVICE>();
            this.MARKETREGISTER_DETAIL = new HashSet<MARKETREGISTER_DETAIL>();
            this.O_INVOICEDETAIL = new HashSet<O_INVOICEDETAIL>();
            this.PACKING_DETAIL = new HashSet<PACKING_DETAIL>();
            this.PACKING_DONEDETAIL = new HashSet<PACKING_DONEDETAIL>();
            this.PRODDELIVERY_DETAIL = new HashSet<PRODDELIVERY_DETAIL>();
            this.PRODREQUEST_DETAIL = new HashSet<PRODREQUEST_DETAIL>();
            this.PRODUCT = new HashSet<PRODUCT>();
            this.PRODUCTGROUP = new HashSet<PRODUCTGROUP>();
            this.PRODUCTION_DETAIL = new HashSet<PRODUCTION_DETAIL>();
            this.RECEIPT_CLOSE_DETAIL = new HashSet<RECEIPT_CLOSE_DETAIL>();
            this.RECEIPT_DETAIL = new HashSet<RECEIPT_DETAIL>();
            this.RETREIVEANAL_DETAIL = new HashSet<RETREIVEANAL_DETAIL>();
            this.RETREIVECHANGE_DETAIL = new HashSet<RETREIVECHANGE_DETAIL>();
            this.RETREIVECHANGE_DETAIL1 = new HashSet<RETREIVECHANGE_DETAIL>();
            this.RETREIVECHANGE_DETAIL_ALT = new HashSet<RETREIVECHANGE_DETAIL_ALT>();
            this.RETURNEDCHANGE_DETAIL = new HashSet<RETURNEDCHANGE_DETAIL>();
            this.SERVICECONTRACT_COST = new HashSet<SERVICECONTRACT_COST>();
            this.SERVICESHEET_FIELDWORK = new HashSet<SERVICESHEET_FIELDWORK>();
            this.SERVICESHEET_OPERATION = new HashSet<SERVICESHEET_OPERATION>();
            this.SERVICESHEET_PRODUCT = new HashSet<SERVICESHEET_PRODUCT>();
            this.STORE_IN_DETAIL = new HashSet<STORE_IN_DETAIL>();
            this.STORE_OUT_DETAIL = new HashSet<STORE_OUT_DETAIL>();
            this.SUPPLYOFFER_DETAIL = new HashSet<SUPPLYOFFER_DETAIL>();
            this.SUPPLYOFFER_REQUEST = new HashSet<SUPPLYOFFER_REQUEST>();
            this.SUPPLYORDER_DETAIL = new HashSet<SUPPLYORDER_DETAIL>();
            this.SUPPLYORDER_REQUEST = new HashSet<SUPPLYORDER_REQUEST>();
            this.TOOLBENCH = new HashSet<TOOLBENCH>();
            this.TOOLINPUT = new HashSet<TOOLINPUT>();
            this.TOOLTRAVELLING_DETAIL = new HashSet<TOOLTRAVELLING_DETAIL>();
            this.TOOLTRAVELS = new HashSet<TOOLTRAVELS>();
            this.WAYBILL_DETAIL = new HashSet<WAYBILL_DETAIL>();
            this.TOOLMAKECONTRACT_COST = new HashSet<TOOLMAKECONTRACT_COST>();
        }
    
        public int TAXDEFID { get; set; }
        public double TAXPERCNT { get; set; }
        public string TAXNAME { get; set; }
        public string FORSTATEMENT { get; set; }
        public Nullable<double> REVERSEPERCNT { get; set; }
        public string TIREFCODE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ANALYTICTAX_DETAIL> ANALYTICTAX_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ANALYTICTAX_TAXES> ANALYTICTAX_TAXES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AVISO_DETAIL> AVISO_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOOKCONT> BOOKCONT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOOKPOST> BOOKPOST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BUYUP_DETAIL> BUYUP_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BUYUP_DETAIL_ALT> BUYUP_DETAIL_ALT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONSIGNMENT_IN_DETAIL> CONSIGNMENT_IN_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONSIGNMENT_OUT_DETAIL> CONSIGNMENT_OUT_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONSIGNMENTREPORT_DETAIL> CONSIGNMENTREPORT_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUSTOMDOC_DETAIL> CUSTOMDOC_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DELIVERYCONTRACT_DETAIL> DELIVERYCONTRACT_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DELIVERYOFFER_DETAIL> DELIVERYOFFER_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DELIVERYORDER_DETAIL> DELIVERYORDER_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DIRECTBUY_DETAIL> DIRECTBUY_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DIRECTSELL_DETAIL> DIRECTSELL_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DPI_INVOICEDETAIL> DPI_INVOICEDETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DPI_TAXDETAIL> DPI_TAXDETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DPO_INVOICEDETAIL> DPO_INVOICEDETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DPO_TAXDETAIL> DPO_TAXDETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GADFILEMOD_POST> GADFILEMOD_POST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_INVOICEDETAIL> I_INVOICEDETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INVENTORY_GAP_DETAIL> INVENTORY_GAP_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JUSTWAYBILL_DETAIL> JUSTWAYBILL_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KOMISSIO_DETAIL> KOMISSIO_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LEASECONTRACT_SERVICE> LEASECONTRACT_SERVICE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LEASECONTRACTBACK_DEFICIENCY> LEASECONTRACTBACK_DEFICIENCY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LEASECONTRACTBACK_LEASE> LEASECONTRACTBACK_LEASE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LEASECONTRACTBACK_SERVICE> LEASECONTRACTBACK_SERVICE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MARKETREGISTER_DETAIL> MARKETREGISTER_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<O_INVOICEDETAIL> O_INVOICEDETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PACKING_DETAIL> PACKING_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PACKING_DONEDETAIL> PACKING_DONEDETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODDELIVERY_DETAIL> PRODDELIVERY_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODREQUEST_DETAIL> PRODREQUEST_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCT> PRODUCT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCTGROUP> PRODUCTGROUP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCTION_DETAIL> PRODUCTION_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RECEIPT_CLOSE_DETAIL> RECEIPT_CLOSE_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RECEIPT_DETAIL> RECEIPT_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RETREIVEANAL_DETAIL> RETREIVEANAL_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RETREIVECHANGE_DETAIL> RETREIVECHANGE_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RETREIVECHANGE_DETAIL> RETREIVECHANGE_DETAIL1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RETREIVECHANGE_DETAIL_ALT> RETREIVECHANGE_DETAIL_ALT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RETURNEDCHANGE_DETAIL> RETURNEDCHANGE_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SERVICECONTRACT_COST> SERVICECONTRACT_COST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SERVICESHEET_FIELDWORK> SERVICESHEET_FIELDWORK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SERVICESHEET_OPERATION> SERVICESHEET_OPERATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SERVICESHEET_PRODUCT> SERVICESHEET_PRODUCT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STORE_IN_DETAIL> STORE_IN_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STORE_OUT_DETAIL> STORE_OUT_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUPPLYOFFER_DETAIL> SUPPLYOFFER_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUPPLYOFFER_REQUEST> SUPPLYOFFER_REQUEST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUPPLYORDER_DETAIL> SUPPLYORDER_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUPPLYORDER_REQUEST> SUPPLYORDER_REQUEST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TOOLBENCH> TOOLBENCH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TOOLINPUT> TOOLINPUT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TOOLTRAVELLING_DETAIL> TOOLTRAVELLING_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TOOLTRAVELS> TOOLTRAVELS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WAYBILL_DETAIL> WAYBILL_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TOOLMAKECONTRACT_COST> TOOLMAKECONTRACT_COST { get; set; }
    }
}
