//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOOLHISTORY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TOOLHISTORY()
        {
            this.TOOLSERVICE = new HashSet<TOOLSERVICE>();
        }
    
        public int OID { get; set; }
        public int TID { get; set; }
        public Nullable<int> TH_TOOLOID { get; set; }
        public Nullable<int> TH_TOOLTID { get; set; }
        public int TH_HISTORYORDER { get; set; }
        public string TH_HISTORYTYPE { get; set; }
        public System.DateTime TH_HISTORYDATE { get; set; }
        public string TH_HISTORYNAME { get; set; }
        public int TH_EMPLOYEEID { get; set; }
        public string TH_HISTORYNOTE { get; set; }
        public string TH_CLOSED { get; set; }
        public Nullable<int> TH_DOCOID { get; set; }
        public Nullable<int> TH_DOCTID { get; set; }
        public Nullable<int> TH_TOOLVALIDCONTRACTOID { get; set; }
        public Nullable<int> TH_TOOLVALIDCONTRACTTID { get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        public virtual TOOL TOOL { get; set; }
        public virtual TOOLVALIDCONTRACT TOOLVALIDCONTRACT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TOOLSERVICE> TOOLSERVICE { get; set; }
    }
}
