//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOOLMAKECONTRACT_CONTRACT
    {
        public int OID { get; set; }
        public int TID { get; set; }
        public int TMCC_TOOLMAKECONTRACTOID { get; set; }
        public int TMCC_TOOLMAKECONTRACTTID { get; set; }
        public int TMCC_TOOLCONTRACTOID { get; set; }
        public int TMCC_TOOLCONTRACTTID { get; set; }
        public System.DateTime TMCC_VALIDFROM { get; set; }
        public string TMCC_DESCRIPTION { get; set; }
    
        public virtual TOOLCONTRACT TOOLCONTRACT { get; set; }
        public virtual TOOLMAKECONTRACT TOOLMAKECONTRACT { get; set; }
    }
}
