//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOOLADDITIONGROUP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TOOLADDITIONGROUP()
        {
            this.TOOLACCESSORY = new HashSet<TOOLACCESSORY>();
            this.TOOLACCESSORY1 = new HashSet<TOOLACCESSORY>();
            this.TOOLADDITION = new HashSet<TOOLADDITION>();
        }
    
        public int TOOLADDITIONGROUPID { get; set; }
        public string TAG_TOOLADDITIONGROUPNAME { get; set; }
        public int TAG_APPEARORDER { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TOOLACCESSORY> TOOLACCESSORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TOOLACCESSORY> TOOLACCESSORY1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TOOLADDITION> TOOLADDITION { get; set; }
    }
}
