//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOOLEMPLOYEE
    {
        public int OID { get; set; }
        public int TID { get; set; }
        public int TE_EMPLOYEEID { get; set; }
        public System.DateTime TE_FROMDATE { get; set; }
        public int TE_TOOLOID { get; set; }
        public int TE_TOOLTID { get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        public virtual TOOL TOOL { get; set; }
    }
}
