//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOOL_EVENTBOOK
    {
        public int OID { get; set; }
        public int TID { get; set; }
        public int TEB_TOOLOID { get; set; }
        public int TEB_TOOLTID { get; set; }
        public Nullable<System.DateTime> TEB_DONEDATE { get; set; }
        public Nullable<System.DateTime> TEB_DONEDEADLINE { get; set; }
        public string TEB_DONEMODE { get; set; }
        public Nullable<int> TEB_EMPLOYEEID { get; set; }
        public Nullable<System.DateTime> TEB_EVENTDATE { get; set; }
        public Nullable<int> TEB_EVENTTYPE { get; set; }
        public Nullable<System.DateTime> TEB_NEXTEVENTDATE { get; set; }
        public string TEB_NEXTEVENTTHEME { get; set; }
        public string TEB_NOTE { get; set; }
        public string TEB_SENDMAIL { get; set; }
        public string TEB_SUBJECT { get; set; }
        public string TEB_TYPE { get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        public virtual EVENTTYPE EVENTTYPE { get; set; }
        public virtual TOOL TOOL { get; set; }
    }
}
