//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOOLCONTRACT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TOOLCONTRACT()
        {
            this.TOOL = new HashSet<TOOL>();
            this.TOOLCONTRACT_COST = new HashSet<TOOLCONTRACT_COST>();
            this.TOOLCONTRACT_DETAIL = new HashSet<TOOLCONTRACT_DETAIL>();
            this.TOOLMAKECONTRACT_CONTRACT = new HashSet<TOOLMAKECONTRACT_CONTRACT>();
            this.TOOLVALIDCONTRACT = new HashSet<TOOLVALIDCONTRACT>();
        }
    
        public int OID { get; set; }
        public int TID { get; set; }
        public string TC_CONTRACTNAME { get; set; }
        public Nullable<int> TC_SERVICEPERYEAR { get; set; }
        public Nullable<int> TC_VALIDDAYS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TOOL> TOOL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TOOLCONTRACT_COST> TOOLCONTRACT_COST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TOOLCONTRACT_DETAIL> TOOLCONTRACT_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TOOLMAKECONTRACT_CONTRACT> TOOLMAKECONTRACT_CONTRACT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TOOLVALIDCONTRACT> TOOLVALIDCONTRACT { get; set; }
    }
}
