//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class UNONTHEWAY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UNONTHEWAY()
        {
            this.SUPPLYORDERMOD = new HashSet<SUPPLYORDERMOD>();
            this.SUPPLYORDERMOD1 = new HashSet<SUPPLYORDERMOD>();
            this.UNONTHEWAY_DETAIL = new HashSet<UNONTHEWAY_DETAIL>();
            this.UNONTHEWAY_EXPANDED = new HashSet<UNONTHEWAY_EXPANDED>();
        }
    
        public int OID { get; set; }
        public int TID { get; set; }
        public Nullable<int> UOW_CUSTOMEROID { get; set; }
        public Nullable<int> UOW_CUSTOMERTID { get; set; }
        public int UOW_WAREHOUSEID { get; set; }
        public int UOW_EOID { get; set; }
        public int UOW_ETID { get; set; }
        public Nullable<int> UOW_DOCUGENNUMBER { get; set; }
        public string UOW_DOCUNUMBER { get; set; }
        public Nullable<int> UOW_SECTIONOID { get; set; }
        public Nullable<int> UOW_SECTIONTID { get; set; }
        public Nullable<int> UOW_EMPLOYEEID { get; set; }
        public System.DateTime UOW_DOCUDATE { get; set; }
        public string UOW_OK { get; set; }
        public Nullable<System.DateTime> UOW_OKDATE { get; set; }
        public string UOW_STORNO { get; set; }
        public Nullable<System.DateTime> UOW_STORNODAT { get; set; }
        public string UOW_CUSTOMERNAME { get; set; }
        public string UOW_COUNTRY { get; set; }
        public string UOW_ZIP { get; set; }
        public string UOW_CITY { get; set; }
        public string UOW_STREET { get; set; }
        public string UOW_ACCOUNTNUMBER { get; set; }
        public string UOW_COMMENT { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        public virtual SECTION SECTION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUPPLYORDERMOD> SUPPLYORDERMOD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUPPLYORDERMOD> SUPPLYORDERMOD1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UNONTHEWAY_DETAIL> UNONTHEWAY_DETAIL { get; set; }
        public virtual WAREHOUSE WAREHOUSE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UNONTHEWAY_EXPANDED> UNONTHEWAY_EXPANDED { get; set; }
    }
}
