//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class UNOPTIONED_DETAIL
    {
        public int OID { get; set; }
        public int TID { get; set; }
        public int UOPD_UNOPTIONEDOID { get; set; }
        public int UOPD_UNOPTIONEDTID { get; set; }
        public int UOPD_PRODUCTOID { get; set; }
        public int UOPD_PRODUCTTID { get; set; }
        public double UOPD_QUANTITY { get; set; }
        public Nullable<double> UOPD_CQUANTITY { get; set; }
        public int UOPD_QUID { get; set; }
    
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual QUANTITY_UNIT QUANTITY_UNIT { get; set; }
        public virtual UNOPTIONED UNOPTIONED { get; set; }
    }
}
