//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class UNOPTIONED_EXPANDED
    {
        public string UOPE_AUTOFREESTOCK { get; set; }
        public Nullable<double> UOPE_C_QUANTITY { get; set; }
        public Nullable<int> UOPE_C_QUID { get; set; }
        public string UOPE_CONTROLLED { get; set; }
        public Nullable<int> UOPE_DETAIL_OID { get; set; }
        public Nullable<int> UOPE_DETAIL_TID { get; set; }
        public string UOPE_FORCE { get; set; }
        public Nullable<System.DateTime> UOPE_LIMITDAY { get; set; }
        public int UOPE_MASTER_OID { get; set; }
        public int UOPE_MASTER_TID { get; set; }
        public Nullable<double> UOPE_MB_QUANTITY { get; set; }
        public Nullable<int> UOPE_MB_QUID { get; set; }
        public Nullable<double> UOPE_MN_QUANTITY { get; set; }
        public Nullable<int> UOPE_MN_QUID { get; set; }
        public Nullable<int> UOPE_NOTICEOID { get; set; }
        public string UOPE_NUMTYPE { get; set; }
        public int OID { get; set; }
        public Nullable<int> UOPE_PFDIVISIONOID { get; set; }
        public Nullable<int> UOPE_PFDIVISIONTID { get; set; }
        public Nullable<int> UOPE_PRODUCTOID { get; set; }
        public Nullable<int> UOPE_PRODUCTTID { get; set; }
        public Nullable<double> UOPE_QUANTITY { get; set; }
        public Nullable<int> UOPE_QUID { get; set; }
        public string UOPE_SERIALNUMBER { get; set; }
        public Nullable<double> UOPE_STOCKQUANTITY { get; set; }
        public string UOPE_TAG { get; set; }
        public int TID { get; set; }
        public Nullable<double> UOPE_UNITPRICEBC { get; set; }
        public Nullable<double> UOPE_V_QUANTITY { get; set; }
        public Nullable<int> UOPE_V_QUID { get; set; }
    
        public virtual C_QUANTITY_UNIT C_QUANTITY_UNIT { get; set; }
        public virtual MB_QUANTITY_UNIT MB_QUANTITY_UNIT { get; set; }
        public virtual MN_QUANTITY_UNIT MN_QUANTITY_UNIT { get; set; }
        public virtual PFDIVISION PFDIVISION { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual QUANTITY_UNIT QUANTITY_UNIT { get; set; }
        public virtual UNOPTIONED UNOPTIONED { get; set; }
        public virtual V_QUANTITY_UNIT V_QUANTITY_UNIT { get; set; }
    }
}
