//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class VACS_QUEUE
    {
        public string VQ_CALCBATCHID { get; set; }
        public int VQ_IDX { get; set; }
        public int VQ_BLOCKIDX { get; set; }
        public Nullable<int> VQ_CONTELEM { get; set; }
        public string VQ_SUPERBLOCKID { get; set; }
    }
}
