//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class VANLINE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VANLINE()
        {
            this.CUSTVANLINE = new HashSet<CUSTVANLINE>();
            this.CUSTVANLINE1 = new HashSet<CUSTVANLINE>();
            this.DELIVERYCONTRACT = new HashSet<DELIVERYCONTRACT>();
            this.GOVANLINEPASS = new HashSet<GOVANLINEPASS>();
            this.GOVANLINEPASS1 = new HashSet<GOVANLINEPASS>();
            this.JUSTVANLINEPASS = new HashSet<JUSTVANLINEPASS>();
            this.JUSTVANLINEPASS1 = new HashSet<JUSTVANLINEPASS>();
            this.VANLINEPASS = new HashSet<VANLINEPASS>();
            this.WAYBILL = new HashSet<WAYBILL>();
            this.SHIPPINGLOG = new HashSet<SHIPPINGLOG>();
            this.VANLINEPASS1 = new HashSet<VANLINEPASS>();
            this.WAYBILL1 = new HashSet<WAYBILL>();
        }
    
        public int OID { get; set; }
        public int TID { get; set; }
        public string VL_VANLINENAME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUSTVANLINE> CUSTVANLINE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUSTVANLINE> CUSTVANLINE1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DELIVERYCONTRACT> DELIVERYCONTRACT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GOVANLINEPASS> GOVANLINEPASS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GOVANLINEPASS> GOVANLINEPASS1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JUSTVANLINEPASS> JUSTVANLINEPASS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JUSTVANLINEPASS> JUSTVANLINEPASS1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VANLINEPASS> VANLINEPASS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WAYBILL> WAYBILL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SHIPPINGLOG> SHIPPINGLOG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VANLINEPASS> VANLINEPASS1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WAYBILL> WAYBILL1 { get; set; }
    }
}
