//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEHICLE_USER
    {
        public int OID { get; set; }
        public int TID { get; set; }
        public int VU_VEHICLEOID { get; set; }
        public int VU_VEHICLETID { get; set; }
        public int VU_EMPLOYEEID { get; set; }
        public Nullable<System.DateTime> VU_USINGSTARTDATE { get; set; }
        public Nullable<System.DateTime> VU_USINGENDDATE { get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        public virtual VEHICLE VEHICLE { get; set; }
    }
}
