//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class WAREHOUSEBANNEDPRODUCT
    {
        public int WBP_ID { get; set; }
        public int WBP_WAREHOUSEID { get; set; }
        public Nullable<int> WBP_PRODUCTGROUPID { get; set; }
        public Nullable<int> WBP_PRODUCTGROUPSNAMEID { get; set; }
    
        public virtual PRODUCTGROUP PRODUCTGROUP { get; set; }
        public virtual PRODUCTGROUPSNAME PRODUCTGROUPSNAME { get; set; }
        public virtual WAREHOUSE WAREHOUSE { get; set; }
    }
}
