//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFCONTROLS
    {
        public int CID { get; set; }
        public int WFC_IBORD { get; set; }
        public int WFC_BID { get; set; }
        public string WFC_NAME { get; set; }
        public string WFC_CAPTION { get; set; }
        public string WFC_TYPE { get; set; }
        public Nullable<int> WFC_MAXLENGTH { get; set; }
        public Nullable<int> WFC_CONTROLWIDTH { get; set; }
        public Nullable<int> WFC_VISIBLELENGTH { get; set; }
        public string WFC_FORMAT { get; set; }
        public string WFC_VISIBLE { get; set; }
        public string WFC_VISIBLEONWRITE { get; set; }
        public string WFC_WRITEABLE { get; set; }
        public string WFC_DEFAULTREF { get; set; }
        public string WFC_DEFAULTNAME { get; set; }
        public string WFC_CHECKEXPRESSION { get; set; }
        public string WFC_ERROR { get; set; }
        public string WFC_REQUIRED { get; set; }
        public string WFC_DOMAINMODE { get; set; }
        public string WFC_DOMAININFO { get; set; }
        public string WFC_ISBUTTON { get; set; }
        public string WFC_USERCONTROL { get; set; }
        public string WFC_USERNOTIFY { get; set; }
        public Nullable<int> WFC_BLOCKCOUNT { get; set; }
        public Nullable<int> WFC_INTERNALBLOCKBID { get; set; }
    
        public virtual WFBLOCKS WFBLOCKS { get; set; }
        public virtual WFBLOCKS WFBLOCKS1 { get; set; }
    }
}
