//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFDATAINT
    {
        public int WFDI_OID { get; set; }
        public int WFDI_TID { get; set; }
        public int WFDI_SID { get; set; }
        public int WFDI_CID { get; set; }
        public Nullable<int> WFDI_DATA { get; set; }
    }
}
