//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFDATAFLT
    {
        public int WFDF_OID { get; set; }
        public int WFDF_TID { get; set; }
        public int WFDF_SID { get; set; }
        public int WFDF_CID { get; set; }
        public Nullable<double> WFDF_DATA { get; set; }
    }
}
