//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFDATATXT
    {
        public int WFDT_OID { get; set; }
        public int WFDT_TID { get; set; }
        public int WFDT_SID { get; set; }
        public int WFDT_CID { get; set; }
        public int WFDT_RORD { get; set; }
        public string WFDT_DATA { get; set; }
    }
}
