//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFSTATEDEFS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WFSTATEDEFS()
        {
            this.WFDATASTA = new HashSet<WFDATASTA>();
            this.WFEVENTS = new HashSet<WFEVENTS>();
            this.WFSTATEDOCS = new HashSet<WFSTATEDOCS>();
            this.WFSTATENEXT = new HashSet<WFSTATENEXT>();
            this.WFSTATENEXT1 = new HashSet<WFSTATENEXT>();
        }
    
        public int STATEID { get; set; }
        public string WFSD_NAME { get; set; }
        public string WFSD_ACTIONNAME { get; set; }
        public string WFSD_CLASS { get; set; }
        public string WFSD_REMINDBACK { get; set; }
        public int WFSD_BID { get; set; }
        public string WFSD_CANVIEW { get; set; }
        public string WFSD_CANGET { get; set; }
        public string WFSD_CANBEGIN { get; set; }
        public string WFSD_CANFINISH { get; set; }
        public string WFSD_CANFORWARD { get; set; }
        public string WFSD_NOTIFY { get; set; }
        public string WFSD_DESCRIPTION { get; set; }
        public string WFSD_STARTDAY { get; set; }
        public string WFSD_STARTOFFSET { get; set; }
        public string WFSD_TIMELENGTH { get; set; }
        public Nullable<double> WFSD_TIMESCALE { get; set; }
        public string WFSD_DEADLINE { get; set; }
        public string WFSD_PRIORITY { get; set; }
        public string WFSD_THEME { get; set; }
        public string WFSD_TIMINGTO { get; set; }
        public string WFSD_PICTUREGUID { get; set; }
        public Nullable<int> WFSD_EV_AFTERCREATE { get; set; }
        public Nullable<int> WFSD_EV_BEFORECLOSE { get; set; }
        public Nullable<int> WFSD_EV_AFTERCLOSE { get; set; }
    
        public virtual WFBLOCKS WFBLOCKS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFDATASTA> WFDATASTA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFEVENTS> WFEVENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFSTATEDOCS> WFSTATEDOCS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFSTATENEXT> WFSTATENEXT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFSTATENEXT> WFSTATENEXT1 { get; set; }
    }
}
