//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFSTATEDOCS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WFSTATEDOCS()
        {
            this.WFDOCMAP = new HashSet<WFDOCMAP>();
        }
    
        public int CONNID { get; set; }
        public int WFDC_STATEID { get; set; }
        public int WFDC_IBORD { get; set; }
        public string WFDC_DOCUMENT { get; set; }
        public string WFDC_REFERENCE { get; set; }
        public string WFDC_SKIPPING { get; set; }
        public string WFDC_CANCREATE { get; set; }
        public string WFDC_CANUPDATE { get; set; }
        public string WFDC_CANCLOSE { get; set; }
        public string WFDC_CANSTORNO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFDOCMAP> WFDOCMAP { get; set; }
        public virtual WFSTATEDEFS WFSTATEDEFS { get; set; }
    }
}
